/** Column headers matching the real Don Bosco admission Excel (`fiels.txt` shape). */
export const SEM1_ADMISSION_TEMPLATE_HEADERS = [
  'Application Number',
  'Photo',
  'Full Name',
  'Email',
  'Mobile Number',
  'Date of Birth',
  'Gender',
  'Shift',
  'Programme',
  'Admission Batch',
  'Stream',
  'Major Subject',
  'Minor Subject',
  'MDC Choice',
  'AEC',
  'SEC',
  'VAC',
  'Section Code',
  'Marital Status',
  'Blood Group',
  'Category',
  'Race/Tribe',
  'Religion',
  'Denomination',
  'Class XII Board',
  'Class XII Stream',
  'Differently Abled',
  'Economically Weaker',
  'Address in Tura',
  'Same as Tura (Check box)',
  'Home Address',
  'Aadhaar Number',
  'State',
  'Father Name',
  'Father Age',
  'Father Occupation',
  'Father Contact',
  'Mother Name',
  'Mother Age',
  'Mother Occupation',
  'Mother Contact',
  'Local Guardian Name',
  'Local Guardian Age',
  'Local Guardian Occupation',
  'Local Guardian Contact',
  'Household Area Type',
  'Board Roll Number',
  'Board Year',
  'Board Total Marks',
  'Board Percentage',
  'Board Division',
  'Board Name',
  'Board Registration Type',
  'Class XII Marks (Minimum 5 Subjects)',
  'CUET Applied',
  'CUET Roll Number',
  'Last Institution Attended',
] as const;

export const SEM1_ADMISSION_TEMPLATE_HELPERS: Record<string, string> = {
  'Application Number': 'APP-2026-0001 or leave blank to auto-generate',
  Programme: 'BA-ECO, BA-GEO, etc.',
  'Admission Batch': 'BATCH-2026',
  Stream: 'ARTS',
  Shift: 'DAY',
  'Major Subject': 'Economics, Education, English, etc. (department name)',
  'Minor Subject': 'Valid minor department for selected major',
  'MDC Choice': 'Culture and Society (paper title for shift curriculum)',
  AEC: 'Alternative English (paper title)',
  SEC: 'Motivation (paper title)',
  VAC: 'Environment Studies (auto-assigned when configured)',
  'Section Code': 'A, B, or Core',
};

export const SEM1_ADMISSION_SAMPLE_ROW: Record<string, string> = {
  'Application Number': 'APP-2026-0001',
  'Full Name': 'Priangshuman Marak',
  Email: 'student@example.edu',
  'Mobile Number': '9876500000',
  Gender: 'Male',
  Shift: 'DAY',
  Programme: 'BA-ECO',
  'Admission Batch': 'BATCH-2026',
  Stream: 'ARTS',
  'Major Subject': 'Economics',
  'Minor Subject': 'Political Science',
  'MDC Choice': 'Culture and Society',
  AEC: 'Alternative English',
  SEC: 'Motivation',
  VAC: 'Environment Studies',
  'Section Code': 'A',
};
