const HEADER_ALIASES: Record<string, string> = {
  'application number': 'applicationNumber',
  applicationnumber: 'applicationNumber',
  'admission number': 'admissionNumber',
  admissionnumber: 'admissionNumber',
  'registration number': 'registrationNumber',
  registrationnumber: 'registrationNumber',
  enrollmentnumber: 'enrollmentNumber',
  'roll number': 'rollNumber',
  rollnumber: 'rollNumber',
  'full name': 'fullName',
  fullname: 'fullName',
  email: 'email',
  mobile: 'mobile',
  'mobile number': 'mobile',
  mobilenumber: 'mobileNumber',
  programme: 'programmeCode',
  program: 'programmeCode',
  'programme code': 'programmeCode',
  programmecode: 'programmeCode',
  programcode: 'programmeCode',
  'program code': 'programmeCode',
  batch: 'batchCode',
  'batch code': 'batchCode',
  batchcode: 'batchCode',
  'admission batch': 'batchCode',
  admissionbatch: 'batchCode',
  stream: 'streamCode',
  'stream code': 'streamCode',
  streamcode: 'streamCode',
  shift: 'shiftCode',
  'shift code': 'shiftCode',
  shiftcode: 'shiftCode',
  session: 'academicSession',
  'academic session': 'academicSession',
  academicsession: 'academicSession',
  'current semester': 'currentSemester',
  currentsemester: 'currentSemester',
  'student status': 'studentStatus',
  studentstatus: 'studentStatus',
  category: 'categoryCode',
  'category code': 'categoryCode',
  categorycode: 'categoryCode',
  religion: 'religion',
  aadhaar: 'aadhaar',
  'aadhaar number': 'aadhaar',
  aadhaarnumber: 'aadhaar',
  nationalid: 'aadhaar',
  'father name': 'fatherName',
  fathername: 'fatherName',
  'mother name': 'motherName',
  mothername: 'motherName',
  rfid: 'rfidNumber',
  'rfid number': 'rfidNumber',
  rfidnumber: 'rfidNumber',
  'major dept code': 'majorDeptCode',
  majordeptcode: 'majorDeptCode',
  department: 'departmentCode',
  departmentcode: 'departmentCode',
  abc_id: 'abcId',
  abcid: 'abcId',
  'abc id': 'abcId',
  gender: 'gender',
  'date of birth': 'dateOfBirth',
  dateofbirth: 'dateOfBirth',
  'major subject slug': 'majorSubjectSlug',
  majorsubjectslug: 'majorSubjectSlug',
  'major course code': 'majorCourseCode',
  majorcoursecode: 'majorCourseCode',
  major_code: 'majorCourseCode',
  majorcode: 'majorCourseCode',
  'minor course code': 'minorCourseCode',
  minorcoursecode: 'minorCourseCode',
  minor_code: 'minorCourseCode',
  minorcode: 'minorCourseCode',
  'mdc course code': 'mdcCourseCode',
  mdccoursecode: 'mdcCourseCode',
  mdc_code: 'mdcCourseCode',
  mdccode: 'mdcCourseCode',
  'aec course code': 'aecCourseCode',
  aeccoursecode: 'aecCourseCode',
  aec_code: 'aecCourseCode',
  aeccode: 'aecCourseCode',
  'sec course code': 'secCourseCode',
  seccoursecode: 'secCourseCode',
  sec_code: 'secCourseCode',
  seccode: 'secCourseCode',
  'vac course code': 'vacCourseCode',
  vaccoursecode: 'vacCourseCode',
  vac_code: 'vacCourseCode',
  vaccode: 'vacCourseCode',
  'vtc course code': 'vtcCourseCode',
  vtccoursecode: 'vtcCourseCode',
  vtc_code: 'vtcCourseCode',
  vtccode: 'vtcCourseCode',
  'major course code 2': 'majorCourseCode2',
  majorcoursecode2: 'majorCourseCode2',
  'major code 2': 'majorCourseCode2',
  majorcode2: 'majorCourseCode2',
  major_code_2: 'majorCourseCode2',
  majorcode_2: 'majorCourseCode2',
  'minor subject slug': 'minorSubjectSlug',
  minorsubjectslug: 'minorSubjectSlug',
  'major subject': 'majorSubject',
  majorsubject: 'majorSubject',
  'minor subject': 'minorSubject',
  minorsubject: 'minorSubject',
  'mdc subject': 'mdcSubject',
  mdcsubject: 'mdcSubject',
  'mdc choice': 'mdcSubject',
  mdcchoice: 'mdcSubject',
  mdc: 'mdcSubject',
  aec: 'aecSubject',
  'aec subject': 'aecSubject',
  aecsubject: 'aecSubject',
  sec: 'secSubject',
  'sec subject': 'secSubject',
  secsubject: 'secSubject',
  vac: 'vacSubject',
  'vac subject': 'vacSubject',
  vacsubject: 'vacSubject',
  vtc: 'vtcSubject',
  'vtc subject': 'vtcSubject',
  vtcsubject: 'vtcSubject',
  'major section': 'majorSection',
  majorsection: 'majorSection',
  'minor section': 'minorSection',
  minorsection: 'minorSection',
  'mdc section': 'mdcSection',
  mdcsection: 'mdcSection',
  'aec section': 'aecSection',
  aecsection: 'aecSection',
  'sec section': 'secSection',
  secsection: 'secSection',
  'vac section': 'vacSection',
  vacsection: 'vacSection',
  'vtc section': 'vtcSection',
  vtcsection: 'vtcSection',
  'local guardian name': 'localGuardianName',
  localguardianname: 'localGuardianName',
  'address in tura': 'turaLine1',
  addressintura: 'turaLine1',
  'major subject 2': 'majorSubject2',
  majorsubject2: 'majorSubject2',
  'major department': 'majorDepartment',
  majordepartment: 'majorDepartment',
  'mdc paper': 'mdcPaper',
  mdcpaper: 'mdcPaper',
  'aec paper': 'aecPaper',
  aecpaper: 'aecPaper',
  'sec paper': 'secPaper',
  secpaper: 'secPaper',
  'vtc paper': 'vtcPaper',
  vtcpaper: 'vtcPaper',
  'minor subject 2': 'minorSubject2',
  minorsubject2: 'minorSubject2',
  'elective subject': 'electiveSubject',
  electivesubject: 'electiveSubject',
  'skill paper': 'skillPaper',
  skillpaper: 'skillPaper',
  'tutorial group': 'tutorialGroup',
  tutorialgroup: 'tutorialGroup',
  'lab batch': 'labBatch',
  labbatch: 'labBatch',
  'major paper index': 'majorPaperIndex',
  majorpaperindex: 'majorPaperIndex',
  'section code': 'sectionCode',
  sectioncode: 'sectionCode',
  coursecode: 'courseCode',
  'course code': 'courseCode',
  code: 'courseCode',
  'course title': 'courseTitle',
  coursetitle: 'courseTitle',
  title: 'courseTitle',
  'delivery type': 'deliveryType',
  deliverytype: 'deliveryType',
  'theory credits': 'theoryCredits',
  theorycredits: 'theoryCredits',
  'practical credits': 'practicalCredits',
  practicalcredits: 'practicalCredits',
  'weekly theory hours': 'theoryHoursPerWeek',
  'theory hours': 'theoryHoursPerWeek',
  theoryhours: 'theoryHoursPerWeek',
  'weekly practical hours': 'practicalHoursPerWeek',
  'practical hours': 'practicalHoursPerWeek',
  practicalhours: 'practicalHoursPerWeek',
  'total theory contact hours': 'totalTheoryContactHours',
  'theory contact hours': 'totalTheoryContactHours',
  totaltheorycontacthours: 'totalTheoryContactHours',
  'total practical contact hours': 'totalPracticalContactHours',
  'practical contact hours': 'totalPracticalContactHours',
  totalpracticalcontacthours: 'totalPracticalContactHours',
  'cbcs catalog type': 'courseType',
  'catalog type': 'courseType',
  cbcs: 'courseType',
  coursetype: 'courseType',
  'department code': 'departmentCode',
  description: 'description',
  staffcode: 'employeeCode',
  'staff code': 'employeeCode',
  employeecode: 'employeeCode',
  'employee code': 'employeeCode',
  stafftype: 'staffType',
  'staff type': 'staffType',
  designation: 'designationCode',
  designationcode: 'designationCode',
  'designation code': 'designationCode',
  joiningdate: 'joiningDate',
  'joining date': 'joiningDate',
  employmentstatus: 'employmentStatus',
  'employment status': 'employmentStatus',
  subjectcodes: 'subjectCodes',
  'subject codes': 'subjectCodes',
  workloadlimit: 'workloadLimit',
  'workload limit': 'workloadLimit',
  createportaluser: 'createPortalUser',
  'create portal user': 'createPortalUser',
  username: 'username',
  password: 'password',
  experienceyears: 'experienceYears',
  'experience years': 'experienceYears',
  photo: 'photo',
  photoUrl: 'photoUrl',
  'photo url': 'photoUrl',
  photourl: 'photoUrl',
  'marital status': 'maritalStatus',
  maritalstatus: 'maritalStatus',
  'race/tribe': 'raceTribe',
  racetribe: 'raceTribe',
  denomination: 'denomination',
  'class xii board': 'classXiiBoard',
  classxiiboard: 'classXiiBoard',
  'class xii stream': 'classXiiStream',
  classxiistream: 'classXiiStream',
  'differently abled': 'differentlyAbled',
  differentlyabled: 'differentlyAbled',
  'economically weaker': 'economicallyWeaker',
  economicallyweaker: 'economicallyWeaker',
  'same as tura (check box)': 'sameAsTura',
  'same as tura': 'sameAsTura',
  sameastura: 'sameAsTura',
  'home address': 'homeLine1',
  homeaddress: 'homeLine1',
  state: 'state',
  'father age': 'fatherAge',
  fatherage: 'fatherAge',
  'father occupation': 'fatherOccupation',
  fatheroccupation: 'fatherOccupation',
  'father contact': 'fatherContact',
  fathercontact: 'fatherContact',
  'mother age': 'motherAge',
  motherage: 'motherAge',
  'mother occupation': 'motherOccupation',
  motheroccupation: 'motherOccupation',
  'mother contact': 'motherContact',
  mothercontact: 'motherContact',
  'local guardian age': 'localGuardianAge',
  localguardianage: 'localGuardianAge',
  'local guardian occupation': 'localGuardianOccupation',
  localguardianoccupation: 'localGuardianOccupation',
  'local guardian contact': 'localGuardianContact',
  localguardiancontact: 'localGuardianContact',
  'household area type': 'householdAreaType',
  householdareatype: 'householdAreaType',
  'board roll number': 'boardRollNumber',
  boardrollnumber: 'boardRollNumber',
  'board year': 'boardYear',
  boardyear: 'boardYear',
  'board total marks': 'boardTotalMarks',
  boardtotalmarks: 'boardTotalMarks',
  'board percentage': 'boardPercentage',
  boardpercentage: 'boardPercentage',
  'board division': 'boardDivision',
  boarddivision: 'boardDivision',
  'board name': 'boardName',
  boardname: 'boardName',
  'board registration type': 'boardRegistrationType',
  boardregistrationtype: 'boardRegistrationType',
  'class xii marks (minimum 5 subjects)': 'classXiiMarks',
  classxiimarks: 'classXiiMarks',
  'cuet applied': 'cuetApplied',
  cuetapplied: 'cuetApplied',
  'cuet roll number': 'cuetRollNumber',
  cuetrollnumber: 'cuetRollNumber',
  'last institution attended': 'lastInstitutionAttended',
  lastinstitutionattended: 'lastInstitutionAttended',
  bloodgroup: 'bloodGroup',
  'blood group': 'bloodGroup',
  pincode: 'pinCode',
  'pin code': 'pinCode',
  hod: 'hod',
  classteacher: 'classTeacher',
  'class teacher': 'classTeacher',
  roleslug: 'roleSlug',
  'role slug': 'roleSlug',
};

export function normalizeHeader(header: string): string {
  const key = header.trim().toLowerCase().replace(/\s+/g, ' ');
  return HEADER_ALIASES[key] ?? key.replace(/\s+/g, '');
}

export function mapRowHeaders(
  headers: string[],
  values: unknown[],
): Record<string, unknown> {
  const row: Record<string, unknown> = {};
  headers.forEach((h, i) => {
    if (!h?.trim()) return;
    const key = normalizeHeader(h);
    row[key] = values[i];
  });
  return row;
}

export const NEP_FORBIDDEN_HEADER_KEYS = new Set([
  'major',
  'minor',
  'mdc',
  'aec',
  'sec',
  'vac',
  'vtc',
  'semester',
  'semestersequence',
  'nepcategory',
  'category',
]);
