export type ImportFieldSection =
  | 'admission'
  | 'personal'
  | 'parents'
  | 'address'
  | 'academic_history'
  | 'subjects_sem1'
  | 'subjects_sem3'
  | 'subjects_sem5'
  | 'identity';

export type ImportFieldVisibility =
  | 'visible'
  | 'hidden'
  | 'optional'
  | 'mandatory';

export type StudentImportFieldDef = {
  key: string;
  header: string;
  section: ImportFieldSection;
  required: boolean;
  visible: boolean;
  readOnly: boolean;
  defaultValue?: string;
  helper?: string;
};

export const IMPORT_SECTION_LABELS: Record<ImportFieldSection, string> = {
  admission: 'Section 1 — Admission Information',
  personal: 'Section 2 — Personal Information',
  parents: 'Section 3 — Parent / Guardian Information',
  address: 'Section 4 — Address',
  academic_history: 'Section 5 — Previous Academic Details',
  subjects_sem1: 'Section 6a — Semester 1 Subject Selection',
  subjects_sem3: 'Section 6b — Semester 3 Subject Selection',
  subjects_sem5: 'Section 6c — Semester 5 Subject Selection',
  identity: 'Section 7 — Identity & Services',
};

/** Configurable import field registry — drives template headers and validation rules. */
export const STUDENT_IMPORT_FIELD_REGISTRY: StudentImportFieldDef[] = [
  // Admission
  {
    key: 'academicSession',
    header: 'Academic Year',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'e.g. 2026-27 — must match admission batch entry session',
  },
  {
    key: 'admissionDate',
    header: 'Admission Date',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'YYYY-MM-DD',
  },
  {
    key: 'admissionStatus',
    header: 'Admission Status',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'ACTIVE, PROVISIONAL, CANCELLED',
  },
  {
    key: 'admissionNumber',
    header: 'Admission Number',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'applicationNumber',
    header: 'Application Number',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'formNumber',
    header: 'Form Number',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'registrationNumber',
    header: 'Registration Number',
    section: 'admission',
    required: true,
    visible: true,
    readOnly: false,
    helper: 'College registration number (required)',
  },
  {
    key: 'rollNumber',
    header: 'Roll Number',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'universityRollNumber',
    header: 'University Roll Number',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'universityRegistrationNumber',
    header: 'University Registration Number',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'abcId',
    header: 'ABC ID',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
    helper: '12-digit Academic Bank of Credits ID',
  },
  {
    key: 'shift',
    header: 'Shift',
    section: 'admission',
    required: true,
    visible: true,
    readOnly: false,
  },
  {
    key: 'programme',
    header: 'Programme',
    section: 'admission',
    required: true,
    visible: true,
    readOnly: false,
  },
  {
    key: 'department',
    header: 'Department',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'Department code — optional if Major Department is set',
  },
  {
    key: 'admissionBatch',
    header: 'Admission Batch',
    section: 'admission',
    required: true,
    visible: true,
    readOnly: false,
  },
  {
    key: 'stream',
    header: 'Stream',
    section: 'admission',
    required: true,
    visible: true,
    readOnly: false,
  },
  {
    key: 'currentSemester',
    header: 'Semester',
    section: 'admission',
    required: true,
    visible: true,
    readOnly: false,
    helper: '1, 3, or 5 for subject columns below',
  },
  // Personal
  {
    key: 'fullName',
    header: 'Full Name',
    section: 'personal',
    required: true,
    visible: true,
    readOnly: false,
  },
  {
    key: 'gender',
    header: 'Gender',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'Male, Female, Other',
  },
  {
    key: 'dateOfBirth',
    header: 'Date of Birth',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'YYYY-MM-DD',
  },
  {
    key: 'bloodGroup',
    header: 'Blood Group',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'category',
    header: 'Category',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'ST, SC, OBC, GENERAL, EWS',
  },
  {
    key: 'tribe',
    header: 'Tribe / Race',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'religion',
    header: 'Religion',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'denomination',
    header: 'Denomination',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'nationality',
    header: 'Nationality',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'aadhaar',
    header: 'Aadhaar Number',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'email',
    header: 'Email Address',
    section: 'personal',
    required: true,
    visible: true,
    readOnly: false,
  },
  {
    key: 'mobile',
    header: 'Student Mobile Number',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'whatsappNumber',
    header: 'WhatsApp Number',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'photoFileName',
    header: 'Photo File Name',
    section: 'personal',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'Optional — match filename in photo bulk upload folder',
  },
  // Parents
  {
    key: 'fatherName',
    header: "Father's Name",
    section: 'parents',
    required: true,
    visible: true,
    readOnly: false,
  },
  {
    key: 'fatherMobile',
    header: "Father's Mobile",
    section: 'parents',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'fatherOccupation',
    header: "Father's Occupation",
    section: 'parents',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'motherName',
    header: "Mother's Name",
    section: 'parents',
    required: true,
    visible: true,
    readOnly: false,
  },
  {
    key: 'motherMobile',
    header: "Mother's Mobile",
    section: 'parents',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'motherOccupation',
    header: "Mother's Occupation",
    section: 'parents',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'guardianName',
    header: 'Guardian Name',
    section: 'parents',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'guardianMobile',
    header: 'Guardian Mobile',
    section: 'parents',
    required: false,
    visible: true,
    readOnly: false,
  },
  // Present address
  {
    key: 'presentLine1',
    header: 'Present Address',
    section: 'address',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'House / locality (Tura / present)',
  },
  {
    key: 'presentVillage',
    header: 'Present Village / Town',
    section: 'address',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'presentPoliceStation',
    header: 'Present Police Station',
    section: 'address',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'presentDistrict',
    header: 'Present District',
    section: 'address',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'presentState',
    header: 'Present State',
    section: 'address',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'presentPinCode',
    header: 'Present PIN Code',
    section: 'address',
    required: false,
    visible: true,
    readOnly: false,
  },
  // Permanent address
  {
    key: 'permanentLine1',
    header: 'Permanent Address',
    section: 'address',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'permanentVillage',
    header: 'Permanent Village / Town',
    section: 'address',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'permanentDistrict',
    header: 'Permanent District',
    section: 'address',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'permanentState',
    header: 'Permanent State',
    section: 'address',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'permanentPinCode',
    header: 'Permanent PIN Code',
    section: 'address',
    required: false,
    visible: true,
    readOnly: false,
  },
  // Academic history
  {
    key: 'lastInstitution',
    header: 'Institution Last Attended',
    section: 'academic_history',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'boardName',
    header: 'Board / University',
    section: 'academic_history',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'boardRegistrationType',
    header: 'Registration / Private',
    section: 'academic_history',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'boardYear',
    header: 'Year of Passing',
    section: 'academic_history',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'boardTotalMarks',
    header: 'Total Marks',
    section: 'academic_history',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'boardPercentage',
    header: 'Percentage',
    section: 'academic_history',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'boardDivision',
    header: 'Division',
    section: 'academic_history',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'cuetScore',
    header: 'CUET Marks',
    section: 'academic_history',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'cuetRollNumber',
    header: 'CUET Roll Number',
    section: 'academic_history',
    required: false,
    visible: true,
    readOnly: false,
  },
  // Sem 1 subjects
  {
    key: 'majorDepartment',
    header: 'Major Department',
    section: 'subjects_sem1',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'Sem 1 — select department name (not code)',
  },
  {
    key: 'minorDepartment',
    header: 'Minor Department',
    section: 'subjects_sem1',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'mdcDepartment',
    header: 'MDC',
    section: 'subjects_sem1',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'Paper title from dropdown',
  },
  {
    key: 'aecPaper',
    header: 'AEC',
    section: 'subjects_sem1',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'secPaper',
    header: 'SEC',
    section: 'subjects_sem1',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'vacNote',
    header: 'VAC',
    section: 'subjects_sem1',
    required: false,
    visible: true,
    readOnly: true,
    defaultValue: 'Auto-assigned',
    helper: 'VAC is registered automatically for Sem 1',
  },
  // Sem 3 subjects
  {
    key: 'majorDepartmentSem3',
    header: 'Major Department (Sem 3)',
    section: 'subjects_sem3',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'Sem 3 — auto-assigns Major Paper 1 & 2',
  },
  {
    key: 'secondMajorDepartment',
    header: 'Second Major Department',
    section: 'subjects_sem3',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'Optional second major track if applicable',
  },
  {
    key: 'mdcPaperSem3',
    header: 'MDC (Sem 3)',
    section: 'subjects_sem3',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'aecPaperSem3',
    header: 'AEC (Sem 3)',
    section: 'subjects_sem3',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'secPaperSem3',
    header: 'SEC (Sem 3)',
    section: 'subjects_sem3',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'vtcPaper',
    header: 'VTC',
    section: 'subjects_sem3',
    required: false,
    visible: true,
    readOnly: false,
  },
  // Sem 5 subjects
  {
    key: 'majorDepartmentSem5',
    header: 'Major Department (Sem 5)',
    section: 'subjects_sem5',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'Sem 5 — auto-assigns Major Papers 1–3',
  },
  {
    key: 'minorDepartmentSem5',
    header: 'Minor Department (Sem 5)',
    section: 'subjects_sem5',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'internshipArea',
    header: 'Internship Subject',
    section: 'subjects_sem5',
    required: false,
    visible: true,
    readOnly: false,
  },
  // Identity
  {
    key: 'rfid',
    header: 'RFID Number',
    section: 'identity',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'libraryCardNumber',
    header: 'Library Card Number',
    section: 'identity',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'hostel',
    header: 'Hostel',
    section: 'identity',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'YES / NO or HOSTELLER / DAY_SCHOLAR',
  },
  {
    key: 'transport',
    header: 'Transport',
    section: 'identity',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'YES / NO — stored as remark until transport module links',
  },
  {
    key: 'scholarshipCategory',
    header: 'Scholarship Category',
    section: 'identity',
    required: false,
    visible: true,
    readOnly: false,
  },
  {
    key: 'studentStatus',
    header: 'Student Status',
    section: 'admission',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'STUDYING, ACTIVE, etc.',
  },
  {
    key: 'sectionCode',
    header: 'Section Code',
    section: 'subjects_sem1',
    required: false,
    visible: true,
    readOnly: false,
    helper: 'A, B, or Core',
  },
];

export const FULL_ADMISSION_IMPORT_HEADERS =
  STUDENT_IMPORT_FIELD_REGISTRY.filter(
    (f) => f.visible && f.key !== 'vacNote',
  ).map((f) => f.header);

export const FULL_ADMISSION_IMPORT_HELPERS = Object.fromEntries(
  STUDENT_IMPORT_FIELD_REGISTRY.filter((f) => f.helper).map((f) => [
    f.header,
    f.helper!,
  ]),
);

export const FULL_ADMISSION_HIDDEN_SHEETS = {
  programmes: 'FA Programmes',
  shifts: 'FA Shifts',
  batches: 'FA Batches',
  streams: 'FA Streams',
  academicYears: 'FA Academic Years',
  departments: 'FA Departments',
  categories: 'FA Categories',
  religions: 'FA Religions',
  bloodGroups: 'FA Blood Groups',
  tribes: 'FA Tribes',
  denominations: 'FA Denominations',
  nationalities: 'FA Nationalities',
  sem1MajorDepartments: 'FA Sem1 Majors',
  sem1Mdc: 'FA Sem1 MDC',
  sem1Aec: 'FA Sem1 AEC',
  sem1Sec: 'FA Sem1 SEC',
  sem1AllMinors: 'FA Sem1 Minor Depts',
  sem3MajorDepartments: 'FA Sem3 Majors',
  sem3Mdc: 'FA Sem3 MDC',
  sem3Aec: 'FA Sem3 AEC',
  sem3Sec: 'FA Sem3 SEC',
  sem3Vtc: 'FA Sem3 VTC',
  sem5MajorDepartments: 'FA Sem5 Majors',
  sem5AllMinors: 'FA Sem5 Minor Depts',
  sem5Internship: 'FA Sem5 Internship',
  gender: 'FA Gender',
  semester: 'FA Semester',
  admissionStatus: 'FA Admission Status',
} as const;

export const FULL_ADMISSION_STRUCTURE_NOTES = [
  'Full Admission Import — populate 90%+ of the student profile in one upload.',
  "Fill only the subject columns for the student's current semester (Sem 1, 3, or 5).",
  'Sem 1: Major + Minor + MDC + AEC + SEC; VAC is auto-assigned.',
  'Sem 3: Major Department auto-assigns two major papers; no Minor column.',
  'Sem 5: Major Department auto-assigns three major papers + Minor + Internship.',
  'Use department and paper titles from dropdowns — never enter raw course codes.',
  'Minor Department lists all NEP minors — the import validates the major/minor pairing.',
  "Father's Name and Mother's Name are mandatory for new admissions.",
  'Photo File Name is optional — use the Photo Bulk Upload tool if not embedding photos.',
];

export function importFieldByHeader(header: string) {
  return STUDENT_IMPORT_FIELD_REGISTRY.find((f) => f.header === header);
}

export function mandatoryImportFieldKeys() {
  return STUDENT_IMPORT_FIELD_REGISTRY.filter((f) => f.required).map(
    (f) => f.key,
  );
}
