/** Don Bosco College official NEHU FYUGP major → allowed minors matrix. */
export const DBC_MAJOR_MINOR_MATRIX: Record<string, readonly string[]> = {
  Economics: ['Geography', 'History', 'Political Science', 'Sociology'],
  Education: ['Garo', 'History', 'Philosophy'],
  English: ['Education', 'Geography', 'Philosophy', 'Political Science'],
  Garo: ['Education', 'Geography', 'Philosophy', 'Sociology'],
  Geography: ['Economics', 'Garo'],
  History: ['Economics', 'Philosophy', 'Political Science', 'Sociology'],
  Philosophy: ['Education', 'Garo', 'Geography'],
  'Political Science': ['Economics', 'Education', 'History', 'Sociology'],
  Sociology: ['Economics', 'Garo', 'History', 'Political Science'],
  Botany: ['Zoology', 'Chemistry'],
  Chemistry: ['Mathematics', 'Physics'],
  Mathematics: ['Physics', 'Chemistry'],
  Zoology: ['Botany', 'Chemistry'],
  Physics: ['Chemistry', 'Mathematics'],
  Commerce: ['Economics', 'Mathematics', 'Geography'],
};

export const DBC_MAJOR_MINOR_PROGRAMME_GROUP: Record<string, string> = {
  Economics: 'ARTS',
  Education: 'ARTS',
  English: 'ARTS',
  Garo: 'ARTS',
  Geography: 'ARTS',
  History: 'ARTS',
  Philosophy: 'ARTS',
  'Political Science': 'ARTS',
  Sociology: 'ARTS',
  Botany: 'SCIENCE',
  Chemistry: 'SCIENCE',
  Mathematics: 'SCIENCE',
  Zoology: 'SCIENCE',
  Physics: 'SCIENCE',
  Commerce: 'COMMERCE',
};

export const DBC_MAJOR_MINOR_DEPT_CODE: Record<string, string> = {
  Economics: 'ECO',
  Education: 'EDN',
  English: 'ENG',
  Garo: 'GAR',
  Geography: 'GEO',
  History: 'HIS',
  Philosophy: 'PHI',
  'Political Science': 'POL',
  Sociology: 'SOC',
  Botany: 'BOT',
  Chemistry: 'CHE',
  Mathematics: 'MTH',
  Zoology: 'ZOO',
  Physics: 'PHY',
  Commerce: 'COM',
};
