'use client';

import { RefreshCw, UserRound } from 'lucide-react';

import { ErpFormGrid, ErpFormSection } from '@/components/erp/erp-workspace-shell';
import { AdmissionPhotoUpload } from '@/components/students-module/add-student/ui/admission-photo-upload';
import {
  GlassField,
  glassInputClass,
  glassSelectClass,
} from '@/components/students-module/add-student/ui/glass-field';
import type { AddStaffDraft } from '@/components/staff-module/add-staff/types/draft';
import { normalizeEmail } from '@/components/staff-module/add-staff/utils/validation';
import { Button } from '@/components/ui/button';
import { DateInput } from '@/components/ui/date-input';
import { revokePhotoPreviewUrl } from '@/components/students-module/add-student/utils/photo-utils';
import { cn } from '@/utils/cn';

type Props = {
  draft: AddStaffDraft;
  setDraft: React.Dispatch<React.SetStateAction<AddStaffDraft>>;
  errors: Record<string, string>;
  employeeCodePreviewLoading?: boolean;
  onRefreshEmployeeCodePreview?: () => void;
};

export function StepBasic({
  draft,
  setDraft,
  errors,
  employeeCodePreviewLoading,
  onRefreshEmployeeCodePreview,
}: Props) {
  const autoGenerated = draft.employeeCodeAutoGenerated && !draft.employeeCodeFinalized;
  const displayCode = autoGenerated
    ? draft.employeeCodePreview || (employeeCodePreviewLoading ? 'Generating…' : '')
    : draft.employeeCode;

  return (
    <div className="space-y-3">
      <ErpFormSection
        icon={UserRound}
        title="Identity"
        description="Core staff identification details."
      >
        <div className="flex flex-col gap-3 lg:flex-row lg:items-start">
          <ErpFormGrid className="flex-1">
            <GlassField label="Full name" error={errors.fullName} className="md:!col-span-12">
              <input
                className={glassInputClass}
                value={draft.fullName}
                onChange={(e) => setDraft((d) => ({ ...d, fullName: e.target.value }))}
              />
            </GlassField>
            <GlassField
              label="Employee code"
              error={errors.employeeCode}
              hint={
                autoGenerated
                  ? 'Generated automatically from Staff Category.'
                  : 'Manual override — enter a unique employee code.'
              }
              labelAction={
                <label className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
                  <input
                    type="checkbox"
                    className="rounded border-border"
                    checked={autoGenerated}
                    disabled={draft.employeeCodeFinalized}
                    onChange={(e) =>
                      setDraft((d) => ({
                        ...d,
                        employeeCodeAutoGenerated: e.target.checked,
                        employeeCode: e.target.checked ? '' : d.employeeCode,
                        employeeCodePreview: e.target.checked ? d.employeeCodePreview : '',
                      }))
                    }
                  />
                  Auto-generated
                </label>
              }
            >
              <div className="flex w-full gap-2">
                <input
                  className={cn(glassInputClass, autoGenerated && 'bg-muted/40')}
                  value={displayCode}
                  readOnly={autoGenerated}
                  onChange={(e) =>
                    setDraft((d) => ({ ...d, employeeCode: e.target.value.toUpperCase() }))
                  }
                  placeholder={
                    autoGenerated ? 'Waiting for Employment category' : 'Enter employee code'
                  }
                />
                {autoGenerated ? (
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    className="h-11 shrink-0 px-2"
                    disabled={
                      employeeCodePreviewLoading ||
                      !onRefreshEmployeeCodePreview ||
                      draft.employeeCodeFinalized
                    }
                    onClick={onRefreshEmployeeCodePreview}
                    title="Regenerate preview"
                  >
                    <RefreshCw
                      className={cn('h-4 w-4', employeeCodePreviewLoading && 'animate-spin')}
                    />
                  </Button>
                ) : null}
              </div>
            </GlassField>
            <GlassField label="Email" error={errors.email}>
              <input
                type="email"
                className={glassInputClass}
                value={draft.email}
                onChange={(e) => setDraft((d) => ({ ...d, email: e.target.value }))}
                onBlur={(e) => setDraft((d) => ({ ...d, email: normalizeEmail(e.target.value) }))}
              />
            </GlassField>
            <GlassField label="Mobile">
              <input
                className={glassInputClass}
                value={draft.mobile}
                onChange={(e) => setDraft((d) => ({ ...d, mobile: e.target.value }))}
              />
            </GlassField>
            <GlassField label="Gender">
              <select
                className={glassSelectClass}
                value={draft.gender}
                onChange={(e) => setDraft((d) => ({ ...d, gender: e.target.value }))}
              >
                <option value="">Select</option>
                <option value="MALE">Male</option>
                <option value="FEMALE">Female</option>
                <option value="OTHER">Other</option>
              </select>
            </GlassField>
            <GlassField label="Date of birth">
              <DateInput
                value={draft.dateOfBirth}
                onChange={(dateOfBirth) => setDraft((d) => ({ ...d, dateOfBirth }))}
              />
            </GlassField>
            <GlassField label="RFID number" optional>
              <input
                className={glassInputClass}
                value={draft.rfidNo}
                onChange={(e) => setDraft((d) => ({ ...d, rfidNo: e.target.value }))}
              />
            </GlassField>
            <GlassField
              label="Biometric ID"
              error={errors.biometricId}
              optional
              hint="Unique user ID configured inside biometric attendance device."
            >
              <input
                className={glassInputClass}
                value={draft.biometricId}
                maxLength={50}
                onChange={(e) => setDraft((d) => ({ ...d, biometricId: e.target.value }))}
                onBlur={(e) =>
                  setDraft((d) => ({
                    ...d,
                    biometricId: e.target.value.replace(/\s+/g, ' ').trim(),
                  }))
                }
                placeholder="Device user ID"
              />
            </GlassField>
          </ErpFormGrid>
          <AdmissionPhotoUpload
            photoPreviewUrl={draft.photoPreviewUrl}
            onPhotoChange={(dataUrl) =>
              setDraft((d) => {
                if (dataUrl && d.photoPreviewUrl && d.photoPreviewUrl !== dataUrl) {
                  revokePhotoPreviewUrl(d.photoPreviewUrl);
                }
                return { ...d, photoPreviewUrl: dataUrl };
              })
            }
          />
        </div>
      </ErpFormSection>
      <ErpFormSection title="Qualifications" description="Academic and professional background">
        <ErpFormGrid>
          <GlassField label="Qualification">
            <input
              className={glassInputClass}
              value={draft.qualification}
              onChange={(e) => setDraft((d) => ({ ...d, qualification: e.target.value }))}
            />
          </GlassField>
          <GlassField label="Specialization">
            <input
              className={glassInputClass}
              value={draft.specialization}
              onChange={(e) => setDraft((d) => ({ ...d, specialization: e.target.value }))}
            />
          </GlassField>
          <GlassField label="Experience (years)">
            <input
              type="number"
              min={0}
              className={glassInputClass}
              value={draft.experienceYears ?? ''}
              onChange={(e) =>
                setDraft((d) => ({
                  ...d,
                  experienceYears: e.target.value ? Number(e.target.value) : undefined,
                }))
              }
            />
          </GlassField>
        </ErpFormGrid>
      </ErpFormSection>
    </div>
  );
}
