'use client';

import { ErpFormSection } from '@/components/erp/erp-workspace-shell';
import type { AddStaffDraft } from '@/components/staff-module/add-staff/types/draft';
import { staffTypeLabel } from '@/components/staff-module/directory/staff-filter-utils';
import { formatShortDate } from '@/utils/format-date';

type Props = {
  draft: AddStaffDraft;
  departmentLabel?: string;
  designationLabel?: string;
  shiftLabel?: string;
  validationIssues?: string[];
};

export function StepReview({
  draft,
  departmentLabel,
  designationLabel,
  shiftLabel,
  validationIssues = [],
}: Props) {
  const employeeCodeDisplay = draft.employeeCodeAutoGenerated
    ? draft.employeeCodePreview || draft.employeeCode || 'Waiting for Employment category'
    : draft.employeeCode || '—';

  const rows = [
    ['Employee code', employeeCodeDisplay],
    ['Full name', draft.fullName],
    ['Email', draft.email || '—'],
    ['Mobile', draft.mobile || '—'],
    ['Staff type', staffTypeLabel(draft.staffType)],
    ['Employment', staffTypeLabel(draft.employmentType)],
    ['Department', departmentLabel || '—'],
    ['Designation', designationLabel || '—'],
    ['Shift', shiftLabel || '—'],
    ['Joining date', draft.joiningDate ? formatShortDate(draft.joiningDate) : '—'],
    ['Portal account', draft.createPortalAccount ? 'Yes' : 'No'],
    ['Subject assignments', String(draft.subjectAssignments.length)],
    ['Queued documents', String(draft.pendingDocuments.length)],
  ] as const;

  return (
    <div className="space-y-3">
      {validationIssues.length > 0 ? (
        <div className="rounded-xl border border-destructive/40 bg-destructive/5 p-3 text-xs text-destructive">
          <p className="font-medium">Please fix before submitting:</p>
          <ul className="mt-1 list-disc pl-4">
            {validationIssues.map((issue) => (
              <li key={issue}>{issue}</li>
            ))}
          </ul>
        </div>
      ) : null}

      <ErpFormSection title="Review" description="Confirm details before creating staff record">
        <dl className="grid gap-2 sm:grid-cols-2">
          {rows.map(([label, value]) => (
            <div key={label} className="glass-card rounded-lg border border-border/40 px-3 py-2">
              <dt className="text-[10px] text-muted-foreground">{label}</dt>
              <dd className="text-xs font-medium">{value}</dd>
            </div>
          ))}
        </dl>
      </ErpFormSection>
    </div>
  );
}
