export type SeedPermission = {
  slug: string;
  resource: string;
  action: string;
  description: string;
};

export const SEED_PERMISSIONS: SeedPermission[] = [
  {
    slug: 'tenant:read',
    resource: 'tenant',
    action: 'read',
    description: 'View tenant profile',
  },
  {
    slug: 'tenant:manage',
    resource: 'tenant',
    action: 'manage',
    description: 'Manage tenant settings',
  },
  {
    slug: 'users:read',
    resource: 'users',
    action: 'read',
    description: 'List users',
  },
  {
    slug: 'users:manage',
    resource: 'users',
    action: 'manage',
    description: 'Create/update users',
  },
  {
    slug: 'rbac:manage',
    resource: 'rbac',
    action: 'manage',
    description: 'Manage roles and permissions',
  },
  {
    slug: 'org:read',
    resource: 'org',
    action: 'read',
    description: 'View organization structure',
  },
  {
    slug: 'org:manage',
    resource: 'org',
    action: 'manage',
    description: 'Manage campuses and departments',
  },
  {
    slug: 'academic:read',
    resource: 'academic',
    action: 'read',
    description: 'View academic catalog',
  },
  {
    slug: 'academic:manage',
    resource: 'academic',
    action: 'manage',
    description: 'Manage programs and courses',
  },
  {
    slug: 'admissions:read',
    resource: 'admissions',
    action: 'read',
    description: 'View admissions',
  },
  {
    slug: 'admissions:manage',
    resource: 'admissions',
    action: 'manage',
    description: 'Manage admissions workflows',
  },
  {
    slug: 'admissions:configure',
    resource: 'admissions',
    action: 'configure',
    description: 'Configure admission cycles and seat matrix',
  },
  {
    slug: 'admissions:verify-documents',
    resource: 'admissions',
    action: 'verify-documents',
    description: 'Verify applicant documents',
  },
  {
    slug: 'admissions:publish-merit',
    resource: 'admissions',
    action: 'publish-merit',
    description: 'Generate and publish merit lists',
  },
  {
    slug: 'admissions:allocate',
    resource: 'admissions',
    action: 'allocate',
    description: 'Run seat allocation',
  },
  {
    slug: 'admissions:enroll',
    resource: 'admissions',
    action: 'enroll',
    description: 'Enroll selected applicants as students',
  },
  {
    slug: 'admissions:portal:self',
    resource: 'admissions',
    action: 'portal:self',
    description: 'Applicant portal self-service',
  },
  {
    slug: 'students:read',
    resource: 'students',
    action: 'read',
    description: 'View students',
  },
  {
    slug: 'students:manage',
    resource: 'students',
    action: 'manage',
    description: 'Manage students',
  },
  {
    slug: 'students:import',
    resource: 'students',
    action: 'import',
    description: 'Import students in bulk',
  },
  {
    slug: 'students:export',
    resource: 'students',
    action: 'export',
    description: 'Export student profiles',
  },
  {
    slug: 'students:manage-academic',
    resource: 'students',
    action: 'manage-academic',
    description: 'Manage student academic profile and registration',
  },
  {
    slug: 'students:verify-documents',
    resource: 'students',
    action: 'verify-documents',
    description: 'Verify student documents',
  },
  {
    slug: 'students:self-update',
    resource: 'students',
    action: 'self-update',
    description: 'Limited student self profile update',
  },
  {
    slug: 'students:bulk-update',
    resource: 'students',
    action: 'bulk-update',
    description: 'Access student bulk update module',
  },
  {
    slug: 'students:bulk-update:personal',
    resource: 'students',
    action: 'bulk-update:personal',
    description: 'Bulk update personal and family fields',
  },
  {
    slug: 'students:bulk-update:academic',
    resource: 'students',
    action: 'bulk-update:academic',
    description: 'Bulk update academic fields',
  },
  {
    slug: 'students:bulk-update:subjects',
    resource: 'students',
    action: 'bulk-update:subjects',
    description: 'Bulk update NEP subject selections',
  },
  {
    slug: 'students:bulk-update:rollback',
    resource: 'students',
    action: 'bulk-update:rollback',
    description: 'Rollback student bulk update batches',
  },
  {
    slug: 'students:photos:upload',
    resource: 'students',
    action: 'photos:upload',
    description: 'Upload student photos in bulk',
  },
  {
    slug: 'students:photos:replace',
    resource: 'students',
    action: 'photos:replace',
    description: 'Replace existing student photos in bulk',
  },
  {
    slug: 'students:photos:delete',
    resource: 'students',
    action: 'photos:delete',
    description: 'Delete student photos in bulk',
  },
  {
    slug: 'students:photos:reports',
    resource: 'students',
    action: 'photos:reports',
    description: 'Download student photo upload reports',
  },
  {
    slug: 'academic-engine:read',
    resource: 'academic-engine',
    action: 'read',
    description: 'View academic engine',
  },
  {
    slug: 'academic-engine:manage',
    resource: 'academic-engine',
    action: 'manage',
    description: 'Manage academic engine',
  },
  {
    slug: 'academic-lifecycle:read',
    resource: 'academic-lifecycle',
    action: 'read',
    description: 'View academic lifecycle and promotion',
  },
  {
    slug: 'academic-lifecycle:manage',
    resource: 'academic-lifecycle',
    action: 'manage',
    description: 'Manage semester lifecycle and promotion',
  },
  {
    slug: 'fees:read',
    resource: 'fees',
    action: 'read',
    description: 'View fees',
  },
  {
    slug: 'fees:manage',
    resource: 'fees',
    action: 'manage',
    description: 'Manage fee structures and payments',
  },
  {
    slug: 'fees:cash:collect',
    resource: 'fees',
    action: 'cash:collect',
    description: 'Collect cash fee payments at the desk',
  },
  {
    slug: 'reports:read',
    resource: 'reports',
    action: 'read',
    description: 'View reports',
  },
  {
    slug: 'communication:read',
    resource: 'communication',
    action: 'read',
    description: 'View communication hub and history',
  },
  {
    slug: 'communication:manage',
    resource: 'communication',
    action: 'manage',
    description: 'Manage templates, campaigns, and send messages',
  },
  {
    slug: 'mobile:settings:read',
    resource: 'mobile',
    action: 'settings:read',
    description: 'View mobile app control settings',
  },
  {
    slug: 'mobile:settings:manage',
    resource: 'mobile',
    action: 'settings:manage',
    description: 'Manage mobile app control settings',
  },
  {
    slug: 'notifications:read',
    resource: 'notifications',
    action: 'read',
    description: 'View in-app notifications',
  },
  {
    slug: 'certificates:read',
    resource: 'certificates',
    action: 'read',
    description: 'View certificate templates, requests, and issues',
  },
  {
    slug: 'certificates:manage',
    resource: 'certificates',
    action: 'manage',
    description: 'Manage templates, issue, revoke, and configure certificates',
  },
  {
    slug: 'certificates:approve',
    resource: 'certificates',
    action: 'approve',
    description: 'Approve certificate workflow steps',
  },
  {
    slug: 'certificates:self',
    resource: 'certificates',
    action: 'self',
    description: 'Student self-service certificate requests and downloads',
  },
  {
    slug: 'obe:read',
    resource: 'obe',
    action: 'read',
    description: 'View OBE mappings',
  },
  {
    slug: 'obe:manage',
    resource: 'obe',
    action: 'manage',
    description: 'Manage OBE and attainment',
  },
  {
    slug: 'abc:read',
    resource: 'abc',
    action: 'read',
    description: 'View ABC credits',
  },
  {
    slug: 'abc:manage',
    resource: 'abc',
    action: 'manage',
    description: 'Manage ABC transfers',
  },
  {
    slug: 'shift:read',
    resource: 'shift',
    action: 'read',
    description: 'View shifts',
  },
  {
    slug: 'shift:manage',
    resource: 'shift',
    action: 'manage',
    description: 'Manage shifts',
  },
  {
    slug: 'shift:students:read',
    resource: 'shift',
    action: 'students:read',
    description: 'View shift students',
  },
  {
    slug: 'shift:students:manage',
    resource: 'shift',
    action: 'students:manage',
    description: 'Manage shift students',
  },
  {
    slug: 'shift:timetable:manage',
    resource: 'shift',
    action: 'timetable:manage',
    description: 'Manage shift timetables',
  },
  {
    slug: 'academic:timetable:manage',
    resource: 'academic',
    action: 'timetable:manage',
    description: 'Manage academic timetables',
  },
  {
    slug: 'shift:attendance:manage',
    resource: 'shift',
    action: 'attendance:manage',
    description: 'Manage shift attendance',
  },
  {
    slug: 'shift:exams:manage',
    resource: 'shift',
    action: 'exams:manage',
    description: 'Manage shift examinations',
  },
  {
    slug: 'shift:reports:read',
    resource: 'shift',
    action: 'reports:read',
    description: 'View shift reports',
  },
  {
    slug: 'audit:read',
    resource: 'audit',
    action: 'read',
    description: 'View platform audit logs',
  },
  {
    slug: 'sessions:manage',
    resource: 'sessions',
    action: 'manage',
    description: 'Manage user sessions',
  },
  {
    slug: 'lookups:read',
    resource: 'lookups',
    action: 'read',
    description: 'View master lookups',
  },
  {
    slug: 'lookups:manage',
    resource: 'lookups',
    action: 'manage',
    description: 'Manage master lookups',
  },
  {
    slug: 'imports:manage',
    resource: 'imports',
    action: 'manage',
    description: 'Manage import/export center',
  },
  {
    slug: 'users:impersonate',
    resource: 'users',
    action: 'impersonate',
    description: 'Login as another user',
  },
  {
    slug: 'staff:read',
    resource: 'staff',
    action: 'read',
    description: 'View staff directory and profiles',
  },
  {
    slug: 'staff:manage',
    resource: 'staff',
    action: 'manage',
    description: 'Create and update staff records',
  },
  {
    slug: 'staff:assign-subjects',
    resource: 'staff',
    action: 'assign-subjects',
    description: 'Assign teaching subjects and sections',
  },
  {
    slug: 'staff:portal',
    resource: 'staff',
    action: 'portal',
    description: 'Manage staff portal accounts',
  },
  {
    slug: 'staff:export',
    resource: 'staff',
    action: 'export',
    description: 'Export staff data',
  },
  {
    slug: 'staff:import',
    resource: 'staff',
    action: 'import',
    description: 'Import staff in bulk',
  },
  {
    slug: 'staff:bulk-update',
    resource: 'staff',
    action: 'bulk-update',
    description: 'Access staff bulk update module',
  },
  {
    slug: 'staff:bulk-update:rollback',
    resource: 'staff',
    action: 'bulk-update:rollback',
    description: 'Rollback staff bulk update batches',
  },
  {
    slug: 'hr:appointment:read',
    resource: 'hr-appointment',
    action: 'read',
    description: 'View appointment orders and probation lists',
  },
  {
    slug: 'hr:appointment:manage',
    resource: 'hr-appointment',
    action: 'manage',
    description: 'Create and manage appointment orders',
  },
  {
    slug: 'hr:appointment:issue',
    resource: 'hr-appointment',
    action: 'issue',
    description: 'Generate and issue appointment order PDFs',
  },
  {
    slug: 'hr:joining:verify',
    resource: 'hr-joining',
    action: 'verify',
    description: 'Verify joining reports and activate staff',
  },
  {
    slug: 'staff-attendance:view',
    resource: 'staff-attendance',
    action: 'view',
    description: 'View staff attendance dashboards and registers',
  },
  {
    slug: 'staff-attendance:edit',
    resource: 'staff-attendance',
    action: 'edit',
    description: 'Edit staff attendance records and settings',
  },
  {
    slug: 'staff-attendance:reports',
    resource: 'staff-attendance',
    action: 'reports',
    description: 'Export staff attendance reports',
  },
  {
    slug: 'staff-attendance:corrections:approve',
    resource: 'staff-attendance',
    action: 'corrections:approve',
    description: 'Approve staff attendance corrections',
  },
  {
    slug: 'staff-attendance:corrections:hod',
    resource: 'staff-attendance',
    action: 'corrections:hod',
    description: 'HOD approval for staff attendance corrections',
  },
  {
    slug: 'staff-attendance:settings:view',
    resource: 'staff-attendance',
    action: 'settings:view',
    description: 'View staff attendance policy configuration',
  },
  {
    slug: 'staff-attendance:settings:edit',
    resource: 'staff-attendance',
    action: 'settings:edit',
    description: 'Edit staff attendance policy configuration',
  },
  {
    slug: 'staff-attendance:shift-admin',
    resource: 'staff-attendance',
    action: 'shift-admin',
    description:
      'Manage staff attendance shifts, groups, rosters, and assignments',
  },
  {
    slug: 'staff-attendance:leave-admin',
    resource: 'staff-attendance',
    action: 'leave-admin',
    description:
      'Manage staff attendance leave types and leave integration settings',
  },
  {
    slug: 'staff-attendance:reprocess',
    resource: 'staff-attendance',
    action: 'reprocess',
    description: 'Run attendance recalculation and reprocessing jobs',
  },
  {
    slug: 'staff-biometric:admin',
    resource: 'staff-biometric',
    action: 'admin',
    description: 'Administer staff biometric mappings and sync',
  },
  {
    slug: 'staff-biometric:device-admin',
    resource: 'staff-biometric',
    action: 'device-admin',
    description: 'Manage biometric devices and dangerous device operations',
  },
  {
    slug: 'staff-biometric:sync',
    resource: 'staff-biometric',
    action: 'sync',
    description: 'Run biometric device sync jobs',
  },
  {
    slug: 'staff:portal:self',
    resource: 'staff',
    action: 'portal:self',
    description: 'Access own staff portal profile and dashboard',
  },
  {
    slug: 'student:portal:self',
    resource: 'student',
    action: 'portal:self',
    description: 'Access own student portal profile and dashboard',
  },
  {
    slug: 'lms:read',
    resource: 'lms',
    action: 'read',
    description: 'View LMS workspaces and content',
  },
  {
    slug: 'lms:manage',
    resource: 'lms',
    action: 'manage',
    description: 'Manage LMS administration',
  },
  {
    slug: 'lms:workspace:manage',
    resource: 'lms',
    action: 'workspace:manage',
    description: 'Manage LMS workspaces',
  },
  {
    slug: 'lms:materials:upload',
    resource: 'lms',
    action: 'materials:upload',
    description: 'Upload LMS materials',
  },
  {
    slug: 'lms:materials:publish',
    resource: 'lms',
    action: 'materials:publish',
    description: 'Publish LMS materials',
  },
  {
    slug: 'lms:announcements:publish',
    resource: 'lms',
    action: 'announcements:publish',
    description: 'Publish LMS announcements',
  },
  {
    slug: 'lms:lesson-plans:manage',
    resource: 'lms',
    action: 'lesson-plans:manage',
    description: 'Manage LMS lesson plans',
  },
  {
    slug: 'lms:assignments:manage',
    resource: 'lms',
    action: 'assignments:manage',
    description: 'Manage and evaluate LMS assignments',
  },
  {
    slug: 'lms:analytics:read',
    resource: 'lms',
    action: 'analytics:read',
    description: 'View LMS analytics',
  },
  {
    slug: 'lms:settings:manage',
    resource: 'lms',
    action: 'settings:manage',
    description: 'Manage LMS settings',
  },
  {
    slug: 'question-bank:read',
    resource: 'question-bank',
    action: 'read',
    description: 'View question bank papers and dashboard',
  },
  {
    slug: 'question-bank:download',
    resource: 'question-bank',
    action: 'download',
    description: 'Download and preview published papers',
  },
  {
    slug: 'question-bank:contribute',
    resource: 'question-bank',
    action: 'contribute',
    description: 'Upload and submit question papers',
  },
  {
    slug: 'question-bank:approve',
    resource: 'question-bank',
    action: 'approve',
    description: 'Approve question paper workflow steps',
  },
  {
    slug: 'question-bank:publish',
    resource: 'question-bank',
    action: 'publish',
    description: 'Publish approved question papers',
  },
  {
    slug: 'question-bank:manage',
    resource: 'question-bank',
    action: 'manage',
    description: 'Full question bank administration and bulk import',
  },
  {
    slug: 'question-bank:reports',
    resource: 'question-bank',
    action: 'reports',
    description: 'View question bank reports and exports',
  },
  {
    slug: 'exam:view',
    resource: 'exam',
    action: 'view',
    description: 'View examination sessions and papers',
  },
  {
    slug: 'exam:create',
    resource: 'exam',
    action: 'create',
    description: 'Create examination sessions',
  },
  {
    slug: 'exam:edit',
    resource: 'exam',
    action: 'edit',
    description: 'Edit examination sessions',
  },
  {
    slug: 'exam:delete',
    resource: 'exam',
    action: 'delete',
    description: 'Archive examination sessions',
  },
  {
    slug: 'exam:admin',
    resource: 'exam',
    action: 'admin',
    description: 'Full examination administration',
  },
  {
    slug: 'exam:results',
    resource: 'exam',
    action: 'results',
    description: 'Calculate and publish examination results',
  },
  {
    slug: 'exam:marks',
    resource: 'exam',
    action: 'marks',
    description: 'Enter examination marks',
  },
  {
    slug: 'exam:allocate',
    resource: 'exam',
    action: 'allocate',
    description: 'Allocate exam rooms and seating',
  },
  {
    slug: 'exam:invigilate',
    resource: 'exam',
    action: 'invigilate',
    description: 'Assign exam invigilators',
  },
  {
    slug: 'exam:reports',
    resource: 'exam',
    action: 'reports',
    description: 'Examination reports and exports',
  },
  {
    slug: 'ia:view',
    resource: 'ia',
    action: 'view',
    description: 'View internal assessment module',
  },
  {
    slug: 'ia:manage',
    resource: 'ia',
    action: 'manage',
    description: 'Manage IA schemes, sessions, and consolidation',
  },
  {
    slug: 'ia:marks:enter',
    resource: 'ia',
    action: 'marks-enter',
    description: 'Enter internal assessment marks',
  },
  {
    slug: 'ia:marks:approve:hod',
    resource: 'ia',
    action: 'approve-hod',
    description: 'HOD approval for IA mark sheets',
  },
  {
    slug: 'ia:marks:approve:controller',
    resource: 'ia',
    action: 'approve-controller',
    description: 'Exam controller verification for IA marks',
  },
  {
    slug: 'ia:marks:approve:principal',
    resource: 'ia',
    action: 'approve-principal',
    description: 'Principal approval for IA mark sheets',
  },
  {
    slug: 'ia:export:nehu',
    resource: 'ia',
    action: 'export-nehu',
    description: 'Export NEHU IA submission reports',
  },
  {
    slug: 'ia:legacy:admin',
    resource: 'ia',
    action: 'legacy-admin',
    description: 'Access legacy university examination mode',
  },
  {
    slug: 'library:access-desk',
    resource: 'library',
    action: 'access-desk',
    description: 'Library access desk kiosk scan and entry/exit',
  },
  {
    slug: 'principal-desk:access',
    resource: 'principal-desk',
    action: 'access',
    description: 'Principal command center dashboard and instant lookup',
  },
  {
    slug: 'cams:read',
    resource: 'cams',
    action: 'read',
    description: 'View campus access points and live occupancy',
  },
  {
    slug: 'cams:manage',
    resource: 'cams',
    action: 'manage',
    description: 'Configure access points and kiosk devices',
  },
  {
    slug: 'cams:reports',
    resource: 'cams',
    action: 'reports',
    description: 'Campus access analytics and NAAC footfall reports',
  },
  {
    slug: 'library:read',
    resource: 'library',
    action: 'read',
    description: 'View library visits, catalogue, and own loans',
  },
  {
    slug: 'library:manage',
    resource: 'library',
    action: 'manage',
    description: 'Manage library catalogue and administration',
  },
  {
    slug: 'library:circulate',
    resource: 'library',
    action: 'circulate',
    description: 'Issue and return library books',
  },
  {
    slug: 'library:reports',
    resource: 'library',
    action: 'reports',
    description: 'View library reports and analytics',
  },
  {
    slug: 'library:settings',
    resource: 'library',
    action: 'settings',
    description: 'Configure library settings and fines',
  },
  {
    slug: 'library:digital:read',
    resource: 'library',
    action: 'digital:read',
    description: 'Browse digital library catalogue',
  },
  {
    slug: 'library:digital:download',
    resource: 'library',
    action: 'digital:download',
    description: 'Download digital library resources',
  },
  {
    slug: 'library:digital:manage',
    resource: 'library',
    action: 'digital:manage',
    description: 'Upload and manage digital library assets',
  },
  {
    slug: 'library:research:read',
    resource: 'library',
    action: 'research:read',
    description: 'Browse research repository',
  },
  {
    slug: 'library:research:submit',
    resource: 'library',
    action: 'research:submit',
    description: 'Submit research repository items',
  },
  {
    slug: 'library:research:manage',
    resource: 'library',
    action: 'research:manage',
    description: 'Approve and manage research repository',
  },
  {
    slug: 'front-office:read',
    resource: 'front-office',
    action: 'read',
    description: 'View front office enquiries, gate passes, and complaints',
  },
  {
    slug: 'front-office:desk',
    resource: 'front-office',
    action: 'desk',
    description: 'Register enquiries, issue gate passes, log complaints',
  },
  {
    slug: 'front-office:manage',
    resource: 'front-office',
    action: 'manage',
    description: 'Manage and resolve front office records',
  },
  {
    slug: 'front-office:reports',
    resource: 'front-office',
    action: 'reports',
    description: 'View front office reports',
  },
  {
    slug: 'governance:read',
    resource: 'governance',
    action: 'read',
    description: 'View committees, meetings, and governance records',
  },
  {
    slug: 'governance:manage',
    resource: 'governance',
    action: 'manage',
    description: 'Manage committees, meetings, ATR, and tasks',
  },
  {
    slug: 'governance:publish',
    resource: 'governance',
    action: 'publish',
    description: 'Publish notices, minutes, and circulars',
  },
  {
    slug: 'governance:reports',
    resource: 'governance',
    action: 'reports',
    description: 'Export governance and NAAC reports',
  },
  {
    slug: 'governance:import',
    resource: 'governance',
    action: 'import',
    description: 'Import committees from PDF',
  },
  {
    slug: 'governance:portal',
    resource: 'governance',
    action: 'portal',
    description: 'Staff committee member self-service portal',
  },
  {
    slug: 'naac-iqac:read',
    resource: 'naac-iqac',
    action: 'read',
    description: 'View NAAC & IQAC workspace, criteria, and evidence',
  },
  {
    slug: 'naac-iqac:manage',
    resource: 'naac-iqac',
    action: 'manage',
    description: 'Manage AQAR, vault, MoUs, and IQAC workflows',
  },
  {
    slug: 'naac-iqac:collect',
    resource: 'naac-iqac',
    action: 'collect',
    description: 'Submit department-wise NAAC data and achievements',
  },
  {
    slug: 'naac-iqac:publish',
    resource: 'naac-iqac',
    action: 'publish',
    description: 'Publish finalized NAAC reports and circulars',
  },
  {
    slug: 'naac-iqac:reports',
    resource: 'naac-iqac',
    action: 'reports',
    description: 'Export NAAC evidence packs and DVV reports',
  },
  {
    slug: 'naac-iqac:portal',
    resource: 'naac-iqac',
    action: 'portal',
    description: 'Staff IQAC and department coordinator self-service',
  },
  {
    slug: 'transport:read',
    resource: 'transport',
    action: 'read',
    description: 'View transport routes, vehicles, and assignments',
  },
  {
    slug: 'transport:manage',
    resource: 'transport',
    action: 'manage',
    description: 'Manage transport routes and vehicles',
  },
  {
    slug: 'transport:assign',
    resource: 'transport',
    action: 'assign',
    description: 'Assign students to transport routes',
  },
  {
    slug: 'inventory:read',
    resource: 'inventory',
    action: 'read',
    description: 'View inventory stores, items, and transactions',
  },
  {
    slug: 'inventory:manage',
    resource: 'inventory',
    action: 'manage',
    description: 'Manage stores, items, and stock receipts',
  },
  {
    slug: 'inventory:issue',
    resource: 'inventory',
    action: 'issue',
    description: 'Issue and return stock to departments',
  },
  {
    slug: 'payroll:read',
    resource: 'payroll',
    action: 'read',
    description: 'View payroll dashboard, structures, and payslips',
  },
  {
    slug: 'payroll:manage',
    resource: 'payroll',
    action: 'manage',
    description: 'Manage salary components, structures, assignments, loans',
  },
  {
    slug: 'payroll:process',
    resource: 'payroll',
    action: 'process',
    description: 'Create and calculate payroll runs',
  },
  {
    slug: 'payroll:verify',
    resource: 'payroll',
    action: 'verify',
    description: 'Verify payroll runs',
  },
  {
    slug: 'payroll:approve',
    resource: 'payroll',
    action: 'approve',
    description: 'Approve payroll runs',
  },
  {
    slug: 'payroll:publish',
    resource: 'payroll',
    action: 'publish',
    description: 'Publish payroll runs',
  },
  {
    slug: 'payroll:reports',
    resource: 'payroll',
    action: 'reports',
    description: 'View and export payroll reports',
  },
  {
    slug: 'payroll:portal:self',
    resource: 'payroll',
    action: 'portal:self',
    description: 'View own payslips, loans, and PF summary',
  },
  {
    slug: 'accommodation:read',
    resource: 'accommodation',
    action: 'read',
    description: 'View staff quarters and accommodation',
  },
  {
    slug: 'accommodation:manage',
    resource: 'accommodation',
    action: 'manage',
    description: 'Manage quarters, allotments, and charges',
  },
  {
    slug: 'accommodation:reports',
    resource: 'accommodation',
    action: 'reports',
    description: 'Export accommodation reports',
  },
  {
    slug: 'license:read',
    resource: 'license',
    action: 'read',
    description: 'View institution license status',
  },
  {
    slug: 'license:activate',
    resource: 'license',
    action: 'activate',
    description: 'Activate or renew license with a key',
  },
  {
    slug: 'platform:licenses:read',
    resource: 'platform',
    action: 'licenses:read',
    description: 'View all tenant licenses',
  },
  {
    slug: 'platform:licenses:manage',
    resource: 'platform',
    action: 'licenses:manage',
    description: 'Manage tenant licenses',
  },
  {
    slug: 'backup:read',
    resource: 'backup',
    action: 'read',
    description: 'View backup dashboard, repository, and logs',
  },
  {
    slug: 'backup:manage',
    resource: 'backup',
    action: 'manage',
    description: 'Configure schedules, run manual backups, cloud settings',
  },
  {
    slug: 'backup:download',
    resource: 'backup',
    action: 'download',
    description: 'Download backup artifacts (super-admin)',
  },
  {
    slug: 'backup:restore',
    resource: 'backup',
    action: 'restore',
    description: 'Restore from backup (super-admin)',
  },
  {
    slug: 'official-documents:read',
    resource: 'official-documents',
    action: 'read',
    description: 'View official documents, archive, and dashboard',
  },
  {
    slug: 'official-documents:manage',
    resource: 'official-documents',
    action: 'manage',
    description: 'Create and edit official document drafts',
  },
  {
    slug: 'official-documents:approve',
    resource: 'official-documents',
    action: 'approve',
    description: 'Approve or reject official documents (Principal)',
  },
  {
    slug: 'official-documents:publish',
    resource: 'official-documents',
    action: 'publish',
    description: 'Publish approved official documents',
  },
  {
    slug: 'official-documents:archive',
    resource: 'official-documents',
    action: 'archive',
    description: 'Archive official documents',
  },
  {
    slug: 'official-documents:settings',
    resource: 'official-documents',
    action: 'settings',
    description:
      'Manage letterheads, issuers, templates, and reference formats',
  },
];
