import { Injectable, Logger } from '@nestjs/common';
import { randomBytes } from 'crypto';
import { PrismaService } from '../../../database/prisma.service';
import type { JwtUser } from '../../../common/decorators/current-user.decorator';
import { StaffPayAssignmentService } from './staff-pay-assignment.service';

@Injectable()
export class SubstitutePayrollBridgeService {
  private readonly logger = new Logger(SubstitutePayrollBridgeService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly payAssignments: StaffPayAssignmentService,
  ) {}

  /** Original faculty excluded when college pays the substitute for this payroll month. */
  async collegePaidOriginalStaffIds(
    tenantId: string,
    month: number,
    year: number,
  ): Promise<Set<string>> {
    const periodStart = new Date(year, month - 1, 1);
    const periodEnd = new Date(year, month, 0);
    const rows = await this.prisma.replacementAssignment.findMany({
      where: {
        tenantId,
        status: 'ACTIVE',
        salaryArrangement: 'COLLEGE_PAYS_SUBSTITUTE',
        startDate: { lte: periodEnd },
        endDate: { gte: periodStart },
      },
      select: { originalStaffProfileId: true },
    });
    return new Set(rows.map((row) => row.originalStaffProfileId));
  }

  /** College-paid substitute assignments overlapping the payroll month. */
  async collegePaidAssignmentsForMonth(
    tenantId: string,
    month: number,
    year: number,
  ) {
    const periodStart = new Date(year, month - 1, 1);
    const periodEnd = new Date(year, month, 0);
    return this.prisma.replacementAssignment.findMany({
      where: {
        tenantId,
        status: 'ACTIVE',
        salaryArrangement: 'COLLEGE_PAYS_SUBSTITUTE',
        startDate: { lte: periodEnd },
        endDate: { gte: periodStart },
        monthlyAgreedAmount: { gt: 0 },
      },
      include: {
        substitute: {
          include: {
            department: { select: { id: true, name: true } },
            linkedStaffProfile: {
              select: { id: true, employeeCode: true, fullName: true },
            },
          },
        },
        originalStaff: {
          select: {
            id: true,
            fullName: true,
            employeeCode: true,
            departmentId: true,
          },
        },
        department: { select: { id: true, name: true } },
      },
    });
  }

  /**
   * Ensure substitute has a linked GUEST staff profile + active pay assignment
   * so payroll can generate a payslip for college-paid replacements.
   */
  async ensureGuestPayrollProfile(
    user: JwtUser,
    assignment: Awaited<
      ReturnType<
        SubstitutePayrollBridgeService['collegePaidAssignmentsForMonth']
      >
    >[number],
  ): Promise<string> {
    const substitute = assignment.substitute;
    const monthlyAmount = Number(assignment.monthlyAgreedAmount ?? 0);
    if (monthlyAmount <= 0) {
      throw new Error(
        `Replacement assignment ${assignment.id} has no monthly agreed amount`,
      );
    }

    let staffProfileId = substitute.linkedStaffProfileId ?? undefined;

    if (!staffProfileId) {
      const existingByCode = await this.prisma.staffProfile.findFirst({
        where: {
          tenantId: user.tid,
          employeeCode: substitute.substituteCode,
          deletedAt: null,
        },
        select: { id: true },
      });
      staffProfileId = existingByCode?.id;
    }

    if (!staffProfileId) {
      const guestStructure = await this.prisma.payStructureTemplate.findFirst({
        where: { tenantId: user.tid, code: 'GUEST_FACULTY', status: 'ACTIVE' },
        select: { id: true },
      });

      const created = await this.prisma.staffProfile.create({
        data: {
          tenantId: user.tid,
          employeeCode: substitute.substituteCode,
          employeeCodeAutoGenerated: false,
          fullName: substitute.fullName,
          email: substitute.email?.trim().toLowerCase(),
          mobile: substitute.mobile,
          staffType: 'GUEST',
          employmentType: 'GUEST',
          departmentId: assignment.departmentId ?? substitute.departmentId,
          qualification: substitute.qualification,
          specialization: substitute.specialization,
          joiningDate: assignment.startDate,
          basicPay: monthlyAmount,
          status: 'ACTIVE',
        },
      });
      staffProfileId = created.id;

      await this.prisma.substituteStaff.update({
        where: { id: substitute.id },
        data: { linkedStaffProfileId: staffProfileId },
      });

      if (guestStructure) {
        await this.payAssignments.create(user, {
          staffProfileId,
          payStructureTemplateId: guestStructure.id,
          payScaleType: 'GUEST',
          basicPay: monthlyAmount,
          effectiveFrom: assignment.startDate.toISOString().slice(0, 10),
          notes: `Replacement faculty payroll — covering ${assignment.originalStaff.fullName} (${assignment.assignmentCode ?? assignment.id})`,
        });
      }
    } else {
      await this.prisma.substituteStaff.update({
        where: { id: substitute.id },
        data: { linkedStaffProfileId: staffProfileId },
      });

      const activeAssignment = await this.prisma.staffPayAssignment.findFirst({
        where: { tenantId: user.tid, staffProfileId, status: 'ACTIVE' },
      });
      if (!activeAssignment) {
        const guestStructure = await this.prisma.payStructureTemplate.findFirst(
          {
            where: {
              tenantId: user.tid,
              code: 'GUEST_FACULTY',
              status: 'ACTIVE',
            },
            select: { id: true },
          },
        );
        if (guestStructure) {
          await this.payAssignments.create(user, {
            staffProfileId,
            payStructureTemplateId: guestStructure.id,
            payScaleType: 'GUEST',
            basicPay: monthlyAmount,
            effectiveFrom: assignment.startDate.toISOString().slice(0, 10),
            notes: `Replacement faculty payroll — ${assignment.assignmentCode ?? assignment.id}`,
          });
        }
      } else if (Number(activeAssignment.basicPay) !== monthlyAmount) {
        await this.prisma.staffPayAssignment.update({
          where: { id: activeAssignment.id },
          data: { basicPay: monthlyAmount },
        });
        await this.prisma.staffProfile.update({
          where: { id: staffProfileId },
          data: { basicPay: monthlyAmount },
        });
      }
    }

    return staffProfileId;
  }

  /** Simplified payslip for college-paid substitute (fixed monthly agreed amount). */
  async createSubstitutePayslip(
    user: JwtUser,
    runId: string,
    month: number,
    year: number,
    staffProfileId: string,
    assignment: Awaited<
      ReturnType<
        SubstitutePayrollBridgeService['collegePaidAssignmentsForMonth']
      >
    >[number],
  ) {
    const amount = Number(assignment.monthlyAgreedAmount ?? 0);
    const existing = await this.prisma.payslip.findFirst({
      where: { payrollRunId: runId, staffProfileId },
    });
    if (existing) return existing;

    const payslip = await this.prisma.payslip.create({
      data: {
        tenantId: user.tid,
        payrollRunId: runId,
        staffProfileId,
        payScaleType: 'GUEST',
        month,
        year,
        grossSalary: amount,
        totalDeductions: 0,
        netSalary: amount,
        verifyToken: randomBytes(16).toString('hex'),
        status: 'DRAFT',
        attendanceSummary: {
          payslipKind: 'SUBSTITUTE_REPLACEMENT',
          replacementAssignmentId: assignment.id,
          substituteStaffId: assignment.substituteStaffId,
          originalStaffProfileId: assignment.originalStaffProfileId,
          originalStaffName: assignment.originalStaff.fullName,
          salaryArrangement: assignment.salaryArrangement,
        },
      },
    });

    await this.prisma.payslipLine.createMany({
      data: [
        {
          tenantId: user.tid,
          payslipId: payslip.id,
          componentCode: 'BASIC',
          componentName: 'Replacement Faculty Honorarium',
          componentType: 'EARNING',
          amount,
          sortOrder: 10,
        },
      ],
    });

    return payslip;
  }

  async appendCollegePaidSubstitutePayslips(
    user: JwtUser,
    runId: string,
    month: number,
    year: number,
  ) {
    const assignments = await this.collegePaidAssignmentsForMonth(
      user.tid,
      month,
      year,
    );
    let created = 0;
    for (const assignment of assignments) {
      try {
        const staffProfileId = await this.ensureGuestPayrollProfile(
          user,
          assignment,
        );
        await this.createSubstitutePayslip(
          user,
          runId,
          month,
          year,
          staffProfileId,
          assignment,
        );
        created += 1;
      } catch (err) {
        this.logger.warn(
          `Substitute payslip skipped for assignment ${assignment.id}: ${err instanceof Error ? err.message : err}`,
        );
      }
    }
    return created;
  }
}
