/** Bundled products and testimonials published on basecodelabs.com. */

export const CATALOG_PRODUCTS = [
  {
    name: 'BCL OneCampus ERP',
    slug: 'bcl-onecampus-erp',
    code: 'ONC',
    version: '2.0',
    category: 'ERP',
    platform: 'Web + Android + iOS',
    pricingModel: 'Per institution / per student',
    licenseType: 'Annual',
    supportPlan: null as string | null,
    description:
      'Complete institution management platform for schools and colleges — students, staff, admissions, academics, attendance, fees, examinations, library, accounts, HR, SMS, portals and mobile apps.',
    featuresJson: JSON.stringify([
      'Student Management',
      'Staff Management',
      'Admissions',
      'Academics',
      'Attendance',
      'Fees',
      'Examination',
      'Library',
      'Accounts',
      'HR',
      'SMS',
      'Notifications',
      'Certificates',
      'Reports',
      'Parent Portal',
      'Student Portal',
      'Staff Portal',
      'Mobile Applications',
    ]),
    status: 'PUBLISHED',
    displayOrder: 1,
  },
  {
    name: 'Web Solutions',
    slug: 'web-solutions',
    code: 'WEB',
    version: '1.0',
    category: 'Website',
    platform: 'Web',
    pricingModel: null as string | null,
    licenseType: null as string | null,
    supportPlan: null as string | null,
    description:
      'Corporate, school and college websites plus web applications — designed, hosted and maintained for institutions that need a lasting digital presence.',
    featuresJson: JSON.stringify([
      'Corporate websites',
      'School websites',
      'College websites',
      'E-commerce',
      'Web applications',
    ]),
    status: 'PUBLISHED',
    displayOrder: 2,
  },
  {
    name: 'Mobile Applications',
    slug: 'mobile-applications',
    code: 'MOB',
    version: '1.0',
    category: 'Mobile App',
    platform: 'Android + iOS',
    pricingModel: null as string | null,
    licenseType: null as string | null,
    supportPlan: null as string | null,
    description:
      'Android, iOS and cross-platform applications for campuses, dioceses and businesses — including parent and staff apps connected to BCL products.',
    featuresJson: JSON.stringify([
      'Android',
      'iOS',
      'Cross-platform',
      'Push notifications',
      'Store publishing',
    ]),
    status: 'PUBLISHED',
    displayOrder: 3,
  },
  {
    name: 'BCL GST Billing',
    slug: 'gst-billing',
    code: 'GST',
    version: '1.0',
    category: 'Business Software',
    platform: 'Web (SaaS)',
    pricingModel: 'Subscription',
    licenseType: 'SaaS',
    supportPlan: 'Email and phone',
    description:
      'A simple and powerful GST billing and business management solution for small businesses, shops, service providers and growing enterprises. Create professional GST invoices, manage customers and products, track payments, and generate useful business reports from one place.',
    featuresJson: JSON.stringify([
      'GST-compliant invoice generation',
      'Customer management',
      'Product & service management',
      'HSN/SAC codes',
      'GST rates and tax calculations',
      'CGST / SGST / IGST',
      'Invoice numbering',
      'Quotations & estimates',
      'Purchase management',
      'Sales management',
      'Payment tracking',
      'Outstanding / receivables',
      'Credit & debit notes',
      'Stock / inventory management',
      'Expense tracking',
      'GST reports',
      'Sales reports',
      'Customer statements',
      'Printable & PDF invoices',
      'Business dashboard',
      'User roles & permissions',
      'Backup & data security',
    ]),
    status: 'PUBLISHED',
    displayOrder: 4,
  },
  {
    name: 'Business Solutions',
    slug: 'custom-software',
    code: 'CUS',
    version: '1.0',
    category: 'Custom Software',
    platform: 'Custom',
    pricingModel: null as string | null,
    licenseType: null as string | null,
    supportPlan: null as string | null,
    description:
      'SaaS, CRM, APIs and purpose-built software for organisations that need more than a template product.',
    featuresJson: JSON.stringify(['SaaS', 'CRM', 'APIs', 'Integrations']),
    status: 'PUBLISHED',
    displayOrder: 5,
  },
];

export const CATALOG_TESTIMONIALS = [
  {
    name: 'Fr. Bivan Rodriques Mukhim',
    designation: 'Vice Provincial',
    organisation: 'Salesian Province of Guwahati',
    quote:
      'BaseCode Labs has redesigned the website of the Salesian Province of Guwahati and developed a dedicated mobile application for the platform. The new website features improved functionality, a well-structured design, and a user-friendly interface that enhances accessibility and navigation. The team demonstrated professionalism, technical expertise, and responsive communication throughout the project. I am very pleased with their work and dedication. Kudos to the team at BaseCode Labs for their excellent service.',
    photo: '/images/testimonials/fr-bivan-salesian.png',
    project: 'Province website and mobile app',
    industry: 'Diocese / Religious',
    website: 'https://donboscoguwahati.org/',
    rating: 5,
    featured: true,
    displayOrder: 1,
    status: 'PUBLISHED',
  },
  {
    name: '(Dr.) Fr. Pius Varghese',
    designation: 'Principal',
    organisation: 'Don Bosco College of Teacher Education Tura',
    quote:
      'I have only great appreciation for BaseCode Labs company for their quick delivery of software products. Their outputs like website creation and updation are of global standards and purely professional. They are customer friendly and they deliver products on time. They are able to meet client satisfaction.',
    photo: '/images/testimonials/fr-pius.png',
    project: 'College website',
    industry: 'College',
    website: 'https://dbctetura.com/',
    rating: 5,
    featured: true,
    displayOrder: 2,
    status: 'PUBLISHED',
  },
  {
    name: 'P. Bhowmik',
    designation: 'Principal',
    organisation: 'Tura Public School',
    quote:
      'BaseCode Labs delivered our website on time and exceeded our expectations. Professional, responsive and great to work with. Highly recommended for anyone looking for quality web development services.',
    photo: '/images/testimonials/p-bhowmik-tps.png',
    project: 'School website',
    industry: 'School',
    website: 'https://turapublicschool.com/',
    rating: 5,
    featured: true,
    displayOrder: 3,
    status: 'PUBLISHED',
  },
  {
    name: 'Dr. Fr. Jogesh B. Sangma, SDB',
    designation: 'Principal',
    organisation: 'Don Bosco College Higher Sec. Section Tura',
    quote:
      'BaseCode Labs supported us with timely updates and a well-structured, user-friendly website experience. Their team was professional, responsive, and attentive to our requirements, ensuring smooth navigation and improved accessibility for our users. We appreciate their dedication and quality of service.',
    photo: '/images/testimonials/dr-fr-jogesh-sangma.png',
    project: 'Institution website',
    industry: 'Higher Secondary',
    website: 'https://dbchsstura.in/',
    rating: 5,
    featured: true,
    displayOrder: 4,
    status: 'PUBLISHED',
  },
  {
    name: 'Tiana Tarin D. Arengh',
    designation: 'Principal',
    organisation: 'PASF - Abong Noga College',
    quote:
      'BaseCode Labs delivered a clear, modern website that reflects our institution and serves students and parents well. The team was professional, listened to our needs, and completed the work on schedule. Communication was smooth throughout, and we are pleased with the result. We would gladly recommend their web development services.',
    photo: '/images/testimonials/tiana-tarin-arengh-pasf.png',
    project: 'College website',
    industry: 'College',
    website: 'https://pasfanc.ac.in/',
    rating: 5,
    featured: true,
    displayOrder: 5,
    status: 'PUBLISHED',
  },
  {
    name: 'Principal',
    designation: 'Anita Vidyalaya Higher Secondary School',
    organisation: 'Anita Vidyalaya Higher Secondary School, Thannipuzha, Kerala',
    quote:
      'BaseCode Labs delivered our school website with care, clarity, and professionalism. The design is easy to navigate for parents and students, updates are handled promptly, and the team was responsive at every step. We are grateful for their support and happily recommend them for quality web development.',
    photo: '/images/testimonials/anita-vidyalaya-principal.png',
    project: 'School website',
    industry: 'School',
    website: 'https://anitavidyalayahss.com/',
    rating: 5,
    featured: true,
    displayOrder: 6,
    status: 'PUBLISHED',
  },
];
