import type { IdCardLayoutInput, IdCardLayoutMeta, IdCardLayoutV1 } from '@/types/id-card-template';
import type {
  BuiltinIdCardTemplate,
  IdCardTemplateCategory,
} from '@/types/id-card-template-library';
import { layoutEl as el } from './id-card-layout-utils';

function layout(
  meta: IdCardLayoutMeta,
  front: IdCardLayoutV1['front'],
  back: IdCardLayoutV1['back'],
): IdCardLayoutV1 {
  return { version: 1, meta, front, back };
}

export const DBC_CLASSIC_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'dbc-classic', stylePreset: 'classic' },
  [
    el('headerBand', 0, 0, 53.98, 17, 0),
    el('watermark', 0, 16, 53.98, 69, 0),
    el('logo', 3, 2, 9, 8, 3, 'center'),
    el('collegeName', 0, 2, 53.98, 5.5, 4, 'center'),
    el('collegeAddress', 0, 7.5, 53.98, 4, 4, 'center'),
    el('affiliationLine', 0, 11.5, 53.98, 2.8, 4, 'center'),
    el('accreditationLine', 0, 14.2, 53.98, 2.5, 4, 'center'),
    el('photo', 18.5, 18.5, 17, 17, 5, 'center'),
    el('name', 2, 36.5, 50, 5.5, 6, 'center'),
    el('roleLabel', 2, 41.5, 50, 3, 6, 'center'),
    el('registrationNumber', 3, 45.5, 48, 3.6, 7),
    el('department', 3, 49.2, 48, 3.6, 7),
    el('programme', 3, 52.9, 48, 3.6, 7),
    el('gender', 3, 56.6, 48, 3.6, 7),
    el('bloodGroup', 3, 60.3, 48, 3.6, 7),
    el('validityBlock', 3, 64.5, 48, 14, 8, 'center'),
  ],
  [
    el('headerBand', 0, 0, 53.98, 8, 0),
    el('logo', 23.5, 1, 7, 6, 2, 'center'),
    el('qr', 17, 10, 20, 19, 3, 'center'),
    el('barcode', 4, 31, 46, 6.5, 4, 'center'),
    el('holderAddress', 3, 38.5, 48, 7, 5),
    el('fatherName', 3, 46, 48, 3.5, 6),
    el('motherName', 3, 49.5, 48, 3.5, 6),
    el('emergencyContact', 3, 53, 48, 3.5, 6),
    el('verificationInfo', 3, 57, 48, 6, 7),
    el('terms', 3, 63.5, 48, 10, 8),
    el('validityFooter', 0, 80, 53.98, 5.6, 9),
  ],
);

export const MODERN_GRADIENT_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'modern-gradient', stylePreset: 'gradient' },
  [
    el('headerBand', 0, 0, 53.98, 24, 0),
    el('watermark', 0, 20, 53.98, 65, 0),
    el('logo', 22, 2, 10, 9, 3, 'center'),
    el('collegeName', 0, 3, 53.98, 6, 4, 'center'),
    el('collegeAddress', 0, 9, 53.98, 4, 4, 'center'),
    el('affiliationLine', 0, 13, 53.98, 3, 4, 'center'),
    el('photo', 17, 26, 20, 20, 5, 'center', { photoShape: 'circle' }),
    el('name', 2, 47, 50, 6, 6, 'center'),
    el('roleLabel', 2, 52.5, 50, 3, 6, 'center'),
    el('registrationNumber', 4, 56.5, 46, 4, 7),
    el('department', 4, 61, 46, 4, 7),
    el('programme', 4, 65.5, 46, 4, 7),
    el('validity', 4, 71, 46, 5, 8, 'center'),
  ],
  [
    el('headerBand', 0, 0, 53.98, 7, 0),
    el('qr', 16.5, 9, 21, 21, 3, 'center'),
    el('verificationInfo', 3, 32, 48, 7, 4),
    el('holderAddress', 3, 40, 48, 8, 5),
    el('fatherName', 3, 49, 48, 3.5, 6),
    el('motherName', 3, 52.5, 48, 3.5, 6),
    el('barcode', 4, 57, 46, 6, 7, 'center'),
    el('terms', 3, 64, 48, 12, 8),
    el('validityFooter', 0, 80, 53.98, 5.6, 9),
  ],
);

export const CORPORATE_PROFESSIONAL_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'corporate-professional', stylePreset: 'corporate' },
  [
    el('headerBand', 0, 0, 53.98, 12, 0),
    el('logo', 2, 1.5, 8, 7, 2, 'center'),
    el('collegeName', 11, 2, 41, 5, 3, 'left'),
    el('collegeAddress', 11, 7, 41, 4, 3, 'left'),
    el('photo', 3, 14, 16, 28, 4, 'center'),
    el('name', 21, 16, 30, 7, 5, 'left'),
    el('roleLabel', 21, 23, 30, 3.5, 5, 'left'),
    el('employeeId', 21, 28, 30, 4, 6),
    el('designation', 21, 33, 30, 4, 6),
    el('department', 21, 38, 30, 4, 6),
    el('bloodGroup', 21, 43, 30, 4, 6),
    el('qr', 21, 49, 14, 14, 7, 'center'),
    el('validity', 36, 49, 15, 5, 7, 'center'),
  ],
  [
    el('headerBand', 0, 0, 53.98, 7, 0),
    el('barcode', 4, 10, 46, 7, 3, 'center'),
    el('address', 3, 19, 48, 10, 4),
    el('emergencyContact', 3, 30, 48, 5, 5),
    el('verificationInfo', 3, 36, 48, 6, 6),
    el('terms', 3, 43, 48, 14, 7),
    el('validityFooter', 0, 80, 53.98, 5.6, 8),
  ],
);

export const ACADEMIC_ELITE_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'academic-elite', stylePreset: 'academic' },
  [
    el('headerBand', 0, 0, 53.98, 20, 0),
    el('watermark', 0, 18, 53.98, 67, 0),
    el('logo', 20, 2, 14, 10, 3, 'center'),
    el('collegeName', 0, 3, 53.98, 6, 4, 'center'),
    el('collegeAddress', 0, 9, 53.98, 3.5, 4, 'center'),
    el('affiliationLine', 0, 12.5, 53.98, 3, 4, 'center'),
    el('accreditationLine', 0, 15.5, 53.98, 3, 4, 'center'),
    el('photo', 17, 22, 20, 20, 5, 'center'),
    el('name', 2, 44, 50, 6, 6, 'center'),
    el('roleLabel', 2, 50, 50, 3.5, 6, 'center'),
    el('designation', 3, 54.5, 48, 4, 7),
    el('department', 3, 59, 48, 4, 7),
    el('employeeId', 3, 63.5, 48, 4, 7),
    el('validityBlock', 3, 68.5, 48, 12, 8, 'center'),
  ],
  [
    el('headerBand', 0, 0, 53.98, 8, 0),
    el('logo', 23.5, 1, 7, 6, 2, 'center'),
    el('qr', 17, 10, 20, 18, 3, 'center'),
    el('principalSignature', 3, 30, 48, 10, 4, 'center'),
    el('verificationInfo', 3, 42, 48, 6, 5),
    el('emergencyContact', 3, 49, 48, 4, 6),
    el('terms', 3, 54, 48, 12, 7),
    el('validityFooter', 0, 80, 53.98, 5.6, 8),
  ],
);

export const RFID_SMART_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'rfid-smart', stylePreset: 'rfid' },
  [
    el('headerBand', 0, 0, 53.98, 14, 0),
    el('logo', 3, 2, 8, 7, 2, 'center'),
    el('collegeName', 0, 2.5, 53.98, 5, 3, 'center'),
    el('collegeAddress', 0, 7.5, 53.98, 3.5, 3, 'center'),
    el('photo', 19, 15, 16, 16, 4, 'center'),
    el('name', 2, 32, 50, 5.5, 5, 'center'),
    el('roleLabel', 2, 37.5, 50, 3, 5, 'center'),
    el('registrationNumber', 3, 41.5, 48, 3.5, 6),
    el('department', 3, 45.5, 48, 3.5, 6),
    el('rfidNumber', 3, 50, 48, 6, 7, 'center'),
    el('qr', 19, 57, 16, 16, 8, 'center'),
    el('validity', 2, 74, 50, 4, 9, 'center'),
  ],
  [
    el('headerBand', 0, 0, 53.98, 7, 0),
    el('qr', 16.5, 8, 21, 21, 3, 'center'),
    el('barcode', 4, 31, 46, 7, 4, 'center'),
    el('rfidNumber', 3, 39, 48, 5, 5, 'center'),
    el('verificationInfo', 3, 45, 48, 6, 6),
    el('holderAddress', 3, 52, 48, 6, 7),
    el('terms', 3, 59, 48, 12, 8),
    el('validityFooter', 0, 80, 53.98, 5.6, 9),
  ],
);

export const MINIMAL_WHITE_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'minimal-white', stylePreset: 'minimal' },
  [
    el('headerBand', 0, 0, 53.98, 6, 0),
    el('logo', 23.5, 0.5, 7, 5, 2, 'center'),
    el('collegeName', 0, 7, 53.98, 4.5, 3, 'center'),
    el('photo', 20, 13, 14, 14, 4, 'center', { photoShape: 'circle' }),
    el('name', 2, 28, 50, 6, 5, 'center'),
    el('roleLabel', 2, 34, 50, 3, 5, 'center'),
    el('registrationNumber', 4, 38.5, 46, 4, 6),
    el('department', 4, 43, 46, 4, 6),
    el('programme', 4, 47.5, 46, 4, 6),
    el('validity', 4, 53, 46, 4, 7, 'center'),
  ],
  [
    el('qr', 17, 8, 20, 20, 2, 'center'),
    el('verificationInfo', 3, 30, 48, 6, 3),
    el('barcode', 4, 38, 46, 6, 4, 'center'),
    el('terms', 3, 46, 48, 14, 5),
    el('validityFooter', 0, 80, 53.98, 5.6, 6),
  ],
);

export const PREMIUM_GOLD_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'premium-gold', stylePreset: 'gold' },
  [
    el('headerBand', 0, 0, 53.98, 18, 0),
    el('watermark', 0, 16, 53.98, 69, 0),
    el('logo', 21, 2, 12, 9, 3, 'center'),
    el('collegeName', 0, 2.5, 53.98, 6, 4, 'center'),
    el('collegeAddress', 0, 8.5, 53.98, 3.5, 4, 'center'),
    el('affiliationLine', 0, 12, 53.98, 3, 4, 'center'),
    el('photo', 18, 20, 18, 18, 5, 'center', { photoShape: 'circle' }),
    el('name', 2, 40, 50, 6.5, 6, 'center'),
    el('roleLabel', 2, 46.5, 50, 3.5, 6, 'center'),
    el('designation', 3, 51, 48, 4, 7),
    el('department', 3, 55.5, 48, 4, 7),
    el('employeeId', 3, 60, 48, 4, 7),
    el('validity', 3, 65, 48, 5, 8, 'center'),
  ],
  [
    el('headerBand', 0, 0, 53.98, 8, 0),
    el('logo', 23.5, 1, 7, 6, 2, 'center'),
    el('qr', 17, 10, 20, 18, 3, 'center'),
    el('principalSignature', 3, 30, 48, 10, 4, 'center'),
    el('emergencyContact', 3, 42, 48, 5, 5),
    el('terms', 3, 48, 48, 14, 6),
    el('validityFooter', 0, 80, 53.98, 5.6, 7),
  ],
);

export const STUDENT_COMPACT_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'student-compact', stylePreset: 'compact' },
  [
    el('headerBand', 0, 0, 53.98, 12, 0),
    el('logo', 2, 1.5, 7, 6, 2, 'center'),
    el('collegeName', 10, 2, 42, 4.5, 3, 'left'),
    el('collegeAddress', 10, 6.5, 42, 3.5, 3, 'left'),
    el('photo', 4, 14, 12, 12, 4, 'center'),
    el('name', 18, 14, 32, 5.5, 5, 'left'),
    el('roleLabel', 18, 19.5, 32, 2.5, 5, 'left'),
    el('department', 18, 23, 32, 3.5, 6),
    el('registrationNumber', 18, 27, 32, 3.5, 6),
    el('programme', 4, 31, 46, 3.5, 7),
    el('gender', 4, 35, 46, 3.5, 7),
    el('bloodGroup', 4, 39, 46, 3.5, 7),
    el('validityBlock', 4, 43, 46, 10, 8),
  ],
  [
    el('qr', 17, 8, 20, 20, 2, 'center'),
    el('barcode', 4, 30, 46, 7, 3, 'center'),
    el('verificationInfo', 3, 38, 48, 6, 4),
    el('terms', 3, 45, 48, 18, 5),
    el('validityFooter', 0, 80, 53.98, 5.6, 6),
  ],
);

export const GEOMETRIC_MODERN_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'geometric-modern', stylePreset: 'geometric' },
  [
    el('headerBand', 0, 0, 53.98, 19, 0),
    el('watermark', 0, 17, 53.98, 68, 0),
    el('logo', 3, 2, 9, 8, 3, 'center'),
    el('collegeName', 0, 2.5, 53.98, 5.5, 4, 'center'),
    el('collegeAddress', 0, 8, 53.98, 3.5, 4, 'center'),
    el('affiliationLine', 0, 11.5, 53.98, 3, 4, 'center'),
    el('photo', 4, 21, 16, 16, 5, 'center', { photoShape: 'circle' }),
    el('name', 22, 22, 28, 6, 6, 'left'),
    el('roleLabel', 22, 28, 28, 3, 6, 'left'),
    el('registrationNumber', 22, 32, 28, 3.5, 7),
    el('department', 22, 36, 28, 3.5, 7),
    el('programme', 4, 40, 46, 3.5, 7),
    el('gender', 4, 44, 46, 3.5, 7),
    el('bloodGroup', 4, 48, 46, 3.5, 7),
    el('validity', 4, 53, 46, 4, 8, 'center'),
  ],
  [
    el('headerBand', 0, 0, 53.98, 7, 0),
    el('qr', 16.5, 9, 21, 20, 3, 'center'),
    el('barcode', 4, 31, 46, 6.5, 4, 'center'),
    el('holderAddress', 3, 39, 48, 7, 5),
    el('fatherName', 3, 47, 48, 3.5, 6),
    el('motherName', 3, 50.5, 48, 3.5, 6),
    el('emergencyContact', 3, 54, 48, 3.5, 6),
    el('terms', 3, 58.5, 48, 12, 7),
    el('validityFooter', 0, 80, 53.98, 5.6, 8),
  ],
);

export const UNIVERSITY_ELITE_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'university-elite', stylePreset: 'elite' },
  [
    el('headerBand', 0, 0, 53.98, 18, 0),
    el('watermark', 0, 17, 53.98, 68, 0),
    el('logo', 3, 2, 10, 9, 3, 'center'),
    el('collegeName', 0, 2.5, 53.98, 6, 4, 'center'),
    el('collegeAddress', 0, 8.5, 53.98, 4, 4, 'center'),
    el('affiliationLine', 0, 12.5, 53.98, 3, 4, 'center'),
    el('accreditationLine', 0, 15.5, 53.98, 2.5, 4, 'center'),
    el('photo', 17.5, 19, 19, 19, 5, 'center'),
    el('name', 2, 39, 50, 6, 6, 'center'),
    el('roleLabel', 2, 45, 50, 3, 6, 'center'),
    el('registrationNumber', 3, 48.5, 48, 3.5, 7),
    el('department', 3, 52, 48, 3.5, 7),
    el('programme', 3, 55.5, 48, 3.5, 7),
    el('gender', 3, 59, 48, 3.5, 7),
    el('bloodGroup', 3, 62.5, 48, 3.5, 7),
    el('validityBlock', 3, 66.5, 48, 12, 8, 'center'),
  ],
  [
    el('headerBand', 0, 0, 53.98, 8, 0),
    el('logo', 23.5, 1, 7, 6, 2, 'center'),
    el('qr', 15.5, 9, 23, 22, 3, 'center'),
    el('barcode', 4, 33, 46, 6.5, 4, 'center'),
    el('holderAddress', 3, 40.5, 48, 6.5, 5),
    el('fatherName', 3, 47.5, 48, 3.5, 6),
    el('motherName', 3, 51, 48, 3.5, 6),
    el('emergencyContact', 3, 54.5, 48, 3.5, 6),
    el('verificationInfo', 3, 58.5, 48, 6, 7),
    el('terms', 3, 65, 48, 10, 8),
    el('validityFooter', 0, 80, 53.98, 5.6, 9),
  ],
);

export const DBC_PURSUIT_EXCELLENCE_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'dbc-pursuit-excellence', stylePreset: 'pursuit-excellence' },
  [
    el('headerBand', 0, 0, 53.98, 14, 0),
    el('footerBand', 0, 79.8, 53.98, 5.8, 0),
    el('watermark', 0, 13, 53.98, 66, 1),
    el('logo', 2, 0.8, 8, 8, 3, 'center'),
    el('collegeName', 10.5, 1, 41, 5, 4, 'center'),
    el('collegeAddress', 10.5, 6, 41, 3.2, 4, 'center'),
    el('securityHologram', 43.5, 1, 9, 5.5, 9),
    el('photo', 11.5, 14.5, 31, 34, 5, 'center'),
    el('name', 2, 49.5, 50, 5, 6, 'center'),
    el('roleLabel', 2, 54.8, 50, 2.2, 6, 'center'),
    el('subtitle', 2, 57.2, 50, 3.2, 6, 'center'),
    el('registrationNumber', 4, 60.6, 46, 3, 7),
    el('department', 4, 63.8, 46, 3, 7),
    el('gender', 4, 67, 46, 3, 7),
    el('rfidNumber', 4, 70.2, 46, 3, 7),
    el('validity', 9, 73.5, 36, 5.5, 8, 'center'),
  ],
  [
    el('footerBand', 0, 79.8, 53.98, 5.8, 0),
    el('watermark', 0, 18, 53.98, 58, 1),
    el('collegeName', 2, 2, 50, 4.5, 3, 'center'),
    el('qr', 20, 7, 14, 13, 4, 'center'),
    el('verificationInfo', 2, 20.5, 50, 3, 5, 'center'),
    el('barcode', 3.5, 24, 47, 6.5, 6, 'center'),
    el('programme', 4, 31, 46, 3, 7),
    el('contact', 3, 34.5, 48, 14.5, 8),
    el('emergencyContact', 4, 49.5, 46, 3, 8),
    el('terms', 3, 52.5, 27, 10, 8),
    el('principalSignature', 30, 62.5, 22, 16, 9, 'center'),
  ],
);

export const DBC_PURSUIT_STAFF_LAYOUT: IdCardLayoutV1 = layout(
  { libraryCode: 'dbc-pursuit-staff', stylePreset: 'pursuit-staff' },
  [
    el('headerBand', 0, 0, 53.98, 16, 0),
    el('footerBand', 0, 79.8, 53.98, 5.8, 0),
    el('watermark', 0, 14, 53.98, 64, 1),
    el('logo', 2, 1, 8.5, 8.5, 3, 'center'),
    el('collegeName', 11, 1.2, 41, 5, 4, 'center'),
    el('collegeAddress', 11, 6.2, 41, 3, 4, 'center'),
    el('affiliationLine', 11, 9.2, 41, 2.6, 4, 'center'),
    el('accreditationLine', 11, 11.8, 41, 2.6, 4, 'center'),
    el('photo', 11.5, 16.5, 31, 26, 5, 'center'),
    el('name', 2, 43.5, 50, 4.2, 6, 'center'),
    el('subtitle', 2, 47.9, 50, 2.8, 6, 'center'),
    el('roleLabel', 2, 50.9, 50, 2.6, 6, 'center'),
    el('employeeId', 3.5, 54, 27, 2.2, 7),
    el('department', 3.5, 56.4, 27, 2.2, 7),
    el('email', 3.5, 58.8, 27, 2.2, 7),
    el('phone', 3.5, 61.2, 27, 2.2, 7),
    el('joiningDate', 3.5, 63.6, 27, 2.2, 7),
    el('rfidNumber', 3.5, 66, 27, 2.2, 7),
    el('principalSignature', 31, 54, 21, 18, 9, 'center'),
    el('validity', 9, 73, 36, 5.2, 8, 'center'),
  ],
  [
    el('footerBand', 0, 79.8, 53.98, 5.8, 0),
    el('watermark', 0, 18, 53.98, 58, 1),
    el('collegeName', 2, 2, 50, 4.5, 3, 'center'),
    el('qr', 20, 7, 14, 13, 4, 'center'),
    el('verificationInfo', 2, 20.5, 50, 3, 5, 'center'),
    el('barcode', 3.5, 24, 47, 6.5, 6, 'center'),
    el('contact', 3, 31, 48, 15, 7),
    el('terms', 3, 46.5, 28, 10, 8),
    el('principalSignature', 30, 62.5, 22, 16, 9, 'center'),
  ],
);

export const BUILTIN_ID_CARD_TEMPLATES: BuiltinIdCardTemplate[] = [
  {
    code: 'dbc-pursuit-staff',
    name: 'DBC Pursuit Staff (Navy & Gold)',
    description:
      'Official Don Bosco College staff design — navy header with gold accents, employee details, QR/barcode verification back.',
    category: 'STAFF',
    holderType: 'STAFF',
    tags: ['dbc', 'official', 'staff', 'gold'],
    styleLabel: 'Pursuit Staff Gold',
    colorHints: ['Navy Blue', 'Gold', 'White'],
    bestFor: ['Teaching Staff', 'Non-Teaching Staff', 'Administration'],
    layout: DBC_PURSUIT_STAFF_LAYOUT,
  },
  {
    code: 'dbc-pursuit-excellence',
    name: 'DBC Pursuit of Excellence',
    description:
      'Official Don Bosco College Tura design — navy & maroon curved header, icon rows, QR verification back, terms block, and principal signature.',
    category: 'STUDENT',
    holderType: 'STUDENT',
    tags: ['dbc', 'official', 'premium', 'nehu'],
    styleLabel: 'Pursuit of Excellence',
    colorHints: ['Navy Blue', 'Maroon Red', 'White'],
    bestFor: ['Don Bosco College Tura', 'NEHU Affiliated Colleges', 'Premium Student IDs'],
    layout: DBC_PURSUIT_EXCELLENCE_LAYOUT,
  },
  {
    code: 'dbc-classic',
    name: 'DBC Classic',
    description:
      'Formal academic layout with full institution identity, key-value rows, and long-term validity block.',
    category: 'STUDENT',
    holderType: 'STUDENT',
    tags: ['formal', 'academic', 'university'],
    styleLabel: 'Formal Academic',
    colorHints: ['Navy Blue', 'White', 'Gold accent'],
    bestFor: ['Traditional Colleges', 'Universities'],
    layout: DBC_CLASSIC_LAYOUT,
  },
  {
    code: 'modern-gradient',
    name: 'Modern Gradient',
    description: 'Premium gradient header with circular photo and minimal front-side details.',
    category: 'STUDENT',
    holderType: 'STUDENT',
    tags: ['modern', 'gradient', 'premium'],
    styleLabel: 'Modern Premium',
    colorHints: ['Purple', 'Blue', 'Pink gradient'],
    bestFor: ['Modern Universities', 'Professional Colleges'],
    layout: MODERN_GRADIENT_LAYOUT,
  },
  {
    code: 'corporate-professional',
    name: 'Corporate Professional',
    description: 'Vertical photo strip with corporate typography for staff and administration.',
    category: 'STAFF',
    holderType: 'STAFF',
    tags: ['corporate', 'staff', 'minimal'],
    styleLabel: 'Corporate MNC',
    colorHints: ['Dark Blue', 'Gray', 'White'],
    bestFor: ['Staff', 'Faculty', 'Administration'],
    layout: CORPORATE_PROFESSIONAL_LAYOUT,
  },
  {
    code: 'academic-elite',
    name: 'Academic Elite',
    description:
      'Large institution branding with signature area for professors and research scholars.',
    category: 'STAFF',
    holderType: 'STAFF',
    tags: ['academic', 'signature', 'elite'],
    styleLabel: 'Academic Official',
    colorHints: ['Maroon', 'Gold', 'White'],
    bestFor: ['Professors', 'Research Scholars'],
    layout: ACADEMIC_ELITE_LAYOUT,
  },
  {
    code: 'rfid-smart',
    name: 'RFID Smart Card',
    description:
      'Technology-focused layout with prominent RFID, QR, and barcode for smart campus access.',
    category: 'SPECIAL',
    holderType: 'STUDENT',
    tags: ['rfid', 'smart', 'access'],
    styleLabel: 'Smart Campus',
    colorHints: ['Blue', 'White', 'Tech accent'],
    bestFor: ['Attendance', 'Library', 'Access Control'],
    layout: RFID_SMART_LAYOUT,
  },
  {
    code: 'minimal-white',
    name: 'Minimal White',
    description:
      'Clean SaaS-inspired card with white space, circular photo, and essential fields only.',
    category: 'STUDENT',
    holderType: 'STUDENT',
    tags: ['minimal', 'clean', 'modern'],
    styleLabel: 'Minimal Modern',
    colorHints: ['White', 'Gray', 'Blue accent'],
    bestFor: ['Large cohorts', 'Quick issuance'],
    layout: MINIMAL_WHITE_LAYOUT,
  },
  {
    code: 'premium-gold',
    name: 'Premium Gold',
    description: 'Executive card with gold accents for principal, vice principal, and management.',
    category: 'STAFF',
    holderType: 'STAFF',
    tags: ['premium', 'gold', 'executive'],
    styleLabel: 'Premium Executive',
    colorHints: ['Black', 'Gold', 'White'],
    bestFor: ['Principal', 'Vice Principal', 'Management'],
    layout: PREMIUM_GOLD_LAYOUT,
  },
  {
    code: 'student-compact',
    name: 'Student Compact',
    description:
      'Highly space-optimized layout for large student populations with essentials on front.',
    category: 'STUDENT',
    holderType: 'STUDENT',
    tags: ['compact', 'dense', 'efficient'],
    styleLabel: 'Space Optimized',
    colorHints: ['Institution colors'],
    bestFor: ['Large Student Population', 'Bulk printing'],
    layout: STUDENT_COMPACT_LAYOUT,
  },
  {
    code: 'geometric-modern',
    name: 'Geometric Modern',
    description: 'Dynamic geometric layout with offset photo and modern professional graphics.',
    category: 'STUDENT',
    holderType: 'STUDENT',
    tags: ['geometric', 'engineering', 'modern'],
    styleLabel: 'Geometric Modern',
    colorHints: ['Blue', 'Purple', 'Cyan'],
    bestFor: ['Engineering Colleges', 'Professional Institutes'],
    layout: GEOMETRIC_MODERN_LAYOUT,
  },
  {
    code: 'university-elite',
    name: 'University Elite',
    description:
      'Flagship university template with large photo, watermark, verification QR, and security elements.',
    category: 'STUDENT',
    holderType: 'STUDENT',
    tags: ['flagship', 'elite', 'verification'],
    styleLabel: 'University Flagship',
    colorHints: ['Institution primary', 'Accent', 'White'],
    bestFor: ['Premier Institutions', 'Official student ID'],
    layout: UNIVERSITY_ELITE_LAYOUT,
  },
  {
    code: 'alumni-member',
    name: 'Alumni Card',
    description: 'Alumni membership card with lifetime validity styling.',
    category: 'SPECIAL',
    holderType: 'ALUMNI',
    tags: ['alumni', 'future'],
    styleLabel: 'Alumni',
    colorHints: ['Gold', 'Navy'],
    bestFor: ['Alumni Association'],
    layout: DBC_CLASSIC_LAYOUT,
    comingSoon: true,
  },
  {
    code: 'library-access',
    name: 'Library Access',
    description: 'Library member card with member ID and access QR.',
    category: 'LIBRARY',
    holderType: 'LIBRARY',
    tags: ['library', 'future'],
    styleLabel: 'Library',
    colorHints: ['Green', 'White'],
    bestFor: ['Library Members'],
    layout: MINIMAL_WHITE_LAYOUT,
    comingSoon: true,
  },
  {
    code: 'visitor-pass',
    name: 'Visitor Pass',
    description: 'Temporary visitor pass with validity emphasis.',
    category: 'VISITOR',
    holderType: 'VISITOR',
    tags: ['visitor', 'future'],
    styleLabel: 'Visitor',
    colorHints: ['Orange', 'White'],
    bestFor: ['Campus Visitors'],
    layout: MINIMAL_WHITE_LAYOUT,
    comingSoon: true,
  },
  {
    code: 'exam-hall-pass',
    name: 'Exam Hall Pass',
    description: 'Examination access pass for hall entry verification.',
    category: 'SPECIAL',
    holderType: 'TEMPORARY',
    tags: ['exam', 'future'],
    styleLabel: 'Exam Access',
    colorHints: ['Red', 'White'],
    bestFor: ['Examination Halls'],
    layout: STUDENT_COMPACT_LAYOUT,
    comingSoon: true,
  },
  {
    code: 'hostel-resident',
    name: 'Hostel Card',
    description: 'Hostel resident identification with room and emergency details.',
    category: 'SPECIAL',
    holderType: 'STUDENT',
    tags: ['hostel', 'future'],
    styleLabel: 'Hostel',
    colorHints: ['Teal', 'White'],
    bestFor: ['Hostel Residents'],
    layout: STUDENT_COMPACT_LAYOUT,
    comingSoon: true,
  },
  {
    code: 'research-fellow',
    name: 'Research Scholar',
    description: 'Research fellow card with department and supervisor fields.',
    category: 'STAFF',
    holderType: 'RESEARCH',
    tags: ['research', 'future'],
    styleLabel: 'Research Fellow',
    colorHints: ['Maroon', 'Gold'],
    bestFor: ['PhD Scholars', 'Research Fellows'],
    layout: ACADEMIC_ELITE_LAYOUT,
    comingSoon: true,
  },
];

export const TEMPLATE_GALLERY_CATEGORIES: { id: IdCardTemplateCategory | 'ALL'; label: string }[] =
  [
    { id: 'ALL', label: 'All Templates' },
    { id: 'STUDENT', label: 'Student Templates' },
    { id: 'STAFF', label: 'Staff Templates' },
    { id: 'LIBRARY', label: 'Library Templates' },
    { id: 'VISITOR', label: 'Visitor Templates' },
    { id: 'SPECIAL', label: 'Special Templates' },
  ];

export function getBuiltinTemplate(code: string): BuiltinIdCardTemplate | undefined {
  return BUILTIN_ID_CARD_TEMPLATES.find((t) => t.code === code);
}

export function listBuiltinTemplates(
  category?: IdCardTemplateCategory | 'ALL',
): BuiltinIdCardTemplate[] {
  if (!category || category === 'ALL') return BUILTIN_ID_CARD_TEMPLATES;
  return BUILTIN_ID_CARD_TEMPLATES.filter((t) => t.category === category);
}

export function getBuiltinTemplateLayout(code: string): IdCardLayoutV1 | undefined {
  return getBuiltinTemplate(code)?.layout;
}

export function libraryCodeFromLayout(layout: IdCardLayoutInput | null | undefined): string | null {
  if (layout && typeof layout === 'object' && 'meta' in layout) {
    const meta = (layout as IdCardLayoutV1).meta;
    return meta?.libraryCode ?? null;
  }
  return null;
}
