export type ModuleCatalogCategory = 'core' | 'optional';

export type ModuleCatalogEntry = {
  key: string;
  label: string;
  category: ModuleCatalogCategory;
  defaultEnabled: boolean;
  description: string;
};

/** Module keys aligned with web nav `module` fields plus enterprise add-ons. */
export const MODULE_CATALOG: ModuleCatalogEntry[] = [
  // Core — always on
  {
    key: 'dashboard',
    label: 'Dashboard',
    category: 'core',
    defaultEnabled: true,
    description: 'Campus overview and analytics',
  },
  {
    key: 'students',
    label: 'Students',
    category: 'core',
    defaultEnabled: true,
    description: 'Student records and profiles',
  },
  {
    key: 'admissions',
    label: 'Admissions',
    category: 'core',
    defaultEnabled: true,
    description: 'Admissions pipeline',
  },
  {
    key: 'academics',
    label: 'Academics',
    category: 'core',
    defaultEnabled: true,
    description: 'Programs, courses, and academic engine',
  },
  {
    key: 'examinations',
    label: 'Examinations',
    category: 'core',
    defaultEnabled: true,
    description: 'Exams, IA, and exam fees',
  },
  {
    key: 'certificates',
    label: 'Certificates',
    category: 'core',
    defaultEnabled: true,
    description: 'Certificate issuance',
  },
  {
    key: 'finance',
    label: 'Fees & Finance',
    category: 'core',
    defaultEnabled: true,
    description: 'Fee collection and finance',
  },
  {
    key: 'accounts',
    label: 'Accounts',
    category: 'core',
    defaultEnabled: true,
    description: 'Finance & accounts ledger',
  },
  {
    key: 'administration',
    label: 'Administration',
    category: 'core',
    defaultEnabled: true,
    description: 'Users, RBAC, license, backups',
  },
  {
    key: 'settings',
    label: 'Settings',
    category: 'core',
    defaultEnabled: true,
    description: 'Organization settings',
  },
  {
    key: 'reports',
    label: 'Reports',
    category: 'core',
    defaultEnabled: true,
    description: 'Operational reports',
  },
  {
    key: 'staff',
    label: 'Staff',
    category: 'core',
    defaultEnabled: true,
    description: 'Staff directory',
  },
  {
    key: 'staffAttendance',
    label: 'Staff Attendance',
    category: 'core',
    defaultEnabled: true,
    description: 'Staff attendance',
  },
  {
    key: 'studentAttendance',
    label: 'Student Attendance',
    category: 'core',
    defaultEnabled: true,
    description: 'Student attendance',
  },
  {
    key: 'communication',
    label: 'Communication',
    category: 'core',
    defaultEnabled: true,
    description: 'Notifications and messaging',
  },
  {
    key: 'timetable',
    label: 'Timetable',
    category: 'core',
    defaultEnabled: true,
    description: 'Timetable engine',
  },
  {
    key: 'hr',
    label: 'Human Resources',
    category: 'core',
    defaultEnabled: true,
    description: 'HR, payroll, accommodation',
  },

  // Optional — existing modules default ON (backward compatible); net-new default OFF
  {
    key: 'shortTermCourses',
    label: 'Short-Term Courses',
    category: 'optional',
    defaultEnabled: true,
    description: 'Certificate / short-term course catalogue',
  },
  {
    key: 'departmentActivities',
    label: 'Department Activities',
    category: 'optional',
    defaultEnabled: true,
    description: 'Seminars, workshops, attendance, and certificates',
  },
  {
    key: 'campusCompetitions',
    label: 'Campus Competitions',
    category: 'optional',
    defaultEnabled: true,
    description:
      'Houses, sports meets, cultural competitions, scoring, and certificates',
  },
  {
    key: 'lms',
    label: 'LMS',
    category: 'optional',
    defaultEnabled: true,
    description: 'Learning management',
  },
  {
    key: 'questionBank',
    label: 'Question Bank',
    category: 'optional',
    defaultEnabled: true,
    description: 'Question bank authoring',
  },
  {
    key: 'syllabusRepository',
    label: 'Syllabus Repository',
    category: 'optional',
    defaultEnabled: true,
    description: 'Syllabus repository',
  },
  {
    key: 'library',
    label: 'Library',
    category: 'optional',
    defaultEnabled: true,
    description: 'Library circulation and digital',
  },
  {
    key: 'cams',
    label: 'CAMS',
    category: 'optional',
    defaultEnabled: true,
    description: 'Campus access management',
  },
  {
    key: 'infrastructure',
    label: 'Infrastructure',
    category: 'optional',
    defaultEnabled: true,
    description: 'Campus infrastructure',
  },
  {
    key: 'frontOffice',
    label: 'Front Office',
    category: 'optional',
    defaultEnabled: true,
    description: 'Front office desk',
  },
  {
    key: 'governance',
    label: 'Governance',
    category: 'optional',
    defaultEnabled: true,
    description: 'Governance & committees',
  },
  {
    key: 'officialDocuments',
    label: 'Official Documents',
    category: 'optional',
    defaultEnabled: true,
    description: 'Official notices and circulars',
  },
  {
    key: 'naacIqac',
    label: 'NAAC & IQAC',
    category: 'optional',
    defaultEnabled: true,
    description: 'NAAC / IQAC quality',
  },
  {
    key: 'transport',
    label: 'Transport',
    category: 'optional',
    defaultEnabled: true,
    description: 'Transport fleet and assignments',
  },
  {
    key: 'inventory',
    label: 'Inventory',
    category: 'optional',
    defaultEnabled: true,
    description: 'Stores and inventory',
  },
  {
    key: 'shifts',
    label: 'Shifts',
    category: 'optional',
    defaultEnabled: true,
    description: 'Shift operations',
  },
  {
    key: 'helpdesk',
    label: 'Helpdesk',
    category: 'optional',
    defaultEnabled: true,
    description:
      'Support Centre — live chat, tickets, FAQ, and multilingual helpdesk',
  },
  {
    key: 'parentPortal',
    label: 'Parent Portal',
    category: 'optional',
    defaultEnabled: true,
    description: 'Parent–student links and ward views',
  },
  {
    key: 'visitorManagement',
    label: 'Visitor Management',
    category: 'optional',
    defaultEnabled: true,
    description: 'Visitor check-in / check-out',
  },
  {
    key: 'placement',
    label: 'Placement',
    category: 'optional',
    defaultEnabled: true,
    description: 'Campus recruitment and drives',
  },
  {
    key: 'internship',
    label: 'Internship',
    category: 'optional',
    defaultEnabled: true,
    description: 'Internship companies and placements',
  },
  {
    key: 'alumni',
    label: 'Alumni',
    category: 'optional',
    defaultEnabled: true,
    description: 'Alumni profiles and mentorship',
  },
  {
    key: 'journals',
    label: 'Journals',
    category: 'optional',
    defaultEnabled: true,
    description: 'Multi-journal academic publishing portals',
  },
  {
    key: 'hostel',
    label: 'Hostel',
    category: 'optional',
    defaultEnabled: true,
    description: 'Hostel blocks, rooms, allotments',
  },
  {
    key: 'research',
    label: 'Research',
    category: 'optional',
    defaultEnabled: true,
    description: 'Research grants',
  },
  {
    key: 'workflow',
    label: 'Workflow',
    category: 'optional',
    defaultEnabled: true,
    description: 'Configurable approval workflows',
  },
  {
    key: 'integrations',
    label: 'Integrations',
    category: 'optional',
    defaultEnabled: true,
    description: 'External connectors and SSO',
  },
  {
    key: 'assetLifecycle',
    label: 'Asset Lifecycle',
    category: 'optional',
    defaultEnabled: true,
    description: 'Warranty / AMC asset services',
  },
  {
    key: 'dms',
    label: 'Document Management',
    category: 'optional',
    defaultEnabled: true,
    description: 'DMS search and expiry tracking',
  },
];

export const MODULE_CATALOG_BY_KEY = Object.fromEntries(
  MODULE_CATALOG.map((m) => [m.key, m]),
) as Record<string, ModuleCatalogEntry>;
