import type { AddStaffDraft } from '@/components/staff-module/add-staff/types/draft';
import type { CreateStaffPayload } from '@/types/staff';

export function buildCreateStaffPayload(
  draft: AddStaffDraft,
  institutionId?: string,
): CreateStaffPayload {
  const portalEmail = draft.portalEmail.trim() || draft.email.trim();
  const autoGenerated = draft.employeeCodeAutoGenerated && !draft.employeeCodeFinalized;
  const employeeCode = autoGenerated
    ? draft.employeeCodePreview.trim() || draft.employeeCode.trim()
    : draft.employeeCode.trim();

  return {
    employeeCode: employeeCode || undefined,
    employeeCodeAutoGenerated: autoGenerated,
    institutionId: institutionId || undefined,
    fullName: draft.fullName.trim(),
    email: draft.email.trim() || undefined,
    mobile: draft.mobile.trim() || undefined,
    staffType: draft.staffType,
    employmentType: draft.employmentType,
    departmentId: draft.departmentId || undefined,
    designationId: draft.designationId || undefined,
    primaryShiftId: draft.primaryShiftId || undefined,
    additionalShiftIds: draft.additionalShiftIds.length ? draft.additionalShiftIds : undefined,
    additionalRoleCodes: draft.additionalRoleCodes.length ? draft.additionalRoleCodes : undefined,
    shortCode: draft.shortCode || undefined,
    joiningDate: draft.joiningDate || undefined,
    probationEndDate: draft.probationEndDate || undefined,
    confirmationDate: draft.confirmationDate || undefined,
    gender: draft.gender || undefined,
    dateOfBirth: draft.dateOfBirth || undefined,
    qualification: draft.qualification.trim() || undefined,
    specialization: draft.specialization.trim() || undefined,
    experienceYears: draft.experienceYears,
    rfidNo: draft.rfidNo.trim() || undefined,
    biometricId: draft.biometricId.trim() || undefined,
    createPortalAccount: draft.createPortalAccount,
    portalRoleSlugs: draft.createPortalAccount ? draft.portalRoleSlugs : undefined,
    password:
      draft.createPortalAccount && draft.portalPassword.trim()
        ? draft.portalPassword.trim()
        : undefined,
    ...(draft.createPortalAccount && portalEmail ? { email: portalEmail } : {}),
  };
}

export function buildAddressSectionPayload(draft: AddStaffDraft) {
  return {
    addressJson: {
      line1: draft.addressLine1,
      line2: draft.addressLine2,
      city: draft.addressCity,
      state: draft.addressState,
      pinCode: draft.addressPin,
    },
    emergencyContactJson: {
      name: draft.emergencyName,
      phone: draft.emergencyPhone,
    },
  };
}

export function buildSalarySectionPayload(draft: AddStaffDraft) {
  return {
    bankName: draft.bankName.trim() || undefined,
    accountNumber: draft.accountNumber.trim() || undefined,
    ifsc: draft.ifsc.trim() || undefined,
    pfNumber: draft.pfNumber.trim() || undefined,
    basicPay: draft.basicPay.trim() ? Number(draft.basicPay) : undefined,
  };
}
