import type { StaffStepId } from '@/components/staff-module/add-staff/constants';
import { validateBiometricId } from '@/components/staff-module/add-staff/constants/biometric-fields';
import type { AddStaffDraft } from '@/components/staff-module/add-staff/types/draft';

/** Strip invisible chars and whitespace often pasted from spreadsheets. */
export function normalizeText(value: string): string {
  return value.replace(/[\u200B-\u200D\uFEFF]/g, '').trim();
}

export function normalizeEmail(value: string): string {
  return normalizeText(value).toLowerCase();
}

export function isValidEmail(value: string): boolean {
  const email = normalizeEmail(value);
  if (!email) return true;
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

export function normalizeBasicDraftFields(draft: AddStaffDraft): AddStaffDraft {
  return {
    ...draft,
    fullName: normalizeText(draft.fullName),
    employeeCode: normalizeText(draft.employeeCode),
    employeeCodePreview: normalizeText(draft.employeeCodePreview),
    email: normalizeEmail(draft.email),
    mobile: normalizeText(draft.mobile),
    rfidNo: normalizeText(draft.rfidNo),
    biometricId: normalizeText(draft.biometricId),
    qualification: normalizeText(draft.qualification),
    specialization: normalizeText(draft.specialization),
  };
}

export function validateStepFields(
  stepId: StaffStepId,
  draft: AddStaffDraft,
): Record<string, string> {
  const errors: Record<string, string> = {};

  if (stepId === 'basic') {
    const fullName = normalizeText(draft.fullName);
    const email = normalizeEmail(draft.email);

    if (!fullName) errors.fullName = 'Full name is required';
    if (email && !isValidEmail(email)) {
      errors.email = 'Invalid email';
    }
    const biometricErr = validateBiometricId(draft.biometricId);
    if (biometricErr) errors.biometricId = biometricErr;
  }

  if (stepId === 'employment') {
    if (!draft.staffType) errors.staffType = 'Staff type is required';
    if (!draft.employmentType) errors.employmentType = 'Employment type is required';
  }

  if (stepId === 'portal' && draft.createPortalAccount) {
    const email = normalizeEmail(draft.portalEmail) || normalizeEmail(draft.email);
    if (!email) errors.portalEmail = 'Portal email is required';
    if (draft.portalPassword && draft.portalPassword.length < 8) {
      errors.portalPassword = 'Password must be at least 8 characters';
    }
  }

  return errors;
}

export function firstStepError(errors: Record<string, string>): string | null {
  const first = Object.values(errors)[0];
  return first ?? null;
}

export function validateStaffSubmit(draft: AddStaffDraft): string[] {
  const issues: string[] = [];
  const basic = validateStepFields('basic', draft);
  const employment = validateStepFields('employment', draft);
  const portal = validateStepFields('portal', draft);

  for (const msg of Object.values({ ...basic, ...employment, ...portal })) {
    issues.push(msg);
  }

  if (draft.employeeCodeAutoGenerated) {
    if (!draft.staffType) issues.push('Staff type is required to generate employee code');
    if (!draft.joiningDate) issues.push('Joining date is required to generate employee code');
    const code = normalizeText(draft.employeeCodePreview || draft.employeeCode);
    if (!code) issues.push('Employee code preview is required — complete Employment details first');
  } else {
    const code = normalizeText(draft.employeeCode);
    if (!code) issues.push('Employee code is required');
  }

  return issues;
}

export function computeDraftCompletion(draft: AddStaffDraft): number {
  const employeeCodeReady = draft.employeeCodeAutoGenerated
    ? Boolean(draft.employeeCodePreview.trim() || draft.employeeCode.trim())
    : Boolean(draft.employeeCode.trim());

  const checks = [
    Boolean(draft.fullName.trim()),
    employeeCodeReady,
    Boolean(draft.staffType),
    Boolean(draft.departmentId),
    Boolean(draft.primaryShiftId),
    Boolean(draft.joiningDate),
    draft.staffType !== 'TEACHING' || draft.subjectAssignments.length > 0,
    !draft.createPortalAccount || Boolean(draft.portalEmail || draft.email),
  ];
  const done = checks.filter(Boolean).length;
  return Math.round((done / checks.length) * 100);
}
