'use client';

import { IdCard, RefreshCw, Tags, UserRound } from 'lucide-react';

import { AdmissionFormSection } from '@/components/students-module/add-student/ui/admission-form-section';
import { AdmissionPhotoUpload } from '@/components/students-module/add-student/ui/admission-photo-upload';
import {
  GlassField,
  admissionFormGridClass,
  glassInputClass,
  glassSelectClass,
} from '@/components/students-module/add-student/ui/glass-field';
import { Button } from '@/components/ui/button';
import { DateInput } from '@/components/ui/date-input';
import { capitalizeName } from '@/components/students-module/add-student/utils/admission-validation';
import { revokePhotoPreviewUrl } from '@/components/students-module/add-student/utils/photo-utils';
import type { AddStudentDraft } from '@/components/students-module/add-student/types/draft';
import type { LookupOptions } from '@/components/students-module/add-student/types/lookups';
import { SupportDataSelect } from '@/components/administration-module/support-data/support-data-select';
import { useSupportDataOptions } from '@/hooks/use-support-data';
import { cn } from '@/utils/cn';

type Props = {
  draft: AddStudentDraft;
  setDraft: React.Dispatch<React.SetStateAction<AddStudentDraft>>;
  lookups: LookupOptions;
  errors: Record<string, string>;
  rollPreviewLoading?: boolean;
  onRefreshRollPreview?: () => void;
};

export function StepBasic({
  draft,
  setDraft,
  lookups,
  errors,
  rollPreviewLoading,
  onRefreshRollPreview,
}: Props) {
  const genderOptions = useSupportDataOptions('gender');

  return (
    <div className="space-y-5">
      <AdmissionFormSection
        icon={UserRound}
        title="Identity"
        description="Core student identification details."
      >
        <div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between">
          <div className="min-w-0 flex-1 space-y-4">
            <GlassField label="Full Name" error={errors.fullName} className="max-w-none">
              <input
                className={glassInputClass}
                value={draft.fullName}
                onChange={(e) => setDraft((d) => ({ ...d, fullName: e.target.value }))}
                onBlur={(e) =>
                  setDraft((d) => ({ ...d, fullName: capitalizeName(e.target.value) }))
                }
                autoComplete="name"
              />
            </GlassField>

            <div className={cn(admissionFormGridClass)}>
              <GlassField label="Email" error={errors.email}>
                <input
                  type="email"
                  className={glassInputClass}
                  value={draft.email}
                  onChange={(e) => setDraft((d) => ({ ...d, email: e.target.value }))}
                  autoComplete="email"
                />
              </GlassField>
              <GlassField label="Application No.">
                <input
                  className={cn(glassInputClass, 'bg-muted/40')}
                  value={draft.applicationNumber}
                  readOnly
                />
              </GlassField>
              <GlassField label="NEHU Registration Number" error={errors.enrollmentNumber}>
                <input
                  className={glassInputClass}
                  value={draft.enrollmentNumber}
                  onChange={(e) => setDraft((d) => ({ ...d, enrollmentNumber: e.target.value }))}
                  placeholder="e.g. REG-2026-001"
                />
              </GlassField>
              <GlassField label="Mobile" error={errors.mobileNumber}>
                <input
                  className={glassInputClass}
                  inputMode="numeric"
                  value={draft.mobileNumber}
                  onChange={(e) =>
                    setDraft((d) => ({
                      ...d,
                      mobileNumber: e.target.value.replace(/\D/g, '').slice(0, 10),
                    }))
                  }
                  autoComplete="tel"
                  placeholder="10-digit mobile"
                />
              </GlassField>
              <GlassField
                label="Roll Number"
                error={errors.rollNumber}
                hint={
                  draft.rollNumberAutoGenerated
                    ? 'Generated from stream + admission year. Assigned on admit.'
                    : 'Enter a unique college roll number manually.'
                }
                labelAction={
                  <label className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
                    <input
                      type="checkbox"
                      className="rounded border-border"
                      checked={draft.rollNumberAutoGenerated}
                      onChange={(e) =>
                        setDraft((d) => ({
                          ...d,
                          rollNumberAutoGenerated: e.target.checked,
                          rollNumber: e.target.checked ? '' : d.rollNumber,
                        }))
                      }
                    />
                    Auto-generated
                  </label>
                }
              >
                <div className="flex w-full gap-2">
                  <input
                    className={cn(glassInputClass, draft.rollNumberAutoGenerated && 'bg-muted/40')}
                    value={
                      draft.rollNumberAutoGenerated
                        ? draft.rollNumberPreview || (rollPreviewLoading ? 'Generating…' : '—')
                        : draft.rollNumber
                    }
                    readOnly={draft.rollNumberAutoGenerated}
                    onChange={(e) =>
                      setDraft((d) => ({ ...d, rollNumber: e.target.value.toUpperCase() }))
                    }
                    placeholder={
                      draft.rollNumberAutoGenerated ? 'Select programme & batch' : 'e.g. BA26-001'
                    }
                  />
                  {draft.rollNumberAutoGenerated ? (
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      className="h-11 shrink-0 px-2"
                      disabled={rollPreviewLoading || !onRefreshRollPreview}
                      onClick={onRefreshRollPreview}
                      title="Refresh preview"
                    >
                      <RefreshCw className={cn('h-4 w-4', rollPreviewLoading && 'animate-spin')} />
                    </Button>
                  ) : null}
                </div>
              </GlassField>
              <GlassField label="NEHU Roll Number" error={errors.nehuRollNumber} optional>
                <input
                  className={glassInputClass}
                  value={draft.nehuRollNumber}
                  onChange={(e) => setDraft((d) => ({ ...d, nehuRollNumber: e.target.value }))}
                  placeholder="University roll no."
                />
              </GlassField>
              <GlassField
                label="ABC ID"
                error={errors.abcId}
                optional
                hint="Academic Bank of Credits ID"
              >
                <input
                  className={glassInputClass}
                  value={draft.abcId}
                  onChange={(e) =>
                    setDraft((d) => ({
                      ...d,
                      abcId: e.target.value.trim().slice(0, 20),
                    }))
                  }
                  placeholder="Enter ABC ID"
                  maxLength={20}
                />
              </GlassField>
            </div>
          </div>

          <AdmissionPhotoUpload
            photoPreviewUrl={draft.photoPreviewUrl}
            onPhotoChange={(dataUrl) =>
              setDraft((d) => {
                if (d.photoPreviewUrl && d.photoPreviewUrl !== dataUrl) {
                  revokePhotoPreviewUrl(d.photoPreviewUrl);
                }
                return { ...d, photoPreviewUrl: dataUrl };
              })
            }
          />
        </div>
      </AdmissionFormSection>

      <AdmissionFormSection
        icon={IdCard}
        title="Personal Details"
        description="Demographic and identity information."
      >
        <div className={admissionFormGridClass}>
          <GlassField label="Gender" optional>
            <SupportDataSelect
              category="gender"
              className={glassSelectClass}
              value={draft.gender}
              options={genderOptions.options}
              loading={genderOptions.isLoading}
              onChange={(gender) => setDraft((d) => ({ ...d, gender }))}
            />
          </GlassField>
          <GlassField label="Date of Birth" error={errors.dateOfBirth}>
            <DateInput
              className={glassInputClass}
              value={draft.dateOfBirth}
              onChange={(dateOfBirth) => setDraft((d) => ({ ...d, dateOfBirth }))}
            />
          </GlassField>
          <GlassField label="Aadhaar / National ID" error={errors.nationalId} optional>
            <input
              className={glassInputClass}
              inputMode="numeric"
              value={draft.nationalId}
              onChange={(e) =>
                setDraft((d) => ({
                  ...d,
                  nationalId: e.target.value.replace(/\D/g, '').slice(0, 12),
                }))
              }
              placeholder="12 digits"
            />
          </GlassField>
          <GlassField label="Blood Group" optional>
            <select
              className={glassSelectClass}
              value={draft.bloodGroupLookupId}
              onChange={(e) => setDraft((d) => ({ ...d, bloodGroupLookupId: e.target.value }))}
            >
              <option value="">Select blood group</option>
              {lookups.bloodGroupOptions.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.label}
                </option>
              ))}
            </select>
          </GlassField>
          <GlassField label="Nationality" optional>
            <select
              className={glassSelectClass}
              value={draft.nationalityLookupId}
              onChange={(e) => setDraft((d) => ({ ...d, nationalityLookupId: e.target.value }))}
            >
              <option value="">Select nationality</option>
              {lookups.nationalityOptions.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.label}
                </option>
              ))}
            </select>
          </GlassField>
          <GlassField label="Marital Status" optional>
            <select
              className={glassSelectClass}
              value={draft.maritalStatus}
              onChange={(e) => setDraft((d) => ({ ...d, maritalStatus: e.target.value }))}
            >
              <option value="">Select status</option>
              <option value="SINGLE">Single</option>
              <option value="MARRIED">Married</option>
            </select>
          </GlassField>
        </div>
      </AdmissionFormSection>

      <AdmissionFormSection
        icon={Tags}
        title="Reservation & Category"
        description="Community and admission classification."
        collapsible
        defaultOpen={Boolean(
          draft.religionLookupId || draft.categoryLookupId || draft.tribeLookupId,
        )}
      >
        <div className={admissionFormGridClass}>
          <GlassField label="Religion" optional>
            <select
              className={glassSelectClass}
              value={draft.religionLookupId}
              onChange={(e) => setDraft((d) => ({ ...d, religionLookupId: e.target.value }))}
            >
              <option value="">Select religion</option>
              {lookups.religionOptions.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.label}
                </option>
              ))}
            </select>
          </GlassField>
          <GlassField label="Category" optional>
            <select
              className={glassSelectClass}
              value={draft.categoryLookupId}
              onChange={(e) => setDraft((d) => ({ ...d, categoryLookupId: e.target.value }))}
            >
              <option value="">Select category</option>
              {lookups.categoryOptions.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.label}
                </option>
              ))}
            </select>
          </GlassField>
          <GlassField label="Tribe / Race" optional>
            <select
              className={glassSelectClass}
              value={draft.tribeLookupId}
              onChange={(e) => setDraft((d) => ({ ...d, tribeLookupId: e.target.value }))}
            >
              <option value="">Select tribe / race</option>
              {lookups.tribeOptions.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.label}
                </option>
              ))}
            </select>
          </GlassField>
        </div>
      </AdmissionFormSection>
    </div>
  );
}
