import { todayIsoDate } from '@/utils/format-date';

import type { Class12SubjectValue } from '@/components/students-module/class12-subject-multi-select';

export type GuardianBlock = {
  fullName: string;
  age?: number;
  occupation: string;
  contactNumber: string;
};

export type AddressBlock = {
  line1: string;
  line2: string;
  city: string;
  state: string;
  district: string;
  pinCode: string;
};

export type SubjectMark = {
  subjectName: string;
  marksObtained?: number;
  maxMarks?: number;
};

export type PendingDocument = {
  id: string;
  documentType: string;
  fileName: string;
};

export type SubjectBasketMeta = {
  creditsSelected: number;
  creditsTarget: number;
  categoriesComplete: string[];
  missingPoolCategories?: string[];
  requiredCategories?: string[];
  semesterSummary?: string;
  minorRequired?: boolean;
};

export type AddStudentDraft = {
  applicationNumber: string;
  photoPreviewUrl: string;
  fullName: string;
  email: string;
  enrollmentNumber: string;
  rollNumber: string;
  rollNumberAutoGenerated: boolean;
  rollNumberPreview: string;
  nehuRollNumber: string;
  abcId: string;
  mobileNumber: string;
  gender: string;
  dateOfBirth: string;
  nationalId: string;
  nationalityLookupId: string;
  bloodGroupLookupId: string;
  religionLookupId: string;
  maritalStatus: string;
  programVersionId: string;
  admissionBatchId: string;
  streamId: string;
  primaryShiftId: string;
  departmentId: string;
  campusId: string;
  majorSubjectSlug: string;
  minorSubjectSlug: string;
  majorSubjectId: string;
  minorSubjectId: string;
  majorCourseOfferingId: string;
  minorCourseOfferingId: string;
  admissionDate: string;
  admissionType: string;
  currentSemester?: number;
  categoryLookupId: string;
  tribeLookupId: string;
  denominationLookupId: string;
  differentlyAbled: boolean;
  ews: boolean;
  father: GuardianBlock;
  mother: GuardianBlock;
  localGuardian: GuardianBlock;
  homeSameAsTura: boolean;
  tura: AddressBlock;
  home: AddressBlock;
  boardName: string;
  schoolName: string;
  boardRollNumber: string;
  examYear?: number;
  boardStream: string;
  overallMarks?: number;
  overallPercentage?: number;
  registrationType: string;
  division: string;
  class12Subjects: Class12SubjectValue[];
  subjectMarks: SubjectMark[];
  cuetApplied: boolean;
  cuetRollNumber: string;
  cuetScore?: number;
  subjectSelections: Record<string, string>;
  subjectBasketMeta: SubjectBasketMeta;
  pendingDocuments: PendingDocument[];
  draftSavedAt: string;
  draftVersion: number;
};

export function emptyGuardian(): GuardianBlock {
  return { fullName: '', occupation: '', contactNumber: '' };
}

export function emptyAddress(): AddressBlock {
  return { line1: '', line2: '', city: '', state: '', district: '', pinCode: '' };
}

export function generateApplicationNumber(): string {
  const year = new Date().getFullYear();
  const rand = Math.floor(1000 + Math.random() * 9000);
  return `APP-${year}-${rand}`;
}

export function createEmptyDraft(): AddStudentDraft {
  return {
    applicationNumber: generateApplicationNumber(),
    photoPreviewUrl: '',
    fullName: '',
    email: '',
    enrollmentNumber: '',
    rollNumber: '',
    rollNumberAutoGenerated: true,
    rollNumberPreview: '',
    nehuRollNumber: '',
    abcId: '',
    mobileNumber: '',
    gender: '',
    dateOfBirth: '',
    nationalId: '',
    nationalityLookupId: '',
    bloodGroupLookupId: '',
    religionLookupId: '',
    maritalStatus: '',
    programVersionId: '',
    admissionBatchId: '',
    streamId: '',
    primaryShiftId: '',
    departmentId: '',
    campusId: '',
    majorSubjectSlug: '',
    minorSubjectSlug: '',
    majorSubjectId: '',
    minorSubjectId: '',
    majorCourseOfferingId: '',
    minorCourseOfferingId: '',
    admissionDate: todayIsoDate(),
    admissionType: 'REGULAR',
    categoryLookupId: '',
    tribeLookupId: '',
    denominationLookupId: '',
    differentlyAbled: false,
    ews: false,
    father: emptyGuardian(),
    mother: emptyGuardian(),
    localGuardian: emptyGuardian(),
    homeSameAsTura: false,
    tura: emptyAddress(),
    home: emptyAddress(),
    boardName: '',
    schoolName: '',
    boardRollNumber: '',
    boardStream: '',
    registrationType: '',
    division: '',
    class12Subjects: [],
    subjectMarks: [],
    cuetApplied: false,
    cuetRollNumber: '',
    subjectSelections: {},
    subjectBasketMeta: { creditsSelected: 0, creditsTarget: 0, categoriesComplete: [] },
    pendingDocuments: [],
    draftSavedAt: '',
    draftVersion: 1,
  };
}
