'use client';

import { AlertTriangle, Check, User } from 'lucide-react';

import type { AddStaffDraft } from '@/components/staff-module/add-staff/types/draft';
import { computeDraftCompletion } from '@/components/staff-module/add-staff/utils/validation';
import { staffTypeLabel } from '@/components/staff-module/directory/staff-filter-utils';
import { cn } from '@/utils/cn';

type Props = {
  draft: AddStaffDraft;
  departmentLabel?: string;
  shiftLabel?: string;
  validationIssues?: string[];
  className?: string;
  compact?: boolean;
};

export function AddStaffSummaryPanel({
  draft,
  departmentLabel,
  shiftLabel,
  validationIssues = [],
  className,
  compact,
}: Props) {
  const completion = computeDraftCompletion(draft);

  return (
    <aside
      className={cn(
        'glass-card space-y-2.5 rounded-xl border border-border/50 p-3 shadow-sm',
        compact && 'text-[11px]',
        className,
      )}
    >
      <div className="flex items-center gap-2 border-b border-border/40 pb-2">
        {draft.photoPreviewUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={draft.photoPreviewUrl}
            alt=""
            className="h-9 w-9 rounded-full object-cover ring-1 ring-primary/30"
          />
        ) : (
          <span className="flex h-9 w-9 items-center justify-center rounded-full bg-muted text-muted-foreground">
            <User className="h-4 w-4" />
          </span>
        )}
        <div className="min-w-0 flex-1">
          <p className="truncate text-xs font-semibold">{draft.fullName || 'New staff'}</p>
          <p className="truncate text-[10px] text-muted-foreground">
            {draft.employeeCodeAutoGenerated
              ? draft.employeeCodePreview || draft.employeeCode || 'Waiting for Employment category'
              : draft.employeeCode || '—'}
          </p>
        </div>
      </div>

      <dl className="grid grid-cols-2 gap-x-2 gap-y-1.5 text-[11px]">
        <div>
          <dt className="text-muted-foreground">Type</dt>
          <dd className="truncate font-medium">{staffTypeLabel(draft.staffType)}</dd>
        </div>
        <div>
          <dt className="text-muted-foreground">Department</dt>
          <dd className="truncate font-medium">{departmentLabel || '—'}</dd>
        </div>
        <div>
          <dt className="text-muted-foreground">Shift</dt>
          <dd className="truncate font-medium">{shiftLabel || '—'}</dd>
        </div>
        <div>
          <dt className="text-muted-foreground">Subjects</dt>
          <dd className="font-medium tabular-nums">{draft.subjectAssignments.length}</dd>
        </div>
      </dl>

      <div>
        <div className="mb-1 flex justify-between text-[10px] text-muted-foreground">
          <span>Completion</span>
          <span>{completion}%</span>
        </div>
        <div className="h-1.5 overflow-hidden rounded-full bg-muted">
          <div
            className="h-full bg-gradient-to-r from-primary to-violet-500"
            style={{ width: `${completion}%` }}
          />
        </div>
      </div>

      {validationIssues.length > 0 ? (
        <div className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-2 text-[10px] text-amber-800">
          <p className="mb-1 flex items-center gap-1 font-medium">
            <AlertTriangle className="h-3 w-3" />
            Issues
          </p>
          <ul className="list-disc pl-4">
            {validationIssues.slice(0, 4).map((issue) => (
              <li key={issue}>{issue}</li>
            ))}
          </ul>
        </div>
      ) : completion >= 70 ? (
        <p className="flex items-center gap-1 text-[10px] text-emerald-600">
          <Check className="h-3 w-3" />
          Ready to review
        </p>
      ) : null}
    </aside>
  );
}

export function AddStaffSummaryMobileBar(props: Props & { onOpen: () => void }) {
  const completion = computeDraftCompletion(props.draft);
  return (
    <button
      type="button"
      onClick={props.onOpen}
      className="glass-card fixed bottom-4 left-4 right-4 z-40 flex items-center justify-between rounded-xl border border-border/50 px-3 py-2 text-xs shadow-lg md:hidden"
    >
      <span>{props.draft.fullName || 'Staff draft'}</span>
      <span className="text-muted-foreground">{completion}% complete</span>
    </button>
  );
}
