import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { PrismaService } from '../../../database/prisma.service';
import type { JwtUser } from '../../../common/decorators/current-user.decorator';
import type { CreateJoiningReportDto } from '../dto/appointment-order.dto';
import { StaffProvisioningService } from '../../staff/services/staff-provisioning.service';
import { StaffPayAssignmentService } from '../../payroll/services/staff-pay-assignment.service';

@Injectable()
export class JoiningReportService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly staffProvisioning: StaffProvisioningService,
    private readonly payAssignments: StaffPayAssignmentService,
  ) {}

  private db() {
    return this.prisma as unknown as Record<string, any>;
  }

  list(tenantId: string, status?: string) {
    return this.db().joiningReport.findMany({
      where: {
        tenantId,
        ...(status ? { status } : {}),
      },
      include: {
        appointmentOrder: {
          select: {
            id: true,
            orderNo: true,
            candidateName: true,
            designationId: true,
            departmentId: true,
            status: true,
          },
        },
        staffProfile: {
          select: { id: true, fullName: true, employeeCode: true },
        },
      },
      orderBy: { createdAt: 'desc' },
      take: 200,
    });
  }

  async get(tenantId: string, id: string) {
    const report = await this.db().joiningReport.findFirst({
      where: { id, tenantId },
      include: {
        appointmentOrder: true,
        staffProfile: true,
      },
    });
    if (!report) throw new NotFoundException('Joining report not found');
    return report;
  }

  listAcceptedOrdersWithoutReport(tenantId: string) {
    return this.db().appointmentOrder.findMany({
      where: {
        tenantId,
        status: 'ACCEPTED',
        joiningReport: null,
      },
      orderBy: { acceptedAt: 'desc' },
      take: 100,
    });
  }

  async create(user: JwtUser, dto: CreateJoiningReportDto) {
    const order = await this.db().appointmentOrder.findFirst({
      where: { id: dto.appointmentOrderId, tenantId: user.tid },
      include: { joiningReport: true },
    });
    if (!order) throw new NotFoundException('Appointment order not found');
    if (order.status !== 'ACCEPTED') {
      throw new BadRequestException(
        'Only accepted orders can have joining reports.',
      );
    }
    if (order.joiningReport) {
      throw new BadRequestException(
        'Joining report already exists for this order.',
      );
    }

    return this.db().joiningReport.create({
      data: {
        tenantId: user.tid,
        appointmentOrderId: order.id,
        actualJoiningDate: new Date(dto.actualJoiningDate),
        reportingDate: dto.reportingDate ? new Date(dto.reportingDate) : null,
        remarks: dto.remarks,
        documentUrl: dto.documentUrl,
        submittedById: user.sub,
        status: 'SUBMITTED',
      },
    });
  }

  async verify(user: JwtUser, id: string) {
    const report = await this.get(user.tid, id);
    if (report.status === 'VERIFIED') {
      throw new BadRequestException('Joining report already verified.');
    }

    const order = report.appointmentOrder;
    if (!order || order.status !== 'ACCEPTED') {
      throw new BadRequestException('Appointment order must be accepted.');
    }

    let staffProfileId = order.staffProfileId ?? report.staffProfileId;

    if (!staffProfileId) {
      const staffType = this.mapStaffType(order.staffType);
      const employmentType = this.mapEmploymentType(order.appointmentType);
      const joiningDate =
        report.actualJoiningDate?.toISOString().slice(0, 10) ??
        order.joiningDate?.toISOString().slice(0, 10) ??
        new Date().toISOString().slice(0, 10);

      const probationEndDate =
        order.appointmentType === 'PROBATIONARY'
          ? this.addMonths(new Date(joiningDate), 24)
          : undefined;

      const created = await this.staffProvisioning.create(
        user.tid,
        {
          fullName: order.candidateName,
          email: order.email ?? undefined,
          mobile: order.mobile ?? undefined,
          staffType,
          employmentType,
          designationId: order.designationId ?? undefined,
          departmentId: order.departmentId ?? undefined,
          primaryShiftId: order.shiftId ?? undefined,
          joiningDate,
          dateOfBirth: order.dateOfBirth?.toISOString().slice(0, 10),
          photoUrl: order.photoUrl ?? undefined,
          status: 'ACTIVE',
          employeeCodeAutoGenerated: true,
        },
        user.sub,
      );
      staffProfileId = created.staff.id;

      await this.db().staffProfile.update({
        where: { id: staffProfileId },
        data: {
          joiningDate: new Date(joiningDate),
          probationEndDate: probationEndDate ?? null,
        },
      });

      if (order.payStructureTemplateId && order.basicPay) {
        await this.payAssignments.create(user, {
          staffProfileId,
          payStructureTemplateId: order.payStructureTemplateId,
          basicPay: Number(order.basicPay),
          effectiveFrom: joiningDate,
          payScaleType:
            order.staffType === 'TEACHING'
              ? 'COLLEGE_TEACHING'
              : 'COLLEGE_NON_TEACHING',
        });
      }

      await this.attachDocuments(user.tid, staffProfileId, order, report);
    } else {
      await this.db().staffProfile.update({
        where: { id: staffProfileId },
        data: {
          status: 'ACTIVE',
          joiningDate: report.actualJoiningDate,
        },
      });
    }

    await this.db().recruitmentApplication.updateMany({
      where: { id: order.applicationId, tenantId: user.tid },
      data: { status: 'HIRED', hiredStaffProfileId: staffProfileId },
    });

    const [updatedReport] = await Promise.all([
      this.db().joiningReport.update({
        where: { id },
        data: {
          status: 'VERIFIED',
          verifiedById: user.sub,
          verifiedAt: new Date(),
          staffProfileId,
        },
      }),
      this.db().appointmentOrder.update({
        where: { id: order.id },
        data: { status: 'JOINED', staffProfileId },
      }),
    ]);

    return updatedReport;
  }

  private async attachDocuments(
    tenantId: string,
    staffProfileId: string,
    order: Record<string, unknown>,
    report: Record<string, unknown>,
  ) {
    const docs: Array<{ type: string; url: string; name: string }> = [];
    if (order.pdfPath) {
      docs.push({
        type: 'APPOINTMENT_ORDER',
        url: String(order.pdfPath),
        name: `${order.orderNo ?? 'appointment'}.pdf`,
      });
    }
    if (order.signedCopyUrl) {
      docs.push({
        type: 'APPOINTMENT_ORDER',
        url: String(order.signedCopyUrl),
        name: 'signed-appointment-order',
      });
    }
    if (report.documentUrl) {
      docs.push({
        type: 'JOINING_REPORT',
        url: String(report.documentUrl),
        name: 'joining-report',
      });
    }

    for (const doc of docs) {
      await this.db().staffDocument.create({
        data: {
          tenantId,
          staffProfileId,
          documentType: doc.type,
          fileUrl: doc.url,
          fileName: doc.name,
          mimeType: doc.url.endsWith('.pdf') ? 'application/pdf' : null,
          verificationStatus: 'VERIFIED',
        },
      });
    }
  }

  private mapStaffType(staffType: string) {
    const map: Record<string, string> = {
      TEACHING: 'TEACHING',
      NON_TEACHING: 'NON_TEACHING',
      GUEST: 'GUEST',
      VISITING: 'VISITING',
      CONTRACT: 'CONTRACT',
    };
    return map[staffType] ?? 'NON_TEACHING';
  }

  private mapEmploymentType(appointmentType: string) {
    const map: Record<string, string> = {
      PERMANENT: 'PERMANENT',
      PROBATIONARY: 'PERMANENT',
      TEMPORARY: 'CONTRACT',
      CONTRACT: 'CONTRACT',
      VISITING_FACULTY: 'VISITING',
      GUEST_LECTURER: 'GUEST',
    };
    return map[appointmentType] ?? 'CONTRACT';
  }

  private addMonths(date: Date, months: number) {
    const d = new Date(date);
    d.setMonth(d.getMonth() + months);
    return d;
  }
}
