export const COMM_CENTER_NAV = [
  { label: 'Dashboard', href: '/admin/communication', icon: 'LayoutDashboard' },
  { label: 'Compose', href: '/admin/communication/compose', icon: 'Send' },
  { label: 'Campaigns', href: '/admin/communication/campaigns', icon: 'Megaphone' },
  { label: 'Templates', href: '/admin/communication/templates', icon: 'Mail' },
  { label: 'Audience Builder', href: '/admin/communication/audience', icon: 'Users' },
  { label: 'Scheduled', href: '/admin/communication/scheduled', icon: 'Calendar' },
  { label: 'Bulk Messaging', href: '/admin/communication/bulk', icon: 'Layers' },
  { label: 'Notifications', href: '/admin/communication/notifications', icon: 'Bell' },
  { label: 'Email Center', href: '/admin/communication/email', icon: 'AtSign' },
  { label: 'SMS Center', href: '/admin/communication/sms', icon: 'MessageSquare' },
  { label: 'WhatsApp', href: '/admin/communication/whatsapp', icon: 'Phone' },
  { label: 'Push Center', href: '/admin/communication/push', icon: 'Smartphone' },
  { label: 'Logs', href: '/admin/communication/logs', icon: 'ScrollText' },
  { label: 'Reports', href: '/admin/communication/reports', icon: 'FileBarChart' },
  { label: 'Failed', href: '/admin/communication/failed', icon: 'AlertTriangle' },
  { label: 'Analytics', href: '/admin/communication/analytics', icon: 'BarChart3' },
  { label: 'Approvals', href: '/admin/communication/approvals', icon: 'ShieldCheck' },
  { label: 'Settings', href: '/admin/communication/settings', icon: 'Settings' },
  { label: 'AI Assistant', href: '/admin/communication/ai', icon: 'Sparkles', soon: true },
] as const;

export const MESSAGE_VARIABLES = [
  { key: 'student_name', label: 'Student Name' },
  { key: 'staff_name', label: 'Staff Name' },
  { key: 'parent_name', label: 'Parent Name' },
  { key: 'roll_number', label: 'Roll Number' },
  { key: 'admission_number', label: 'Admission Number' },
  { key: 'department', label: 'Department' },
  { key: 'programme', label: 'Programme' },
  { key: 'semester', label: 'Semester' },
  { key: 'academic_year', label: 'Academic Year' },
  { key: 'fee_amount', label: 'Fee Amount' },
  { key: 'receipt_number', label: 'Receipt Number' },
  { key: 'payment_date', label: 'Payment Date' },
  { key: 'examination_name', label: 'Examination Name' },
  { key: 'otp', label: 'OTP' },
  { key: 'login_url', label: 'Login URL' },
  { key: 'attendance_percent', label: 'Attendance %' },
  { key: 'due_date', label: 'Due Date' },
  { key: 'library_fine', label: 'Library Fine' },
  { key: 'institution_name', label: 'Institution Name' },
  { key: 'application_number', label: 'Application Number' },
  { key: 'program_name', label: 'Programme Name' },
] as const;

export const CHANNEL_OPTIONS = [
  { value: 'IN_APP', label: 'In-App Notification' },
  { value: 'EMAIL', label: 'Email' },
  { value: 'SMS', label: 'SMS' },
  { value: 'WHATSAPP', label: 'WhatsApp' },
  { value: 'PUSH', label: 'Push Notification' },
] as const;

export const AUDIENCE_OPTIONS = [
  { value: 'STUDENTS', label: 'Students' },
  { value: 'FACULTY', label: 'Staff' },
  { value: 'PARENTS', label: 'Parents' },
  { value: 'ALUMNI', label: 'Alumni' },
  { value: 'COMMITTEE', label: 'Committee' },
  { value: 'DEPARTMENTS', label: 'Departments' },
  { value: 'INDIVIDUAL', label: 'Individual' },
] as const;
