import {
  IsArray,
  IsBoolean,
  IsDateString,
  IsEmail,
  IsIn,
  IsInt,
  IsNumber,
  IsObject,
  IsOptional,
  IsString,
  IsUUID,
  Min,
  MinLength,
  MaxLength,
} from 'class-validator';
import { Transform, Type } from 'class-transformer';
import { PaginationQueryDto } from '../../../common/dto/pagination.dto';

const toBool = ({ value }: { value: unknown }) =>
  value === true || value === 'true' || value === '1';

export const STAFF_TYPES = [
  'TEACHING',
  'NON_TEACHING',
  'GUEST',
  'VISITING',
  'CONTRACT',
  'ADMIN',
] as const;

export const EMPLOYMENT_TYPES = [
  'PERMANENT',
  'CONTRACT',
  'GUEST',
  'VISITING',
] as const;

export const STAFF_STATUSES = [
  'ACTIVE',
  'INACTIVE',
  'ON_LEAVE',
  'SUSPENDED',
  'RELIEVED',
  'RETIRED',
  'CONTRACT_ENDED',
] as const;

export const TEACHING_SHIFT_CATEGORIES = [
  'MORNING',
  'DAY',
  'BOTH',
  'EVENING',
  'WEEKEND',
  'ONLINE',
] as const;

export const STAFF_PROFILE_SECTIONS = [
  'basic',
  'employment',
  'portal',
  'salary',
  'address',
] as const;

export type StaffProfileSection = (typeof STAFF_PROFILE_SECTIONS)[number];

export class CreateStaffDto {
  @IsOptional()
  @IsString()
  @MinLength(2)
  employeeCode?: string;

  @IsOptional()
  @IsBoolean()
  employeeCodeAutoGenerated?: boolean;

  @IsOptional()
  @IsUUID()
  institutionId?: string;

  @IsString()
  @MinLength(2)
  fullName!: string;

  @IsOptional()
  @IsEmail()
  email?: string;

  @IsOptional()
  @IsString()
  mobile?: string;

  @IsOptional()
  @IsIn(STAFF_TYPES)
  staffType?: string;

  @IsOptional()
  @IsIn(EMPLOYMENT_TYPES)
  employmentType?: string;

  @IsOptional()
  @IsUUID()
  departmentId?: string;

  @IsOptional()
  @IsUUID()
  designationId?: string;

  @IsOptional()
  @IsUUID()
  primaryShiftId?: string;

  @IsOptional()
  @IsArray()
  @IsUUID(undefined, { each: true })
  additionalShiftIds?: string[];

  @IsOptional()
  @IsIn(TEACHING_SHIFT_CATEGORIES)
  teachingShiftCategory?: string;

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  additionalRoleCodes?: string[];

  @IsOptional()
  @IsString()
  shortCode?: string;

  @IsOptional()
  @IsDateString()
  joiningDate?: string;

  @IsOptional()
  @IsString()
  gender?: string;

  @IsOptional()
  @IsDateString()
  dateOfBirth?: string;

  @IsOptional()
  @IsString()
  qualification?: string;

  @IsOptional()
  @IsString()
  specialization?: string;

  @IsOptional()
  @IsInt()
  @Min(0)
  experienceYears?: number;

  @IsOptional()
  @IsString()
  @MaxLength(50)
  rfidNo?: string;

  @IsOptional()
  @IsString()
  @MaxLength(50)
  biometricId?: string;

  @IsOptional()
  @IsBoolean()
  createPortalAccount?: boolean;

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  portalRoleSlugs?: string[];

  @IsOptional()
  @IsString()
  @MinLength(8)
  password?: string;
}

export class UpdateStaffDto {
  @IsOptional()
  @IsString()
  @MinLength(2)
  employeeCode?: string;

  @IsOptional()
  @IsString()
  @MinLength(2)
  fullName?: string;

  @IsOptional()
  @IsEmail()
  email?: string;

  @IsOptional()
  @IsString()
  mobile?: string;

  @IsOptional()
  @IsIn(STAFF_TYPES)
  staffType?: string;

  @IsOptional()
  @IsIn(EMPLOYMENT_TYPES)
  employmentType?: string;

  @IsOptional()
  @IsUUID()
  departmentId?: string | null;

  @IsOptional()
  @IsUUID()
  designationId?: string | null;

  @IsOptional()
  @IsUUID()
  primaryShiftId?: string | null;

  @IsOptional()
  @IsArray()
  @IsUUID(undefined, { each: true })
  additionalShiftIds?: string[];

  @IsOptional()
  @IsIn(TEACHING_SHIFT_CATEGORIES)
  teachingShiftCategory?: string;

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  additionalRoleCodes?: string[];

  @IsOptional()
  @IsString()
  shortCode?: string | null;

  @IsOptional()
  @IsIn(STAFF_STATUSES)
  status?: string;

  @IsOptional()
  @IsDateString()
  joiningDate?: string | null;

  @IsOptional()
  @IsDateString()
  probationEndDate?: string | null;

  @IsOptional()
  @IsDateString()
  confirmationDate?: string | null;

  @IsOptional()
  @IsDateString()
  relievingDate?: string | null;

  @IsOptional()
  @IsDateString()
  retirementDate?: string | null;

  @IsOptional()
  @IsDateString()
  lastWorkingDate?: string | null;

  @IsOptional()
  @IsString()
  resignationReason?: string | null;

  @IsOptional()
  @IsString()
  @MaxLength(50)
  rfidNo?: string | null;

  @IsOptional()
  @IsString()
  @MaxLength(50)
  biometricId?: string | null;
}

export class UpdateStaffShiftsDto {
  @IsOptional()
  @IsUUID()
  primaryShiftId?: string | null;

  @IsOptional()
  @IsArray()
  @IsUUID(undefined, { each: true })
  additionalShiftIds?: string[];
}

export class CreateStaffAdditionalRoleDto {
  @IsString()
  roleCode!: string;

  @IsOptional()
  @IsDateString()
  startDate?: string;

  @IsOptional()
  @IsDateString()
  endDate?: string;
}

export class UpdateStaffAdditionalRoleDto {
  @IsOptional()
  @IsBoolean()
  active?: boolean;

  @IsOptional()
  @IsDateString()
  startDate?: string | null;

  @IsOptional()
  @IsDateString()
  endDate?: string | null;
}

export class CreateStaffPublicationDto {
  @IsString()
  @MinLength(2)
  title!: string;

  @IsString()
  publicationType!: string;

  @IsOptional()
  @IsString()
  journal?: string;

  @IsOptional()
  @IsString()
  isbnIssn?: string;

  @IsOptional()
  @IsString()
  doi?: string;

  @IsOptional()
  @IsString()
  coAuthors?: string;

  @IsOptional()
  @IsString()
  indexedIn?: string;

  @IsOptional()
  @IsDateString()
  publishedAt?: string;

  @IsOptional()
  @IsString()
  attachmentUrl?: string;
}

export class UpdateStaffPublicationDto {
  @IsOptional()
  @IsString()
  @MinLength(2)
  title?: string;

  @IsOptional()
  @IsString()
  publicationType?: string;

  @IsOptional()
  @IsString()
  journal?: string | null;

  @IsOptional()
  @IsString()
  isbnIssn?: string | null;

  @IsOptional()
  @IsString()
  doi?: string | null;

  @IsOptional()
  @IsString()
  coAuthors?: string | null;

  @IsOptional()
  @IsString()
  indexedIn?: string | null;

  @IsOptional()
  @IsDateString()
  publishedAt?: string | null;

  @IsOptional()
  @IsString()
  attachmentUrl?: string | null;
}

export class CreateStaffAwardDto {
  @IsString()
  @MinLength(2)
  title!: string;

  @IsOptional()
  @IsString()
  organization?: string;

  @IsOptional()
  @IsString()
  level?: string;

  @IsOptional()
  @IsDateString()
  awardDate?: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsString()
  certificateUrl?: string;
}

export class UpdateStaffAwardDto {
  @IsOptional()
  @IsString()
  @MinLength(2)
  title?: string;

  @IsOptional()
  @IsString()
  organization?: string | null;

  @IsOptional()
  @IsString()
  level?: string | null;

  @IsOptional()
  @IsDateString()
  awardDate?: string | null;

  @IsOptional()
  @IsString()
  description?: string | null;

  @IsOptional()
  @IsString()
  certificateUrl?: string | null;
}

export class ListDesignationsQueryDto {
  @IsOptional()
  @IsIn(STAFF_TYPES)
  staffType?: string;
}

export class StaffDirectoryQueryDto extends PaginationQueryDto {
  @IsOptional()
  @IsIn(STAFF_TYPES)
  staffType?: string;

  @IsOptional()
  @IsUUID()
  departmentId?: string;

  @IsOptional()
  @IsUUID()
  designationId?: string;

  @IsOptional()
  @IsUUID()
  shiftId?: string;

  @IsOptional()
  @IsIn(TEACHING_SHIFT_CATEGORIES)
  teachingShiftCategory?: string;

  @IsOptional()
  @IsIn(STAFF_STATUSES)
  status?: string;

  @IsOptional()
  @IsString()
  ids?: string;

  @IsOptional()
  @IsString()
  additionalRoleCode?: string;

  @IsOptional()
  @Transform(toBool)
  @IsBoolean()
  hodOnly?: boolean;

  @IsOptional()
  @Transform(toBool)
  @IsBoolean()
  activeTeachingOnly?: boolean;

  @IsOptional()
  @Transform(toBool)
  @IsBoolean()
  hasPublications?: boolean;
}

export class AssignSubjectDto {
  @IsUUID()
  courseId!: string;

  @IsInt()
  @Min(1)
  semesterNo!: number;

  @IsOptional()
  @IsUUID()
  programVersionId?: string;

  @IsOptional()
  @IsUUID()
  offeringSectionId?: string;

  @IsOptional()
  @IsUUID()
  shiftId?: string;

  @IsOptional()
  @IsUUID()
  academicYearId?: string;

  @IsOptional()
  @IsString()
  category?: string;

  @IsOptional()
  @IsNumber()
  workloadHours?: number;

  @IsOptional()
  @IsBoolean()
  isPrimaryFaculty?: boolean;

  @IsOptional()
  @IsString()
  role?: string;

  @IsOptional()
  @IsNumber()
  allocationPercent?: number;

  @IsOptional()
  @IsDateString()
  startDate?: string;

  @IsOptional()
  @IsDateString()
  endDate?: string;

  @IsOptional()
  @IsBoolean()
  canMarkAttendance?: boolean;

  @IsOptional()
  @IsBoolean()
  canEnterInternalMarks?: boolean;

  @IsOptional()
  @IsBoolean()
  canUploadLessonPlan?: boolean;

  @IsOptional()
  @IsBoolean()
  canAccessSubjectWorkspace?: boolean;
}

export class TeachingAssignmentContextQueryDto extends PaginationQueryDto {
  @IsOptional()
  @IsUUID()
  programVersionId?: string;

  @IsOptional()
  @IsUUID()
  departmentId?: string;

  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  semesterNo?: number;

  @IsOptional()
  @IsString()
  category?: string;

  @IsOptional()
  @IsUUID()
  shiftId?: string;

  @IsOptional()
  @IsString()
  sectionCode?: string;
}

export class UpdateStaffSectionDto {
  @IsObject()
  data!: Record<string, unknown>;
}

export class UploadStaffDocumentDto {
  @IsString()
  documentType!: string;
}

export class VerifyStaffDocumentDto {
  @IsString()
  verificationStatus!: string;

  @IsOptional()
  @IsString()
  verificationRemarks?: string;
}

export class UpdateStaffDocumentMetaDto {
  @IsOptional()
  @IsString()
  issueDate?: string;

  @IsOptional()
  @IsString()
  expiryDate?: string;
}

export class ProvisionStaffPortalDto {
  @IsEmail()
  email!: string;

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  roleSlugs?: string[];

  @IsOptional()
  @IsString()
  @MinLength(8)
  password?: string;

  @IsOptional()
  @IsUUID()
  shiftId?: string;

  @IsOptional()
  @IsUUID()
  campusId?: string;
}

export class GenerateEmployeeCodeDto {
  @IsString()
  @IsIn(STAFF_TYPES)
  staffType!: string;

  @IsOptional()
  @IsDateString()
  joiningDate?: string;

  @IsOptional()
  @IsUUID()
  institutionId?: string;

  @IsOptional()
  @Transform(toBool)
  @IsBoolean()
  preview?: boolean;

  @IsOptional()
  @IsUUID()
  staffProfileId?: string;
}

export const STAFF_IMPORT_MODES = ['CREATE', 'MERGE', 'REPLACE'] as const;
export type StaffImportMode = (typeof STAFF_IMPORT_MODES)[number];

export class ValidateStaffImportDto {
  @IsOptional()
  @IsIn(STAFF_IMPORT_MODES)
  importMode?: StaffImportMode;
}

export class CommitStaffImportDto {
  @IsUUID()
  batchId!: string;

  @IsOptional()
  @IsIn(['VALID_ONLY', 'STRICT'])
  mode?: 'VALID_ONLY' | 'STRICT';

  @IsOptional()
  @IsIn(STAFF_IMPORT_MODES)
  importMode?: StaffImportMode;
}
