import { describe, expect, it } from 'vitest';

import { createEmptyDraft } from '../types/draft';
import {
  firstStepError,
  isClass12BackgroundComplete,
  validateClass12Background,
  validateStepFields,
} from './admission-validation';
import { buildAdmitFullPayload } from './build-admit-payload';
import { buildAdmitWithRegistrationPayload } from './build-admit-payload';
import { mergeWithEmptyDraft } from './draft-storage';

function draftWithClass12() {
  return {
    ...createEmptyDraft(),
    fullName: 'Jane Doe',
    email: 'jane@example.com',
    enrollmentNumber: 'REG001',
    programVersionId: 'pv-1',
    admissionBatchId: 'batch-1',
    streamId: 'stream-1',
    primaryShiftId: 'shift-1',
    majorSubjectSlug: 'economics',
    boardName: 'MBOSE',
    schoolName: 'St. Mary School',
    examYear: 2024,
    boardStream: 'SCIENCE',
    overallPercentage: 78.5,
    class12Subjects: [{ name: 'Physics', code: 'physics' }],
  };
}

describe('admission validation', () => {
  it('requires basic fields', () => {
    const draft = createEmptyDraft();
    const errors = validateStepFields('basic', draft);
    expect(errors.fullName).toBeTruthy();
    expect(errors.email).toBeTruthy();
    expect(firstStepError(errors)).toBeTruthy();
  });

  it('validates academic programme selection', () => {
    const draft = {
      ...createEmptyDraft(),
      fullName: 'Jane Doe',
      email: 'jane@example.com',
      enrollmentNumber: 'REG001',
    };
    const errors = validateStepFields('academic', draft);
    expect(errors.programVersionId).toBeTruthy();
    expect(errors.boardName).toBeTruthy();
    expect(errors.class12Subjects).toBeTruthy();
  });

  it('requires Class XII background on academic step', () => {
    const errors = validateClass12Background(draftWithClass12());
    expect(errors).toEqual({});
    expect(isClass12BackgroundComplete(draftWithClass12())).toBe(true);
  });

  it('blocks fyugp when Class XII is incomplete', () => {
    const draft = {
      ...createEmptyDraft(),
      majorSubjectSlug: 'economics',
    };
    const errors = validateStepFields('fyugp', draft);
    expect(errors.class12Subjects).toContain('Academic step');
  });
});

describe('buildAdmitFullPayload', () => {
  it('maps core admit fields and Class XII sections', () => {
    const draft = draftWithClass12();
    const payload = buildAdmitFullPayload(draft);
    expect(payload.fullName).toBe('Jane Doe');
    expect(payload.majorSubjectSlug).toBe('economics');
    expect(payload.sections?.academic?.class12Subjects).toEqual(draft.class12Subjects);
    expect(payload.sections?.board_exam?.schoolName).toBe('St. Mary School');
    expect(payload.sections?.board_exam?.percentage).toBe(78.5);
  });

  it('maps NEHU Roll Number to admissionNumber', () => {
    const draft = { ...draftWithClass12(), nehuRollNumber: 'NEHU/2026/001' };
    const payload = buildAdmitFullPayload(draft);
    expect(payload.admissionNumber).toBe('NEHU/2026/001');
  });
});

describe('buildAdmitWithRegistrationPayload', () => {
  it('omits roll number when auto-generated', () => {
    const draft = {
      ...draftWithClass12(),
      rollNumberAutoGenerated: true,
      rollNumberPreview: 'BA26-003',
      rollNumber: '',
    };
    const payload = buildAdmitWithRegistrationPayload(draft, { registrationAction: 'SUBMIT' });
    expect(payload.rollNumber).toBeUndefined();
    expect(payload.generateRollNumber).toBe(true);
    expect(payload.rollNumberAutoGenerated).toBe(true);
  });

  it('sends manual roll number when auto-generated is off', () => {
    const draft = {
      ...draftWithClass12(),
      rollNumberAutoGenerated: false,
      rollNumber: 'BA26-099',
    };
    const payload = buildAdmitWithRegistrationPayload(draft, { registrationAction: 'SUBMIT' });
    expect(payload.rollNumber).toBe('BA26-099');
    expect(payload.generateRollNumber).toBe(false);
  });
});

describe('mergeWithEmptyDraft', () => {
  it('derives class12Subjects from non-placeholder mark rows', () => {
    const merged = mergeWithEmptyDraft({
      subjectMarks: [{ subjectName: 'Geography' }, { subjectName: 'Subject 2' }],
    });
    expect(merged.class12Subjects).toEqual([{ name: 'Geography' }]);
    expect(merged.subjectMarks).toEqual([{ subjectName: 'Geography' }]);
  });
});
