import type { AddStudentDraft } from '@/components/students-module/add-student/types/draft';
import type {
  AdmitStudentFullPayload,
  AdmitStudentWithRegistrationPayload,
} from '@/types/students';

function hasGuardianData(g: AddStudentDraft['father']) {
  return Boolean(g.fullName || g.contactNumber || g.occupation);
}

function hasAddressData(a: AddStudentDraft['tura']) {
  return Boolean(a.line1 || a.city || a.pinCode);
}

export function buildAdmitFullPayload(draft: AddStudentDraft): AdmitStudentFullPayload {
  const sections: Record<string, Record<string, unknown>> = {};

  if (
    hasGuardianData(draft.father) ||
    hasGuardianData(draft.mother) ||
    hasGuardianData(draft.localGuardian)
  ) {
    sections.guardians = {
      father: draft.father,
      mother: draft.mother,
      localGuardian: draft.localGuardian,
    };
  }

  if (hasAddressData(draft.tura) || hasAddressData(draft.home) || draft.homeSameAsTura) {
    sections.address = {
      homeSameAsTura: draft.homeSameAsTura,
      tura: draft.tura,
      home: draft.home,
    };
  }

  if (
    draft.categoryLookupId ||
    draft.religionLookupId ||
    draft.tribeLookupId ||
    draft.denominationLookupId ||
    draft.differentlyAbled ||
    draft.ews
  ) {
    sections.category_reservation = {
      categoryLookupId: draft.categoryLookupId || undefined,
      religionLookupId: draft.religionLookupId || undefined,
      tribeLookupId: draft.tribeLookupId || undefined,
      denominationLookupId: draft.denominationLookupId || undefined,
      differentlyAbled: draft.differentlyAbled,
      ews: draft.ews,
    };
  }

  if (
    draft.boardName ||
    draft.schoolName ||
    draft.boardRollNumber ||
    draft.class12Subjects.length > 0
  ) {
    sections.board_exam = {
      boardName: draft.boardName,
      schoolName: draft.schoolName || undefined,
      boardRollNumber: draft.boardRollNumber || undefined,
      examYear: draft.examYear,
      stream: draft.boardStream,
      registrationType: draft.registrationType || undefined,
      division: draft.division || undefined,
      totalMarks: draft.overallMarks,
      percentage: draft.overallPercentage,
      subjectMarks: draft.subjectMarks.filter((m) => m.subjectName.trim()),
    };
  }

  if (draft.class12Subjects.length > 0) {
    sections.academic = {
      class12Subjects: draft.class12Subjects,
    };
  }

  if (draft.cuetApplied) {
    sections.cuet = {
      cuetApplied: draft.cuetApplied,
      cuetRollNumber: draft.cuetRollNumber,
      cuetScore: draft.cuetScore,
    };
  }

  const primaryGuardian = draft.father.fullName
    ? draft.father
    : draft.mother.fullName
      ? draft.mother
      : draft.localGuardian;

  return {
    email: draft.email,
    enrollmentNumber: draft.enrollmentNumber,
    applicationNumber: draft.applicationNumber || undefined,
    fullName: draft.fullName,
    programVersionId: draft.programVersionId,
    admissionBatchId: draft.admissionBatchId,
    streamId: draft.streamId,
    primaryShiftId: draft.primaryShiftId,
    rollNumber: draft.rollNumber || undefined,
    admissionNumber: draft.nehuRollNumber.trim() || undefined,
    campusId: draft.campusId || undefined,
    departmentId: draft.departmentId || undefined,
    gender: draft.gender || undefined,
    maritalStatus: draft.maritalStatus || undefined,
    dateOfBirth: draft.dateOfBirth || undefined,
    mobileNumber: draft.mobileNumber || undefined,
    nationalId: draft.nationalId || undefined,
    nationalityLookupId: draft.nationalityLookupId || undefined,
    bloodGroupLookupId: draft.bloodGroupLookupId || undefined,
    religionLookupId: draft.religionLookupId || undefined,
    categoryLookupId: draft.categoryLookupId || undefined,
    tribeLookupId: draft.tribeLookupId || undefined,
    denominationLookupId: draft.denominationLookupId || undefined,
    differentlyAbled: draft.differentlyAbled,
    ews: draft.ews,
    majorSubjectSlug: draft.majorSubjectSlug || undefined,
    minorSubjectSlug: draft.minorSubjectSlug || undefined,
    admissionDate: draft.admissionDate || undefined,
    admissionType: draft.admissionType || undefined,
    currentSemester: draft.currentSemester || undefined,
    guardianName: primaryGuardian.fullName || undefined,
    guardianMobile: primaryGuardian.contactNumber || undefined,
    sections: Object.keys(sections).length > 0 ? sections : undefined,
  };
}

export function buildAdmitWithRegistrationPayload(
  draft: AddStudentDraft,
  options: {
    registrationAction?: 'NONE' | 'DRAFT' | 'SUBMIT';
    generateRollNumber?: boolean;
  },
): AdmitStudentWithRegistrationPayload {
  const autoRoll = draft.rollNumberAutoGenerated && !draft.rollNumber.trim();
  const base = buildAdmitFullPayload(draft);
  return {
    ...base,
    rollNumber: autoRoll ? undefined : base.rollNumber,
    subjectSelections: draft.subjectSelections,
    registrationAction: options.registrationAction ?? 'NONE',
    generateRollNumber: options.generateRollNumber ?? autoRoll,
    rollNumberAutoGenerated: draft.rollNumberAutoGenerated,
    semesterSequence: draft.currentSemester ?? 1,
  };
}
