import type { LucideIcon } from 'lucide-react';
import {
  Award,
  BookMarked,
  BookOpen,
  Building2,
  Bus,
  CalendarDays,
  ClipboardList,
  FileBarChart2,
  GraduationCap,
  HelpCircle,
  Home,
  LayoutDashboard,
  Library,
  Megaphone,
  Settings,
  Shield,
  Smartphone,
  Sparkles,
  Stethoscope,
  UserCog,
  Users,
  Wallet,
} from 'lucide-react';
import type { SchoolErpNavLink, SchoolErpNavModule } from '@/lib/school-erp/nav';

export type SchoolSisNavGroup = {
  id: string;
  label: string;
  items: SchoolErpNavModule[];
};

const soon = (id: string, label: string, extra?: Partial<SchoolErpNavLink>): SchoolErpNavLink => ({
  id,
  label,
  status: 'coming_soon',
  ...extra,
});

const live = (id: string, label: string, href: string): SchoolErpNavLink => ({
  id,
  label,
  href,
  status: 'active',
});

/** St. Luke's secondary SIS navigation — grouped ERP modules, not TPS KG. */
export const SCHOOL_SIS_NAV_GROUPS: SchoolSisNavGroup[] = [
  {
    id: 'main',
    label: 'MAIN',
    items: [
      {
        id: 'dashboard',
        label: 'Dashboard',
        href: '/admin',
        icon: LayoutDashboard as LucideIcon,
        status: 'active',
      },
      {
        id: 'academic-config',
        label: 'Academic Configuration',
        icon: BookMarked as LucideIcon,
        status: 'active',
        children: [
          live('ac-years', 'Academic Year', '/admin/school-sis/academic/years'),
          live('ac-classes', 'Classes', '/admin/school-sis/academic/classes'),
          live('ac-subjects', 'Subjects', '/admin/school-sis/academic/subjects'),
          live(
            'ac-class-subjects',
            'Class-wise Subjects',
            '/admin/school-sis/academic/class-subjects',
          ),
          live('ac-staff', 'Class-wise Staff', '/admin/school-sis/academic/staff'),
          live('ac-timetable', 'Timetable', '/admin/school-sis/timetable'),
          live('ac-optionals', 'Optional Subject Mapping', '/admin/school-sis/academic/optionals'),
          live('ac-houses', 'Student House Mapping', '/admin/school-sis/academic/houses'),
          live('ac-clubs', 'Student Club Mapping', '/admin/school-sis/academic/clubs'),
          live('ac-promotion', 'Student Promotion', '/admin/school-sis/academic/promotion'),
          live('ac-id-cards', 'ID Card Template', '/admin/school-sis/academic/id-cards'),
        ],
      },
      {
        id: 'application',
        label: 'Application',
        icon: ClipboardList as LucideIcon,
        status: 'active',
        children: [
          live('online-admission', 'Online admission', '/admin/school-sis/admissions'),
          live('public-apply', 'Public apply form', '/school-sis-portal/apply'),
        ],
      },
    ],
  },
  {
    id: 'people',
    label: 'PEOPLE & ADMISSION',
    items: [
      {
        id: 'students',
        label: 'Students',
        icon: GraduationCap as LucideIcon,
        status: 'active',
        children: [
          live('student-list', 'Student List', '/admin/school-sis/students'),
          live('student-add', 'Add Student', '/admin/school-sis/students/new'),
          live('student-enrollment', 'Student Enrollment', '/admin/school-sis/students'),
          soon('student-documents', 'Student Documents'),
          soon('student-history', 'Student History'),
        ],
      },
      {
        id: 'teachers',
        label: 'Teachers',
        icon: Users as LucideIcon,
        status: 'active',
        children: [
          live('teacher-list', 'Teacher List', '/admin/school-sis/staff'),
          live('teacher-profiles', 'Teacher Profiles', '/admin/school-sis/staff'),
          live('teacher-assignments', 'Teacher Assignments', '/admin/school-sis/allocation'),
        ],
      },
      {
        id: 'parents',
        label: 'Parents',
        icon: Users as LucideIcon,
        status: 'coming_soon',
        children: [soon('parent-list', 'Parent List'), soon('parent-accounts', 'Parent Accounts')],
      },
      {
        id: 'guardians',
        label: 'Guardians',
        icon: Users as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('guardian-list', 'Guardian List'),
          soon('guardian-relationships', 'Guardian Relationships'),
        ],
      },
      {
        id: 'staff',
        label: 'Staff',
        icon: UserCog as LucideIcon,
        status: 'active',
        children: [
          live('staff-list', 'Staff List', '/admin/school-sis/staff'),
          live('staff-profiles', 'Staff Profiles', '/admin/school-sis/staff'),
        ],
      },
      {
        id: 'users',
        label: 'Users',
        icon: Shield as LucideIcon,
        status: 'active',
        children: [
          live('user-accounts', 'User Accounts', '/admin/school-sis/users'),
          live('user-roles', 'Roles', '/admin/school-sis/users/roles'),
          live('user-permissions', 'Permissions', '/admin/school-sis/users/permissions'),
          live('user-sessions', 'Sessions', '/admin/school-sis/users/sessions'),
          live('user-audit', 'Security logs', '/admin/school-sis/users/audit'),
        ],
      },
    ],
  },
  {
    id: 'academic',
    label: 'ACADEMIC',
    items: [
      {
        id: 'classes-sections',
        label: 'Classes & Sections',
        icon: BookOpen as LucideIcon,
        status: 'active',
        children: [
          live('academic-years', 'Academic Years', '/admin/school-sis/academic/years'),
          live('classes', 'Classes', '/admin/school-sis/academic/classes'),
          live('sections', 'Sections', '/admin/school-sis/academic/classes'),
          live('class-teachers', 'Class Teachers', '/admin/school-sis/academic/staff'),
          live('student-allocation', 'Student Allocation', '/admin/school-sis/academic/staff'),
        ],
      },
      {
        id: 'subjects-curriculum',
        label: 'Subjects & Curriculum',
        icon: BookMarked as LucideIcon,
        status: 'active',
        children: [
          live('subject-types', 'Subject Types', '/admin/school-sis/academic/subjects?tab=types'),
          live('subjects', 'Subjects', '/admin/school-sis/academic/subjects?tab=list'),
          live(
            'subject-class-mapping',
            'Classwise Subject',
            '/admin/school-sis/academic/class-subjects',
          ),
          soon('subject-groups', 'Subject Groups'),
          soon('curriculum', 'Curriculum'),
        ],
      },
      {
        id: 'timetable',
        label: 'Timetable',
        icon: CalendarDays as LucideIcon,
        status: 'active',
        children: [
          live('tt-dashboard', 'Timetable Dashboard', '/admin/school-sis/timetable'),
          live('weekly-timetable', 'Weekly Timetable', '/admin/school-sis/timetable/weekly'),
          live('class-timetable', 'Class-wise Timetable', '/admin/school-sis/timetable/class'),
          live(
            'teacher-timetable',
            'Teacher-wise Timetable',
            '/admin/school-sis/timetable/teacher',
          ),
          live('my-timetable', 'My Timetable', '/admin/school-sis/timetable/mine'),
          live('timetable-config', 'Period Configuration', '/admin/school-sis/timetable/settings'),
          live(
            'timetable-conflicts',
            'Timetable Conflicts',
            '/admin/school-sis/timetable/conflicts',
          ),
          live('timetable-print', 'Print / Export', '/admin/school-sis/timetable/print'),
        ],
      },
      {
        id: 'learning',
        label: 'Learning',
        icon: Sparkles as LucideIcon,
        status: 'coming_soon',
      },
      {
        id: 'examination',
        label: 'Examination',
        icon: ClipboardList as LucideIcon,
        status: 'active',
        children: [
          live('exams', 'Exams', '/admin/school-sis/exams'),
          live('exam-schedule', 'Exam Schedule', '/admin/school-sis/exams/schedule'),
          live('marks-entry', 'Marks Entry', '/admin/school-sis/exams/marks'),
          live('grades', 'Grades', '/admin/school-sis/exams/grades'),
          live('results', 'Results', '/admin/school-sis/exams/results'),
          live('report-cards', 'Report Cards', '/admin/school-sis/exams/report-cards'),
        ],
      },
      {
        id: 'holidays',
        label: 'Holidays',
        icon: CalendarDays as LucideIcon,
        status: 'active',
        children: [
          live('holiday-calendar', 'Holiday Calendar', '/admin/school-sis/holidays'),
          live('academic-calendar', 'Academic Calendar', '/admin/school-sis/holidays/academic'),
        ],
      },
      {
        id: 'attendance',
        label: 'Attendance',
        icon: ClipboardList as LucideIcon,
        status: 'active',
        children: [
          live('student-attendance', 'Student Attendance', '/admin/school-sis/attendance'),
          live('take-attendance', 'Take Attendance', '/admin/school-sis/attendance/mark'),
          live(
            'attendance-absentees',
            'Today’s Absentees',
            '/admin/school-sis/attendance/absentees',
          ),
          live('attendance-leave', 'Leave', '/admin/school-sis/attendance/leave'),
          live('attendance-corrections', 'Corrections', '/admin/school-sis/attendance/corrections'),
          live('attendance-monthly', 'Monthly / Register', '/admin/school-sis/attendance/monthly'),
          live(
            'attendance-reports',
            'Attendance Reports',
            '/admin/school-sis/reports?module=attendance',
          ),
          live(
            'attendance-settings',
            'Attendance Settings',
            '/admin/school-sis/attendance/settings',
          ),
          live('staff-attendance', 'Staff Attendance', '/admin/school-sis/hr/attendance'),
        ],
      },
    ],
  },
  {
    id: 'hr',
    label: 'HR & PAYROLL',
    items: [
      {
        id: 'hr-payroll',
        label: 'HR & Payroll',
        icon: Building2 as LucideIcon,
        href: '/admin/school-sis/hr',
        status: 'active',
        children: [
          live('hr-dashboard', 'HR Dashboard', '/admin/school-sis/hr'),
          live('hr-employees', 'All Employees', '/admin/school-sis/hr/employees'),
          live('hr-teaching', 'Teaching Staff', '/admin/school-sis/hr/employees?type=TEACHING'),
          live(
            'hr-non-teaching',
            'Non-Teaching Staff',
            '/admin/school-sis/hr/employees?type=NON_TEACHING',
          ),
          live(
            'hr-documents',
            'Employee Documents',
            '/admin/school-sis/hr/employees?tab=documents',
          ),
          live('hr-import', 'Employee Import', '/admin/school-sis/hr/import'),
          live('hr-departments', 'Departments', '/admin/school-sis/hr/org?tab=departments'),
          live('hr-designations', 'Designations', '/admin/school-sis/hr/org?tab=designations'),
          live('hr-types', 'Employee Types', '/admin/school-sis/hr/org?tab=types'),
          live('hr-attendance', 'Attendance', '/admin/school-sis/hr/attendance'),
          live('hr-leave-types', 'Leave Types', '/admin/school-sis/hr/leave?tab=types'),
          live('hr-leave-policies', 'Leave Policies', '/admin/school-sis/hr/leave?tab=policies'),
          live('hr-leave-requests', 'Leave Requests', '/admin/school-sis/hr/leave?tab=requests'),
          live('hr-leave-calendar', 'Leave Calendar', '/admin/school-sis/hr/leave?tab=calendar'),
          live('hr-leave-balance', 'Leave Balance', '/admin/school-sis/hr/leave?tab=balance'),
          live('hr-payroll-dash', 'Payroll Dashboard', '/admin/school-sis/hr/payroll'),
          live('hr-structures', 'Salary Structure', '/admin/school-sis/hr/salary?tab=structures'),
          live('hr-process', 'Payroll Processing', '/admin/school-sis/hr/payroll?tab=process'),
          live('hr-register', 'Payroll Register', '/admin/school-sis/hr/payroll?tab=register'),
          live('hr-payments', 'Salary Payments', '/admin/school-sis/hr/payroll?tab=payments'),
          live('hr-history', 'Payroll History', '/admin/school-sis/hr/payroll?tab=history'),
          live('hr-components', 'Salary Components', '/admin/school-sis/hr/salary?tab=components'),
          live('hr-assign', 'Salary Assignments', '/admin/school-sis/hr/salary?tab=assign'),
          live('hr-revisions', 'Salary Revisions', '/admin/school-sis/hr/salary?tab=revisions'),
          live('hr-payslips', 'Payslips', '/admin/school-sis/hr/payslips'),
          live('hr-loans', 'Loans & Advances', '/admin/school-sis/hr/loans'),
          live('hr-reimb', 'Reimbursements', '/admin/school-sis/hr/reimbursements'),
          live('hr-self', 'Employee Self Service', '/admin/school-sis/hr/me'),
          live('hr-reports', 'HR Reports', '/admin/school-sis/reports?module=staff'),
        ],
      },
    ],
  },
  {
    id: 'finance',
    label: 'FINANCE & ACCOUNTS',
    items: [
      {
        id: 'fees',
        label: 'Fees',
        icon: Wallet as LucideIcon,
        status: 'active',
        children: [
          live('fee-structure', 'Fee Structure', '/admin/school-sis/fees'),
          live('monthly-fees', 'Monthly Fees (N–IV)', '/admin/school-sis/fees/monthly'),
          live('fee-collection', 'Collect fees', '/admin/school-sis/fees/collect'),
          live('pending-fees', 'Pending Fees', '/admin/school-sis/fees/pending'),
          live('fee-receipts', 'Collection register', '/admin/school-sis/fees/register'),
          live('fee-user-wise', 'User wise collection', '/admin/school-sis/fees/reports'),
          live('fee-settings', 'Fee configuration', '/admin/school-sis/fees/settings'),
          live('fee-gateways', 'Payment gateway integration', '/admin/school-sis/fees/gateways'),
          live(
            'fee-gateway-txns',
            'Gateway transactions',
            '/admin/school-sis/fees/gateways/transactions',
          ),
        ],
      },
      {
        id: 'billing',
        label: 'Billing',
        icon: Wallet as LucideIcon,
        status: 'active',
        children: [
          live('stationery-billing', 'Stationery Billing', '/admin/school-sis/stationery'),
          live(
            'stationery-products',
            'Stationery Products',
            '/admin/school-sis/stationery/products',
          ),
          live('stationery-categories', 'Categories', '/admin/school-sis/stationery/categories'),
          live('stationery-stock', 'Stock / Inventory', '/admin/school-sis/stationery/stock'),
          live(
            'stationery-purchases',
            'Stock Purchase / Receiving',
            '/admin/school-sis/stationery/purchases',
          ),
          live('stationery-adjust', 'Stock Adjustment', '/admin/school-sis/stationery/adjustments'),
          live('stationery-returns', 'Returns', '/admin/school-sis/stationery/returns'),
          live('stationery-suppliers', 'Suppliers', '/admin/school-sis/stationery/suppliers'),
          live('stationery-reports', 'Stationery Reports', '/admin/school-sis/stationery/reports'),
          soon('other-billing', 'Other Billing'),
        ],
      },
      {
        id: 'accounts',
        label: 'Accounts',
        icon: FileBarChart2 as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('income', 'Income'),
          soon('expenses', 'Expenses'),
          soon('ledger', 'Ledger'),
          soon('financial-reports', 'Financial Reports'),
        ],
      },
    ],
  },
  {
    id: 'campus',
    label: 'CAMPUS OPERATIONS',
    items: [
      {
        id: 'library',
        label: 'Library',
        icon: Library as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('books', 'Books'),
          soon('library-members', 'Members'),
          soon('issue-return', 'Issue/Return'),
          soon('fines', 'Fines'),
        ],
      },
      {
        id: 'transport',
        label: 'Transport',
        icon: Bus as LucideIcon,
        status: 'active',
        children: [
          live('tr-dash', 'Dashboard', '/admin/school-sis/transport'),
          live('vehicles', 'Vehicles', '/admin/school-sis/transport/vehicles'),
          live('routes', 'Routes', '/admin/school-sis/transport/routes'),
          live('stops', 'Stops', '/admin/school-sis/transport/stops'),
          live('drivers', 'Drivers', '/admin/school-sis/transport/drivers'),
          live('attendants', 'Attendants', '/admin/school-sis/transport/attendants'),
          live(
            'transport-allocation',
            'Student Allocation',
            '/admin/school-sis/transport/allocations',
          ),
          live('tr-trips', 'Trips & Attendance', '/admin/school-sis/transport/trips'),
          live('tr-track', 'Live Tracking', '/admin/school-sis/transport/tracking'),
          live('tr-inc', 'Incidents', '/admin/school-sis/transport/incidents'),
          live('tr-maint', 'Maintenance', '/admin/school-sis/transport/maintenance'),
          live('tr-fuel', 'Fuel', '/admin/school-sis/transport/fuel'),
          live('tr-fees', 'Fees', '/admin/school-sis/transport/fees'),
          live('tr-req', 'Requests', '/admin/school-sis/transport/requests'),
          live('tr-set', 'Settings', '/admin/school-sis/transport/settings'),
        ],
      },
      {
        id: 'sports',
        label: 'Sports',
        icon: Award as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('sports-list', 'Sports'),
          soon('teams', 'Teams'),
          soon('activities', 'Activities'),
          soon('sports-achievements', 'Achievements'),
        ],
      },
      {
        id: 'hostel',
        label: 'Hostel',
        icon: Home as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('hostels', 'Hostels'),
          soon('rooms', 'Rooms'),
          soon('hostel-allocation', 'Student Allocation'),
        ],
      },
      {
        id: 'cafeteria',
        label: 'Cafeteria',
        icon: Building2 as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('menu', 'Menu'),
          soon('cafeteria-billing', 'Billing'),
          soon('cafeteria-tx', 'Transactions'),
        ],
      },
      {
        id: 'assets',
        label: 'Assets',
        icon: Building2 as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('asset-list', 'Assets'),
          soon('inventory', 'Inventory'),
          soon('maintenance', 'Maintenance'),
        ],
      },
      {
        id: 'security',
        label: 'Security',
        icon: Shield as LucideIcon,
        status: 'coming_soon',
        children: [soon('visitors', 'Visitors'), soon('security-logs', 'Security Logs')],
      },
      {
        id: 'medical',
        label: 'Medical',
        icon: Stethoscope as LucideIcon,
        status: 'coming_soon',
        children: [soon('student-medical', 'Student Medical Records')],
      },
    ],
  },
  {
    id: 'communication',
    label: 'COMMUNICATION',
    items: [
      {
        id: 'broadcast',
        label: 'Broadcast',
        icon: Megaphone as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('announcements', 'Announcements'),
          soon('notices', 'Notices'),
          soon('circulars', 'Circulars'),
        ],
      },
      {
        id: 'sms',
        label: 'SMS',
        icon: Megaphone as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('sms-templates', 'SMS Templates'),
          soon('sms-campaigns', 'SMS Campaigns'),
          soon('sms-reports', 'Delivery Reports'),
        ],
      },
      {
        id: 'whatsapp',
        label: 'WhatsApp',
        icon: Megaphone as LucideIcon,
        status: 'active',
        children: [
          live('wa-dashboard', 'Dashboard', '/admin/school-sis/whatsapp'),
          live('wa-inbox', 'Inbox', '/admin/school-sis/whatsapp/inbox'),
          live('wa-contacts', 'Contacts', '/admin/school-sis/whatsapp/contacts'),
          live('wa-templates', 'Templates', '/admin/school-sis/whatsapp/templates'),
          live('wa-campaigns', 'Campaigns', '/admin/school-sis/whatsapp/campaigns'),
          live('wa-messaging', 'Messaging', '/admin/school-sis/whatsapp/messaging'),
          live('wa-automation', 'Automation', '/admin/school-sis/whatsapp/automation'),
          live('wa-status', 'Delivery Status', '/admin/school-sis/whatsapp/delivery'),
          live('wa-scheduled', 'Scheduled Messages', '/admin/school-sis/whatsapp/scheduled'),
          live('wa-media', 'Media Library', '/admin/school-sis/whatsapp/media'),
          live('wa-flows', 'WhatsApp Flows', '/admin/school-sis/whatsapp/flows'),
          live('wa-analytics', 'Analytics', '/admin/school-sis/whatsapp/analytics'),
          live('wa-optin', 'Opt-in / Consent', '/admin/school-sis/whatsapp/opt-in'),
          live('wa-gateway', 'Gateway / API Settings', '/admin/school-sis/whatsapp/settings'),
          live('wa-logs', 'Logs', '/admin/school-sis/whatsapp/logs'),
        ],
      },
      {
        id: 'notifications',
        label: 'Notifications',
        icon: Megaphone as LucideIcon,
        status: 'active',
        children: [
          live('push', 'Push Notifications', '/admin/school-sis/notifications'),
          live(
            'push-templates',
            'Notification Templates',
            '/admin/school-sis/notifications/templates',
          ),
          live(
            'push-scheduled',
            'Scheduled Notifications',
            '/admin/school-sis/notifications/scheduled',
          ),
          live('push-history', 'Notification History', '/admin/school-sis/notifications/history'),
          live('push-delivery', 'Delivery Reports', '/admin/school-sis/notifications/delivery'),
          live('push-devices', 'Device Management', '/admin/school-sis/notifications/devices'),
          live(
            'push-prefs',
            'Notification Preferences',
            '/admin/school-sis/notifications/preferences',
          ),
          live(
            'push-settings',
            'Notification Settings',
            '/admin/school-sis/notifications/settings',
          ),
        ],
      },
      {
        id: 'automation',
        label: 'Automation',
        icon: Sparkles as LucideIcon,
        status: 'active',
        children: [
          live('auto-dash', 'Automation Dashboard', '/admin/school-sis/automation'),
          live('auto-workflows', 'Workflows', '/admin/school-sis/automation/workflows'),
          live('auto-scheduled', 'Scheduled Tasks', '/admin/school-sis/automation/scheduled'),
          live('auto-rules', 'Rules & Triggers', '/admin/school-sis/automation/rules'),
          live('auto-templates', 'Templates', '/admin/school-sis/automation/templates'),
          live('auto-logs', 'Execution Logs', '/admin/school-sis/automation/logs'),
          live('auto-failed', 'Failed Jobs', '/admin/school-sis/automation/failed'),
          live('auto-reports', 'Automation Reports', '/admin/school-sis/automation/reports'),
          live('auto-settings', 'Automation Settings', '/admin/school-sis/automation/settings'),
        ],
      },
    ],
  },
  {
    id: 'reports',
    label: 'REPORTS',
    items: [
      {
        id: 'reports-analytics',
        label: 'Reports & Analytics',
        icon: FileBarChart2 as LucideIcon,
        status: 'active',
        children: [
          live('all-reports', 'All reports', '/admin/school-sis/reports'),
          live('student-reports', 'Student Reports', '/admin/school-sis/reports'),
          live('attendance-reports-hub', 'Attendance Reports', '/admin/school-sis/reports'),
          live('fee-reports-hub', 'Fee Reports', '/admin/school-sis/fees/reports'),
          live('exam-reports', 'Exam Reports', '/admin/school-sis/reports'),
          live('report-design', 'Report design', '/admin/school-sis/reports/design'),
        ],
      },
      {
        id: 'ai-insights',
        label: 'AI Insights',
        icon: Sparkles as LucideIcon,
        status: 'coming_soon',
      },
      {
        id: 'achievements',
        label: 'Achievements',
        icon: Award as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('student-achievements', 'Student Achievements'),
          soon('staff-achievements', 'Staff Achievements'),
          soon('school-achievements', 'School Achievements'),
        ],
      },
      {
        id: 'certificates',
        label: 'Certificates',
        icon: Award as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('certificate-templates', 'Certificate Templates'),
          soon('generate-certificate', 'Generate Certificate'),
          soon('certificate-history', 'Certificate History'),
        ],
      },
    ],
  },
  {
    id: 'administration',
    label: 'ADMINISTRATION',
    items: [
      {
        id: 'events',
        label: 'Events',
        icon: CalendarDays as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('school-events', 'School Events'),
          soon('event-calendar', 'Calendar'),
          soon('event-management', 'Event Management'),
        ],
      },
      {
        id: 'multi-school',
        label: 'Multi School',
        icon: Building2 as LucideIcon,
        status: 'coming_soon',
      },
      {
        id: 'mobile-app',
        label: 'Mobile App',
        icon: Smartphone as LucideIcon,
        status: 'active',
        children: [
          live('app-settings', 'App versions & store', '/admin/school-sis/mobile-app'),
          live('app-prayer', 'Morning prayer', '/admin/school-sis/mobile-app?tab=prayer'),
          live('app-push', 'Push notifications', '/admin/school-sis/mobile-app?tab=push'),
        ],
      },
    ],
  },
  {
    id: 'settings',
    label: 'SETTINGS',
    items: [
      {
        id: 'settings-general',
        label: 'General',
        icon: Settings as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('school-information', 'School Information'),
          soon('logo', 'Logo'),
          soon('address', 'Address'),
          soon('phone', 'Phone'),
          soon('email', 'Email'),
          soon('website', 'Website'),
          soon('social-links', 'Social Links'),
        ],
      },
      {
        id: 'account-security',
        label: 'Account & Security',
        icon: Shield as LucideIcon,
        status: 'active',
        children: [
          live('sec-roles', 'Roles', '/admin/school-sis/users/roles'),
          live('sec-permissions', 'Permissions', '/admin/school-sis/users/permissions'),
          live('password-policies', 'Password policies', '/admin/school-sis/users/security'),
          live('login-security', 'Login security', '/admin/school-sis/users/login-history'),
          live('sessions', 'Sessions', '/admin/school-sis/users/sessions'),
          live('audit-logs', 'Audit logs', '/admin/school-sis/users/audit'),
        ],
      },
      {
        id: 'settings-academic',
        label: 'Academic',
        icon: BookOpen as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('settings-year', 'Academic Year'),
          soon('settings-classes', 'Classes'),
          soon('settings-sections', 'Sections'),
          soon('grading', 'Grading'),
          soon('attendance-settings', 'Attendance settings'),
        ],
      },
      {
        id: 'financial-settings',
        label: 'Financial Settings',
        icon: Wallet as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('fee-settings', 'Fee settings'),
          soon('payment-config', 'Payment configuration'),
          soon('receipt-settings', 'Receipt settings'),
        ],
      },
      {
        id: 'settings-communication',
        label: 'Communication',
        icon: Megaphone as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('email-settings', 'Email'),
          soon('sms-settings', 'SMS'),
          soon('wa-settings', 'WhatsApp'),
          live('push-settings', 'Push notifications', '/admin/school-sis/notifications/settings'),
        ],
      },
      {
        id: 'localization',
        label: 'Localization',
        icon: Settings as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('timezone', 'Timezone'),
          soon('currency', 'Currency'),
          soon('date-format', 'Date format'),
          soon('language', 'Language'),
        ],
      },
      {
        id: 'integrations',
        label: 'Integrations',
        icon: Settings as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('payment-gateway', 'Payment Gateway'),
          soon('email-api', 'Email'),
          soon('sms-api', 'SMS'),
          soon('wa-api', 'WhatsApp'),
          soon('maps', 'Maps'),
          soon('storage', 'Storage'),
        ],
      },
      {
        id: 'appearance',
        label: 'Appearance',
        icon: Sparkles as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('appearance-logo', 'Logo'),
          soon('theme', 'Theme'),
          soon('brand-colours', 'Brand colours'),
          soon('login-screen', 'Login screen'),
          soon('sidebar-config', 'Sidebar configuration'),
        ],
      },
      {
        id: 'system',
        label: 'System',
        icon: Settings as LucideIcon,
        status: 'coming_soon',
        children: [
          soon('system-status', 'System status'),
          soon('cache', 'Cache'),
          soon('backup', 'Backup'),
          soon('logs', 'Logs'),
          soon('maintenance', 'Maintenance mode'),
        ],
      },
    ],
  },
  {
    id: 'cms',
    label: 'CMS & WEBSITE',
    items: [
      {
        id: 'cms-website',
        label: 'Website CMS',
        icon: Home as LucideIcon,
        status: 'active',
        children: [
          live('cms-site', 'Site & identity', '/admin/school-sis/website?view=site'),
          live('cms-pages', 'Pages & homepage', '/admin/school-sis/website?view=home'),
          live('cms-notices', 'Notices', '/admin/school-sis/website?view=notices'),
          live('cms-events', 'Events', '/admin/school-sis/website?view=events'),
          live('cms-enquiries', 'Contact / Enquiries', '/admin/school-sis/website?view=inbox'),
          live('cms-seo', 'SEO & identity', '/admin/school-sis/website?view=seo'),
          live('cms-gallery', 'Albums / Gallery', '/admin/school-sis/website/albums'),
          soon('cms-downloads', 'Downloads'),
          soon('cms-media', 'Media Library'),
        ],
      },
    ],
  },
  {
    id: 'help',
    label: 'HELP',
    items: [
      {
        id: 'documentation',
        label: 'Documentation',
        icon: HelpCircle as LucideIcon,
        status: 'coming_soon',
      },
      {
        id: 'changelog',
        label: 'Changelog',
        icon: HelpCircle as LucideIcon,
        status: 'coming_soon',
      },
      {
        id: 'support',
        label: 'Support',
        icon: HelpCircle as LucideIcon,
        status: 'coming_soon',
      },
    ],
  },
];

export const SCHOOL_SIS_NAV: SchoolErpNavModule[] = SCHOOL_SIS_NAV_GROUPS.flatMap((g) => g.items);
