import { Injectable } from '@nestjs/common';
import ExcelJS from 'exceljs';
import {
  formatInr,
  formatReportDateTime,
  guessKind,
  visibleFilters,
  type ReportBranding,
  type ReportDocument,
} from './report-types';

function hexArgb(hex: string, fallback = 'FF163A63') {
  const h = hex.replace('#', '').trim();
  if (h.length === 3) {
    return `FF${h
      .split('')
      .map((c) => c + c)
      .join('')
      .toUpperCase()}`;
  }
  if (h.length === 6) return `FF${h.toUpperCase()}`;
  if (h.length === 8) return h.toUpperCase();
  return fallback;
}

@Injectable()
export class SchoolReportExcelService {
  async render(doc: ReportDocument, branding: ReportBranding) {
    const wb = new ExcelJS.Workbook();
    wb.creator = 'School ERP';
    wb.created = new Date();
    const ws = wb.addWorksheet(doc.title.slice(0, 31) || 'Report', {
      views: [{ state: 'frozen', ySplit: 0 }],
    });
    const colCount = Math.max(doc.columns.length, 4);
    ws.columns = doc.columns.map((c) => ({
      key: c.key,
      width: c.width ?? Math.max(14, Math.min(36, c.label.length + 8)),
    }));

    let row = 1;
    if (branding.logoDataUri) {
      const base64 = branding.logoDataUri.replace(
        /^data:image\/\w+;base64,/,
        '',
      );
      const img = wb.addImage({ base64, extension: 'png' });
      ws.addImage(img, {
        tl: { col: Math.max(0, (colCount - 1) / 2 - 0.4), row: 0 },
        ext: { width: 70, height: 70 },
      });
      row = 5;
    }

    const titleRow = ws.getRow(row);
    titleRow.getCell(1).value = branding.schoolName.toUpperCase();
    titleRow.font = {
      bold: true,
      size: 16,
      color: { argb: hexArgb(branding.primaryColor) },
    };
    titleRow.alignment = { horizontal: 'center' };
    ws.mergeCells(row, 1, row, colCount);
    row += 1;

    const addr = ws.getRow(row);
    addr.getCell(1).value =
      `${branding.addressLine}, ${branding.district}, ${branding.state} - ${branding.pin}`;
    addr.alignment = { horizontal: 'center' };
    addr.font = { size: 10, color: { argb: 'FF4A5A6A' } };
    ws.mergeCells(row, 1, row, colCount);
    row += 1;

    const reportTitle = ws.getRow(row);
    reportTitle.getCell(1).value = doc.title.toUpperCase();
    reportTitle.font = {
      bold: true,
      size: 12,
      color: { argb: hexArgb(branding.primaryColor) },
    };
    reportTitle.alignment = { horizontal: 'center' };
    ws.mergeCells(row, 1, row, colCount);
    row += 1;

    if (doc.subtitle || doc.academicYear) {
      const sub = ws.getRow(row);
      sub.getCell(1).value = [
        doc.subtitle,
        doc.academicYear ? `Academic Year: ${doc.academicYear}` : '',
      ]
        .filter(Boolean)
        .join('  ·  ');
      sub.alignment = { horizontal: 'center' };
      ws.mergeCells(row, 1, row, colCount);
      row += 1;
    }

    const generated = formatReportDateTime(new Date(), branding.timezone);
    const meta = ws.getRow(row);
    meta.getCell(1).value =
      `Generated on: ${generated}${doc.generatedBy ? `  |  Generated by: ${doc.generatedBy}` : ''}`;
    meta.font = { italic: true, size: 9, color: { argb: 'FF5A6A7A' } };
    ws.mergeCells(row, 1, row, colCount);
    row += 2;

    if (branding.showFilters) {
      for (const f of visibleFilters(doc.filters)) {
        const r = ws.getRow(row);
        r.getCell(1).value = f.label;
        r.getCell(1).font = { bold: true, size: 9 };
        r.getCell(2).value = f.value;
        row += 1;
      }
      row += 1;
    }

    if (doc.kpis?.length) {
      const kpi = ws.getRow(row);
      doc.kpis.forEach((k, i) => {
        kpi.getCell(i + 1).value = `${k.label}: ${k.value}`;
        kpi.getCell(i + 1).font = { bold: true };
      });
      row += 2;
    }

    const headerRowIndex = row;
    const header = ws.getRow(row);
    doc.columns.forEach((c, i) => {
      const cell = header.getCell(i + 1);
      cell.value = c.label.toUpperCase();
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 9 };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: hexArgb(branding.primaryColor) },
      };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFD9E2EC' } },
        left: { style: 'thin', color: { argb: 'FFD9E2EC' } },
        bottom: { style: 'thin', color: { argb: 'FFD9E2EC' } },
        right: { style: 'thin', color: { argb: 'FFD9E2EC' } },
      };
      cell.alignment = { vertical: 'middle' };
    });
    row += 1;

    const dataStart = row;
    doc.rows.forEach((record, idx) => {
      const r = ws.getRow(row);
      doc.columns.forEach((c, i) => {
        const cell = r.getCell(i + 1);
        const kind = guessKind(c, record[c.key]);
        const raw = record[c.key];
        if (kind === 'currency') {
          const n = Number(raw);
          cell.value = Number.isFinite(n) ? n : 0;
          cell.numFmt = '"₹"#,##,##0.00';
          cell.alignment = { horizontal: 'right' };
        } else if (kind === 'number') {
          cell.value = Number(raw) || 0;
          cell.alignment = { horizontal: 'right' };
        } else {
          cell.value = raw == null ? '' : String(raw);
        }
        if (idx % 2 === 1) {
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: hexArgb(branding.secondaryColor, 'FFEAF2F8') },
          };
        }
        cell.border = {
          bottom: { style: 'thin', color: { argb: 'FFD9E2EC' } },
        };
      });
      row += 1;
    });

    if (doc.totals && doc.rows.length) {
      const r = ws.getRow(row);
      doc.columns.forEach((c, i) => {
        const cell = r.getCell(i + 1);
        cell.font = { bold: true };
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF3F6FA' },
        };
        if (i === 0) {
          cell.value = 'TOTAL';
          return;
        }
        const kind = guessKind(c);
        if (kind === 'currency' || kind === 'number') {
          const colLetter = r.getCell(i + 1).address.replace(/\d+/, '');
          cell.value = {
            formula: `SUM(${colLetter}${dataStart}:${colLetter}${row - 1})`,
          };
          if (kind === 'currency') cell.numFmt = '"₹"#,##,##0.00';
        } else if (doc.totals?.[c.key] != null) {
          cell.value = doc.totals[c.key] as string | number;
        }
      });
      row += 1;
    }

    if (!doc.rows.length) {
      ws.getRow(row).getCell(1).value =
        'NO RECORDS FOUND — No data is available for the selected filters.';
      ws.mergeCells(row, 1, row, colCount);
    }

    ws.autoFilter = {
      from: { row: headerRowIndex, column: 1 },
      to: { row: Math.max(headerRowIndex, row - 1), column: colCount },
    };
    ws.views = [{ state: 'frozen', ySplit: headerRowIndex }];

    const buf = await wb.xlsx.writeBuffer();
    return Buffer.from(buf);
  }

  csv(doc: ReportDocument) {
    const lines = [
      doc.columns.map((c) => csvCell(c.label)).join(','),
      ...doc.rows.map((row) =>
        doc.columns
          .map((c) => {
            const kind = guessKind(c, row[c.key]);
            return csvCell(
              kind === 'currency' ? formatInr(row[c.key]) : row[c.key],
            );
          })
          .join(','),
      ),
    ];
    return Buffer.from(lines.join('\n'), 'utf8');
  }
}

function csvCell(value: unknown) {
  return `"${String(value ?? '').replace(/"/g, '""')}"`;
}
