export type ReportFormat = 'pdf' | 'xlsx' | 'html' | 'csv';

export type ReportColumnKind = 'text' | 'number' | 'currency' | 'date';

export type ReportColumn = {
  key: string;
  label: string;
  kind?: ReportColumnKind;
  width?: number;
};

export type ReportKpi = { label: string; value: string | number };

export type ReportDocument = {
  key: string;
  title: string;
  subtitle?: string;
  academicYear?: string;
  filters?: Record<string, string | undefined>;
  kpis?: ReportKpi[];
  columns: ReportColumn[];
  rows: Record<string, unknown>[];
  totals?: Record<string, number | string>;
  signatures?: { role: string; name?: string }[];
  confidential?: boolean;
  official?: boolean;
  orientation?: 'portrait' | 'landscape';
  pageSize?: 'A4' | 'A3' | 'Letter';
  generatedBy?: string;
};

export type ReportBranding = {
  schoolName: string;
  shortName: string;
  addressLine: string;
  city: string;
  district: string;
  state: string;
  pin: string;
  phone: string;
  email: string;
  website: string;
  affiliation?: string;
  schoolCode?: string;
  udise?: string;
  gstin?: string;
  principalName?: string;
  signatoryName?: string;
  primaryColor: string;
  secondaryColor: string;
  textColor: string;
  borderColor: string;
  headerTextColor: string;
  fontFamily: string;
  logoDataUri: string | null;
  timezone: string;
  currency: string;
  showGeneratedBy: boolean;
  showGeneratedAt: boolean;
  showPageNumber: boolean;
  showAcademicYear: boolean;
  showFilters: boolean;
  showSignature: boolean;
  showConfidential: boolean;
  footerText: string;
  watermark?: string | null;
};

export const DEFAULT_REPORT_DESIGN = {
  schoolName: "St. Luke's Higher Secondary School",
  shortName: "St. Luke's",
  addressLine: 'Walbakgre, Tura',
  city: 'Tura',
  district: 'West Garo Hills',
  state: 'Meghalaya',
  pin: '794101',
  phone: '',
  email: '',
  website: '',
  affiliation: '',
  schoolCode: '',
  udise: '',
  gstin: '',
  principalName: '',
  signatoryName: '',
  primaryColor: '#163A63',
  secondaryColor: '#EAF2F8',
  textColor: '#172033',
  borderColor: '#D9E2EC',
  headerTextColor: '#FFFFFF',
  fontFamily: 'Inter, system-ui, sans-serif',
  timezone: 'Asia/Kolkata',
  currency: 'INR',
  showGeneratedBy: true,
  showGeneratedAt: true,
  showPageNumber: true,
  showAcademicYear: true,
  showFilters: true,
  showSignature: false,
  showConfidential: false,
  footerText: 'Generated by School ERP',
  watermark: null as string | null,
};

export function formatReportDateTime(d = new Date(), tz = 'Asia/Kolkata') {
  return new Intl.DateTimeFormat('en-IN', {
    timeZone: tz,
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  }).format(d);
}

export function formatInr(value: unknown) {
  const n =
    typeof value === 'number'
      ? value
      : Number(String(value ?? '').replace(/[^\d.-]/g, ''));
  if (!Number.isFinite(n)) return String(value ?? '');
  return `₹${n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function reportFileName(
  branding: ReportBranding,
  title: string,
  format: string,
  extra?: string,
) {
  const school = branding.shortName
    .replace(/['’]/g, '')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_|_$/g, '');
  const slug = title
    .replace(/['’]/g, '')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_|_$/g, '');
  const when =
    extra?.replace(/[^A-Za-z0-9-]+/g, '_') ||
    new Intl.DateTimeFormat('en-CA', { timeZone: branding.timezone }).format(
      new Date(),
    );
  return `${school}_${slug}_${when}.${format === 'xlsx' ? 'xlsx' : format === 'csv' ? 'csv' : 'pdf'}`;
}

export function guessKind(
  col: ReportColumn,
  sample?: unknown,
): ReportColumnKind {
  if (col.kind) return col.kind;
  const label = col.label.toLowerCase();
  if (
    /amount|fee|total|collection|tuition|arrear|paid|due|₹|inr|cash|upi/.test(
      label,
    )
  )
    return 'currency';
  if (sample instanceof Date || /date|time/.test(label)) return 'date';
  if (typeof sample === 'number') return 'number';
  return 'text';
}

export function visibleFilters(filters?: Record<string, string | undefined>) {
  const out: { label: string; value: string }[] = [];
  for (const [k, v] of Object.entries(filters ?? {})) {
    if (!v || v === 'ALL') continue;
    const label = k
      .replace(/Id$/i, '')
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, (c) => c.toUpperCase())
      .trim();
    out.push({ label, value: v });
  }
  return out;
}
