import {
  formatInr,
  formatReportDateTime,
  guessKind,
  visibleFilters,
  type ReportBranding,
  type ReportDocument,
} from './report-types';

function esc(value: unknown) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function cell(col: ReportDocument['columns'][number], value: unknown) {
  const kind = guessKind(col, value);
  if (kind === 'currency') return esc(formatInr(value));
  if (value == null || value === '') return '—';
  return esc(value);
}

export function renderReportHtml(
  doc: ReportDocument,
  branding: ReportBranding,
) {
  const generated = formatReportDateTime(new Date(), branding.timezone);
  const filters = visibleFilters(doc.filters);
  const contact = [branding.phone, branding.email, branding.website]
    .filter(Boolean)
    .join('  ·  ');
  const place = [
    branding.addressLine,
    [branding.district, branding.state].filter(Boolean).join(', ') +
      (branding.pin ? ` - ${branding.pin}` : ''),
  ]
    .filter(Boolean)
    .join('<br/>');
  const kpiHtml = (doc.kpis ?? [])
    .map(
      (k) =>
        `<div class="kpi"><div class="kpi-l">${esc(k.label)}</div><div class="kpi-v">${esc(k.value)}</div></div>`,
    )
    .join('');
  const filterHtml =
    branding.showFilters && filters.length
      ? `<section class="filters"><h3>Report filters</h3><table class="meta">${filters
          .map(
            (f) => `<tr><th>${esc(f.label)}</th><td>${esc(f.value)}</td></tr>`,
          )
          .join('')}</table></section>`
      : '';
  const empty = !doc.rows.length
    ? `<div class="empty"><strong>NO RECORDS FOUND</strong><p>No data is available for the selected filters.</p><p>Generated on: ${esc(generated)}</p></div>`
    : '';
  const head = doc.columns.map((c) => `<th>${esc(c.label)}</th>`).join('');
  const body = doc.rows
    .map((row, i) => {
      const tds = doc.columns.map((c) => {
        const kind = guessKind(c, row[c.key]);
        return `<td class="${kind}">${cell(c, row[c.key])}</td>`;
      });
      return `<tr class="${i % 2 ? 'alt' : ''}">${tds.join('')}</tr>`;
    })
    .join('');
  const totalKeys = Object.keys(doc.totals ?? {});
  const totals = totalKeys.length
    ? `<tr class="total">${doc.columns
        .map((c, i) => {
          if (i === 0) return '<td>TOTAL</td>';
          const v = doc.totals?.[c.key];
          return `<td class="${guessKind(c)}">${v == null ? '' : cell(c, v)}</td>`;
        })
        .join('')}</tr>`
    : '';
  const signs =
    branding.showSignature || doc.signatures?.length
      ? `<section class="signs">${(doc.signatures?.length
          ? doc.signatures
          : [
              { role: 'Prepared By', name: '' },
              {
                role: 'Checked By',
                name: branding.signatoryName || 'Accountant',
              },
              {
                role: 'Authorized By',
                name: branding.principalName || 'Principal',
              },
            ]
        )
          .map(
            (s) =>
              `<div><div class="line"></div><div>${esc(s.role)}</div><div class="muted">${esc(s.name || '')}</div></div>`,
          )
          .join('')}</section>`
      : '';
  const label =
    doc.confidential || branding.showConfidential
      ? '<div class="badge">CONFIDENTIAL</div>'
      : doc.official
        ? '<div class="badge">OFFICIAL SCHOOL RECORD</div>'
        : '';
  const metaBits = [
    branding.showGeneratedAt ? `Generated on: ${esc(generated)}` : '',
    branding.showGeneratedBy && doc.generatedBy
      ? `Generated by: ${esc(doc.generatedBy)}`
      : '',
    branding.showAcademicYear && doc.academicYear
      ? `Academic Year: ${esc(doc.academicYear)}`
      : '',
  ].filter(Boolean);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(doc.title)}</title>
<style>
  @page { size: ${doc.pageSize || 'A4'} ${doc.orientation === 'landscape' ? 'landscape' : 'portrait'}; margin: 14mm 12mm 18mm; }
  * { box-sizing: border-box; }
  body { margin: 0; color: ${branding.textColor}; font-family: ${branding.fontFamily}; font-size: 11px; }
  .wrap { padding: 0 4px; }
  header { text-align: center; border-bottom: 2px solid ${branding.primaryColor}; padding-bottom: 10px; margin-bottom: 12px; }
  header img { height: 64px; width: auto; object-fit: contain; display: block; margin: 0 auto 6px; }
  .school { font-size: 16px; font-weight: 700; letter-spacing: .04em; color: ${branding.primaryColor}; text-transform: uppercase; }
  .place { color: #4a5a6a; line-height: 1.4; margin-top: 4px; }
  h1 { font-size: 13px; letter-spacing: .08em; margin: 12px 0 4px; text-transform: uppercase; }
  .sub { color: #4a5a6a; margin-bottom: 8px; }
  .kpis { display: flex; flex-wrap: wrap; gap: 8px; margin: 10px 0 14px; }
  .kpi { flex: 1; min-width: 120px; border: 1px solid ${branding.borderColor}; background: ${branding.secondaryColor}; padding: 8px 10px; border-radius: 6px; }
  .kpi-l { font-size: 9px; color: #5a6a7a; text-transform: uppercase; }
  .kpi-v { font-size: 14px; font-weight: 700; margin-top: 2px; }
  table.data { width: 100%; border-collapse: collapse; }
  table.data th { background: ${branding.primaryColor}; color: ${branding.headerTextColor}; font-size: 9px; letter-spacing: .04em; text-align: left; padding: 6px 7px; }
  table.data td { border-bottom: 1px solid ${branding.borderColor}; padding: 5px 7px; }
  table.data tr.alt td { background: ${branding.secondaryColor}; }
  table.data tr.total td { font-weight: 700; background: #f3f6fa; border-top: 2px solid ${branding.primaryColor}; }
  td.currency, td.number { text-align: right; font-variant-numeric: tabular-nums; }
  thead { display: table-header-group; }
  tr { page-break-inside: avoid; }
  .filters, .empty, .signs { break-inside: avoid; }
  .filters h3 { font-size: 10px; margin: 0 0 6px; letter-spacing: .06em; text-transform: uppercase; color: ${branding.primaryColor}; }
  table.meta th { text-align: left; font-weight: 600; padding: 2px 12px 2px 0; color: #5a6a7a; }
  .empty { text-align: center; padding: 28px 12px; border: 1px dashed ${branding.borderColor}; margin: 16px 0; }
  .meta-line { color: #5a6a7a; margin: 8px 0 12px; }
  .badge { display: inline-block; font-size: 9px; letter-spacing: .12em; border: 1px solid ${branding.primaryColor}; color: ${branding.primaryColor}; padding: 2px 8px; margin-bottom: 8px; }
  .signs { display: flex; justify-content: space-between; margin-top: 36px; gap: 16px; text-align: center; }
  .signs .line { border-bottom: 1px solid #9aa8b6; height: 36px; margin-bottom: 6px; }
  .muted { color: #6b7c8d; font-size: 10px; }
  footer.page { display: none; }
  .watermark { position: fixed; inset: 18% 0 0; text-align: center; font-size: 64px; font-weight: 700; letter-spacing: .2em; color: ${branding.primaryColor}; opacity: .06; transform: rotate(-24deg); pointer-events: none; z-index: 0; }
  .wrap { position: relative; z-index: 1; }
</style>
</head>
<body>
  ${branding.watermark ? `<div class="watermark">${esc(branding.watermark)}</div>` : ''}
  <div class="wrap">
    <header>
      ${branding.logoDataUri ? `<img src="${branding.logoDataUri}" alt="School logo"/>` : ''}
      <div class="school">${esc(branding.schoolName)}</div>
      <div class="place">${place}${contact ? `<br/>${esc(contact)}` : ''}</div>
      ${label}
      <h1>${esc(doc.title)}</h1>
      ${doc.subtitle ? `<div class="sub">${esc(doc.subtitle)}</div>` : ''}
    </header>
    <div class="meta-line">${metaBits.join('  ·  ')}</div>
    ${filterHtml}
    ${kpiHtml ? `<div class="kpis">${kpiHtml}</div>` : ''}
    ${empty}
    ${
      doc.rows.length
        ? `<table class="data"><thead><tr>${head}</tr></thead><tbody>${body}${totals}</tbody></table>`
        : ''
    }
    ${signs}
  </div>
</body>
</html>`;
}
