import {
  BadRequestException,
  ConflictException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../../database/prisma.service';
import { UserProvisioningService } from '../../administration/services/user-provisioning.service';
import type { CreateStaffDto } from '../dto/staff.dto';
import { EmployeeCodeService } from './employee-code.service';
import { StaffEmploymentService } from './staff-employment.service';
import {
  assertBiometricIdUnique,
  normalizeBiometricId,
} from '../utils/staff-biometric.util';

@Injectable()
export class StaffProvisioningService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly provisioning: UserProvisioningService,
    private readonly employment: StaffEmploymentService,
    private readonly employeeCodes: EmployeeCodeService,
  ) {}

  async create(
    tenantId: string,
    dto: CreateStaffDto & {
      aadhaarNo?: string;
      photoUrl?: string;
      addressJson?: Prisma.InputJsonValue;
      status?: string;
    },
    actorUserId?: string,
  ) {
    const autoGenerate = dto.employeeCodeAutoGenerated !== false;
    const staffType = dto.staffType ?? 'TEACHING';

    if (dto.email) {
      const emailTaken = await this.prisma.staffProfile.findFirst({
        where: {
          tenantId,
          deletedAt: null,
          email: dto.email.trim().toLowerCase(),
        },
      });
      if (emailTaken) {
        throw new ConflictException(
          'Email already linked to another staff member',
        );
      }
    }

    if (dto.rfidNo?.trim()) {
      const rfidTaken = await this.prisma.staffProfile.findFirst({
        where: {
          tenantId,
          deletedAt: null,
          rfidNo: dto.rfidNo.trim(),
        },
      });
      if (rfidTaken) throw new ConflictException('RFID number already in use');
    }

    const biometricId = normalizeBiometricId(dto.biometricId);
    if (biometricId) {
      await assertBiometricIdUnique(this.prisma, tenantId, biometricId, {
        departmentId: dto.departmentId,
        primaryShiftId: dto.primaryShiftId,
      });
    }

    if (dto.departmentId) {
      await this.assertDepartment(tenantId, dto.departmentId);
    }
    if (dto.designationId) {
      await this.assertDesignation(tenantId, dto.designationId);
    }
    if (dto.primaryShiftId) {
      await this.assertShift(tenantId, dto.primaryShiftId);
    }

    await this.employment.assertValidEmploymentCombo(
      tenantId,
      staffType,
      dto.designationId,
      dto.departmentId,
      dto.additionalRoleCodes,
    );

    let campusId: string | null = null;
    if (dto.departmentId || dto.primaryShiftId) {
      if (dto.departmentId) {
        const dept = await this.prisma.department.findFirst({
          where: { id: dto.departmentId, tenantId, deletedAt: null },
          select: { campusId: true },
        });
        campusId = dept?.campusId ?? null;
      }
      if (!campusId && dto.primaryShiftId) {
        const shift = await this.prisma.shift.findFirst({
          where: { id: dto.primaryShiftId, tenantId, deletedAt: null },
          select: { campusId: true },
        });
        campusId = shift?.campusId ?? null;
      }
    }

    let institutionId = dto.institutionId;
    if (!institutionId && campusId) {
      const campus = await this.prisma.campus.findFirst({
        where: { id: campusId, tenantId, deletedAt: null },
        select: { institutionId: true },
      });
      institutionId = campus?.institutionId;
    }

    let employeeCode = dto.employeeCode?.trim() ?? '';
    let employeeCodeAutoGenerated = autoGenerate;

    if (autoGenerate) {
      const allocated = await this.employeeCodes.allocateNextEmployeeCode(
        tenantId,
        {
          institutionId,
          staffType,
          joiningDate: dto.joiningDate,
          actorId: actorUserId,
          action: 'ALLOCATE',
        },
      );
      employeeCode = allocated.employeeCode;
      employeeCodeAutoGenerated = true;
    } else {
      if (!employeeCode) {
        throw new BadRequestException(
          'Employee code is required when manual override is enabled',
        );
      }
      await this.employeeCodes.validateEmployeeCodeUniqueTx(
        this.prisma,
        tenantId,
        employeeCode,
      );
      employeeCodeAutoGenerated = false;
    }

    let portalUserId: string | undefined;
    let generatedPassword: string | undefined;

    if (dto.createPortalAccount) {
      if (!dto.email) {
        throw new BadRequestException(
          'Email is required for portal account creation',
        );
      }
      const roleSlugs = this.resolveRoleSlugs(dto);

      const { user, plainPassword } =
        await this.provisioning.ensureUserWithRoles(
          tenantId,
          dto.email,
          roleSlugs,
          {
            password: dto.password,
            userTypeForUsername:
              dto.staffType === 'TEACHING' ? 'FACULTY' : 'STAFF',
            mustResetPassword: true,
            displayName: dto.fullName,
            phone: dto.mobile,
            shiftId: dto.primaryShiftId,
          },
        );
      portalUserId = user.id;
      generatedPassword = plainPassword;
    }

    const staff = await this.prisma.staffProfile.create({
      data: {
        tenantId,
        employeeCode,
        employeeCodeAutoGenerated,
        employeeCodeAllocatedAt: employeeCodeAutoGenerated ? new Date() : null,
        fullName: dto.fullName.trim(),
        email: dto.email?.trim().toLowerCase(),
        mobile: dto.mobile?.trim(),
        staffType: dto.staffType ?? 'TEACHING',
        employmentType: dto.employmentType ?? 'PERMANENT',
        departmentId: dto.departmentId,
        designationId: dto.designationId,
        primaryShiftId: dto.primaryShiftId,
        teachingShiftCategory: dto.teachingShiftCategory ?? 'DAY',
        campusId,
        shortCode: dto.shortCode?.trim().toUpperCase() || undefined,
        joiningDate: dto.joiningDate ? new Date(dto.joiningDate) : undefined,
        gender: dto.gender,
        dateOfBirth: dto.dateOfBirth ? new Date(dto.dateOfBirth) : undefined,
        qualification: dto.qualification,
        specialization: dto.specialization,
        experienceYears: dto.experienceYears,
        rfidNo: dto.rfidNo?.trim(),
        biometricId,
        aadhaarNo: dto.aadhaarNo?.trim(),
        photoUrl: dto.photoUrl?.trim(),
        addressJson: dto.addressJson,
        portalUserId,
        status: dto.status ?? 'ACTIVE',
      },
      include: this.defaultInclude(),
    });

    if (dto.primaryShiftId) {
      await this.prisma.staffShiftAssignment.upsert({
        where: {
          staffProfileId_shiftId: {
            staffProfileId: staff.id,
            shiftId: dto.primaryShiftId,
          },
        },
        create: {
          tenantId,
          staffProfileId: staff.id,
          shiftId: dto.primaryShiftId,
          isPrimary: true,
          active: true,
        },
        update: { isPrimary: true, active: true },
      });
    }

    if (!employeeCodeAutoGenerated) {
      await this.prisma.staffEmployeeCodeAuditLog.create({
        data: {
          tenantId,
          institutionId: institutionId ?? null,
          staffProfileId: staff.id,
          action: 'MANUAL_OVERRIDE',
          employeeCode,
          newValue: employeeCode,
          manualOverride: true,
          createdById: actorUserId,
        },
      });
    }

    return { staff, generatedPassword, actorUserId };
  }

  async mergeFromImport(
    tenantId: string,
    staffProfileId: string,
    dto: CreateStaffDto & {
      aadhaarNo?: string;
      photoUrl?: string;
      addressJson?: Prisma.InputJsonValue;
      status?: string;
    },
    mode: 'MERGE' | 'REPLACE',
    actorUserId?: string,
  ) {
    const existing = await this.prisma.staffProfile.findFirst({
      where: { id: staffProfileId, tenantId, deletedAt: null },
    });
    if (!existing) {
      throw new NotFoundException('Staff member not found');
    }

    if (
      dto.email &&
      dto.email.trim().toLowerCase() !== existing.email?.toLowerCase()
    ) {
      const emailTaken = await this.prisma.staffProfile.findFirst({
        where: {
          tenantId,
          deletedAt: null,
          email: dto.email.trim().toLowerCase(),
          NOT: { id: staffProfileId },
        },
      });
      if (emailTaken) {
        throw new ConflictException(
          'Email already linked to another staff member',
        );
      }
    }

    if (
      dto.employeeCode &&
      dto.employeeCode.trim().toUpperCase() !==
        existing.employeeCode.toUpperCase()
    ) {
      const codeTaken = await this.prisma.staffProfile.findFirst({
        where: {
          tenantId,
          deletedAt: null,
          employeeCode: dto.employeeCode.trim(),
          NOT: { id: staffProfileId },
        },
      });
      if (codeTaken) {
        throw new ConflictException('Employee code already in use');
      }
    }

    if (dto.departmentId)
      await this.assertDepartment(tenantId, dto.departmentId);
    if (dto.designationId)
      await this.assertDesignation(tenantId, dto.designationId);
    if (dto.primaryShiftId)
      await this.assertShift(tenantId, dto.primaryShiftId);

    let portalUserId = existing.portalUserId ?? undefined;
    let generatedPassword: string | undefined;

    if (dto.createPortalAccount && !existing.portalUserId) {
      if (!dto.email) {
        throw new BadRequestException(
          'Email is required for portal account creation',
        );
      }
      const roleSlugs = this.resolveRoleSlugs(dto);
      const { user, plainPassword } =
        await this.provisioning.ensureUserWithRoles(
          tenantId,
          dto.email,
          roleSlugs,
          {
            password: dto.password,
            userTypeForUsername:
              dto.staffType === 'TEACHING' ? 'FACULTY' : 'STAFF',
            mustResetPassword: true,
            displayName: dto.fullName ?? existing.fullName,
            phone: dto.mobile,
            shiftId: dto.primaryShiftId,
          },
        );
      portalUserId = user.id;
      generatedPassword = plainPassword;
    }

    const mergeData: Prisma.StaffProfileUpdateInput = {};

    const setIf = <K extends keyof Prisma.StaffProfileUpdateInput>(
      key: K,
      value: Prisma.StaffProfileUpdateInput[K] | undefined | null,
      always = false,
    ) => {
      if (always || (value !== undefined && value !== null && value !== '')) {
        mergeData[key] = value as Prisma.StaffProfileUpdateInput[K];
      }
    };

    if (mode === 'REPLACE') {
      mergeData.fullName = dto.fullName?.trim() ?? existing.fullName;
      mergeData.email = dto.email?.trim().toLowerCase() ?? null;
      mergeData.mobile = dto.mobile?.trim() ?? null;
      mergeData.staffType = dto.staffType ?? existing.staffType;
      mergeData.employmentType = dto.employmentType ?? existing.employmentType;
      mergeData.department = dto.departmentId
        ? { connect: { id: dto.departmentId } }
        : { disconnect: true };
      mergeData.designation = dto.designationId
        ? { connect: { id: dto.designationId } }
        : { disconnect: true };
      mergeData.primaryShift = dto.primaryShiftId
        ? { connect: { id: dto.primaryShiftId } }
        : { disconnect: true };
      mergeData.joiningDate = dto.joiningDate
        ? new Date(dto.joiningDate)
        : null;
      mergeData.gender = dto.gender ?? null;
      mergeData.dateOfBirth = dto.dateOfBirth
        ? new Date(dto.dateOfBirth)
        : null;
      mergeData.qualification = dto.qualification ?? null;
      mergeData.specialization = dto.specialization ?? null;
      mergeData.experienceYears = dto.experienceYears ?? null;
      mergeData.aadhaarNo = dto.aadhaarNo ?? null;
      mergeData.photoUrl = dto.photoUrl ?? null;
      mergeData.addressJson = dto.addressJson ?? Prisma.JsonNull;
      mergeData.status = dto.status ?? existing.status;
      if (dto.employeeCode) mergeData.employeeCode = dto.employeeCode.trim();
    } else {
      setIf('fullName', dto.fullName?.trim());
      setIf('email', dto.email?.trim().toLowerCase());
      setIf('mobile', dto.mobile?.trim());
      setIf('staffType', dto.staffType);
      setIf('employmentType', dto.employmentType);
      if (dto.departmentId)
        mergeData.department = { connect: { id: dto.departmentId } };
      if (dto.designationId)
        mergeData.designation = { connect: { id: dto.designationId } };
      if (dto.primaryShiftId)
        mergeData.primaryShift = { connect: { id: dto.primaryShiftId } };
      if (dto.joiningDate) mergeData.joiningDate = new Date(dto.joiningDate);
      setIf('gender', dto.gender);
      if (dto.dateOfBirth) mergeData.dateOfBirth = new Date(dto.dateOfBirth);
      setIf('qualification', dto.qualification);
      setIf('specialization', dto.specialization);
      if (dto.experienceYears != null)
        mergeData.experienceYears = dto.experienceYears;
      setIf('aadhaarNo', dto.aadhaarNo);
      setIf('photoUrl', dto.photoUrl);
      if (dto.addressJson) mergeData.addressJson = dto.addressJson;
      setIf('status', dto.status);
      if (dto.employeeCode) mergeData.employeeCode = dto.employeeCode.trim();
    }

    if (portalUserId && portalUserId !== existing.portalUserId) {
      mergeData.portalUser = { connect: { id: portalUserId } };
    }

    const staff = await this.prisma.staffProfile.update({
      where: { id: staffProfileId },
      data: mergeData,
      include: this.defaultInclude(),
    });

    if (dto.primaryShiftId) {
      await this.prisma.staffShiftAssignment.upsert({
        where: {
          staffProfileId_shiftId: {
            staffProfileId: staff.id,
            shiftId: dto.primaryShiftId,
          },
        },
        create: {
          tenantId,
          staffProfileId: staff.id,
          shiftId: dto.primaryShiftId,
          isPrimary: true,
          active: true,
        },
        update: { isPrimary: true, active: true },
      });
    }

    return { staff, generatedPassword, actorUserId };
  }

  resolveRoleSlugs(dto: CreateStaffDto): string[] {
    if (dto.portalRoleSlugs?.length) return dto.portalRoleSlugs;
    switch (dto.staffType) {
      case 'TEACHING':
      case 'GUEST':
      case 'VISITING':
        return ['faculty'];
      case 'ADMIN':
        return ['institution-admin'];
      default:
        return ['staff'];
    }
  }

  async deactivate(tenantId: string, staffProfileId: string) {
    const staff = await this.prisma.staffProfile.findFirst({
      where: { id: staffProfileId, tenantId, deletedAt: null },
    });
    if (!staff) throw new NotFoundException('Staff member not found');

    await this.prisma.$transaction(async (tx) => {
      await tx.staffProfile.update({
        where: { id: staffProfileId },
        data: {
          status: 'INACTIVE',
          deletedAt: new Date(),
        },
      });

      if (staff.portalUserId) {
        await tx.user.update({
          where: { id: staff.portalUserId },
          data: { isActive: false, accountStatus: 'inactive' },
        });
      }
    });

    return { ok: true };
  }

  async provisionPortal(
    tenantId: string,
    staffProfileId: string,
    input: {
      email: string;
      roleSlugs?: string[];
      password?: string;
      shiftId?: string;
      campusId?: string;
    },
    actorUserId?: string,
  ) {
    const staff = await this.prisma.staffProfile.findFirst({
      where: { id: staffProfileId, tenantId, deletedAt: null },
    });
    if (!staff) throw new NotFoundException('Staff member not found');
    if (staff.portalUserId) {
      throw new ConflictException('Staff member already has a portal account');
    }

    const roleSlugs = input.roleSlugs?.length
      ? input.roleSlugs
      : staff.staffType === 'TEACHING'
        ? ['faculty']
        : ['staff'];

    const { user, plainPassword } = await this.provisioning.ensureUserWithRoles(
      tenantId,
      input.email,
      roleSlugs,
      {
        password: input.password,
        userTypeForUsername:
          staff.staffType === 'TEACHING' ? 'FACULTY' : 'STAFF',
        mustResetPassword: true,
        displayName: staff.fullName,
        phone: staff.mobile ?? undefined,
        shiftId: input.shiftId ?? staff.primaryShiftId ?? undefined,
        campusId: input.campusId,
      },
    );

    const updated = await this.prisma.staffProfile.update({
      where: { id: staffProfileId },
      data: {
        portalUserId: user.id,
        email: input.email.trim().toLowerCase(),
      },
      include: this.defaultInclude(),
    });

    return { staff: updated, generatedPassword: plainPassword, actorUserId };
  }

  defaultInclude(): Prisma.StaffProfileInclude {
    return {
      department: { select: { id: true, code: true, name: true } },
      designation: { select: { id: true, code: true, label: true } },
      primaryShift: { select: { id: true, code: true, name: true } },
      portalUser: {
        select: {
          id: true,
          email: true,
          username: true,
          isActive: true,
          accountStatus: true,
          mustResetPassword: true,
        },
      },
      shiftAssignments: {
        where: { active: true },
        include: { shift: { select: { id: true, code: true, name: true } } },
      },
      additionalRoles: {
        where: { active: true },
        select: { id: true, roleCode: true, roleName: true, active: true },
      },
      _count: {
        select: {
          subjectAssignments: true,
          offeringSections: true,
          documents: true,
        },
      },
    };
  }

  private async assertDepartment(tenantId: string, departmentId: string) {
    const dept = await this.prisma.department.findFirst({
      where: { id: departmentId, tenantId, deletedAt: null },
    });
    if (!dept) throw new BadRequestException('Invalid department');
  }

  private async assertDesignation(tenantId: string, designationId: string) {
    const designation = await this.prisma.designation.findFirst({
      where: { id: designationId, tenantId, isActive: true },
    });
    if (!designation) throw new BadRequestException('Invalid designation');
  }

  private async assertShift(tenantId: string, shiftId: string) {
    const shift = await this.prisma.shift.findFirst({
      where: { id: shiftId, tenantId, deletedAt: null, status: 'ACTIVE' },
    });
    if (!shift) throw new BadRequestException('Invalid shift');
  }
}
