import { SchoolEmpty, SchoolShell } from '@/components/school-sis/school-shell';
import { hideStaffAdminModules } from '@/features/school/permissions';
import { useSchoolSession } from '@/store/school-session';

export default function SchoolPayrollScreen() {
  const persona = useSchoolSession((s) => s.persona);
  const features = useSchoolSession((s) => s.features);
  if (hideStaffAdminModules(persona) || features.payroll === false) {
    return (
      <SchoolShell title="Payroll">
        <SchoolEmpty title="Not available" />
      </SchoolShell>
    );
  }
  return (
    <SchoolShell title="Payslips">
      <SchoolEmpty
        title="No payslip"
        body="Salary slips are generated by payroll on the ERP. Bank details are never shown on mobile."
      />
    </SchoolShell>
  );
}
