import { SchoolEmpty, SchoolShell } from '@/components/school-sis/school-shell';
import { hideStaffAdminModules } from '@/features/school/permissions';
import { useSchoolSession } from '@/store/school-session';

export default function SchoolReportsScreen() {
  const persona = useSchoolSession((s) => s.persona);
  if (hideStaffAdminModules(persona) || persona === 'teacher') {
    return (
      <SchoolShell title="Reports">
        <SchoolEmpty
          title="Not available"
          body="Reports stay on authorized office and admin accounts."
        />
      </SchoolShell>
    );
  }
  return (
    <SchoolShell title="Reports">
      <SchoolEmpty
        title="Use school ERP report design"
        body="PDFs are generated by the backend with school letterhead."
      />
    </SchoolShell>
  );
}
