'use client';

import { useQuery } from '@tanstack/react-query';
import { History } from 'lucide-react';

import { AdminPageHeader } from '@/components/administration-module/admin-page-header';
import { AdminShell, AdminGlassCard } from '@/components/administration-module/ui/admin-shell';
import { DashboardShell } from '@/components/layout/dashboard-shell';
import { useRequireAuth } from '@/hooks/use-auth';
import { fetchRollNumberHistory } from '@/services/roll-number';

export function RollNumberHistoryPage() {
  useRequireAuth();

  const historyQ = useQuery({
    queryKey: ['admin', 'roll-number-history'],
    queryFn: fetchRollNumberHistory,
  });

  return (
    <DashboardShell role="admin" title="Roll Number History">
      <AdminShell>
        <AdminPageHeader
          title="Roll Number History"
          subtitle="Permanent audit trail of bulk roll number generation batches."
        />

        <AdminGlassCard className="p-4">
          <h2 className="flex items-center gap-2 text-sm font-semibold">
            <History className="h-4 w-4" />
            Generation Batches
          </h2>

          {historyQ.isLoading ? (
            <p className="mt-4 text-sm text-muted-foreground">Loading history…</p>
          ) : (
            <div className="mt-4 overflow-x-auto">
              <table className="w-full min-w-[720px] text-sm">
                <thead>
                  <tr className="border-b text-left text-xs text-muted-foreground">
                    <th className="pb-2 pr-3">Batch</th>
                    <th className="pb-2 pr-3">Date</th>
                    <th className="pb-2 pr-3">Generated By</th>
                    <th className="pb-2 pr-3">Academic Year</th>
                    <th className="pb-2 pr-3">Students</th>
                    <th className="pb-2 pr-3">Roll Range</th>
                    <th className="pb-2">Notes</th>
                  </tr>
                </thead>
                <tbody>
                  {(historyQ.data ?? []).map((batch) => (
                    <tr key={batch.id} className="border-b border-border/40">
                      <td className="py-2 pr-3 font-mono font-semibold">
                        #{String(batch.batchNumber).padStart(3, '0')}
                      </td>
                      <td className="py-2 pr-3">
                        {new Date(batch.generatedAt).toLocaleString('en-IN')}
                      </td>
                      <td className="py-2 pr-3">{batch.generatedBy}</td>
                      <td className="py-2 pr-3">{batch.admissionYear ?? '—'}</td>
                      <td className="py-2 pr-3">{batch.studentsProcessed}</td>
                      <td className="py-2 pr-3 font-mono text-xs">
                        {batch.firstRollNumber && batch.lastRollNumber
                          ? `${batch.firstRollNumber} → ${batch.lastRollNumber}`
                          : '—'}
                      </td>
                      <td className="py-2 text-xs text-muted-foreground">
                        {batch.blockedCount > 0 ? `${batch.blockedCount} blocked · ` : ''}
                        {batch.excludedCount > 0 ? `${batch.excludedCount} excluded` : '—'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              {!historyQ.data?.length && (
                <p className="py-8 text-center text-sm text-muted-foreground">
                  No bulk generation batches recorded yet.
                </p>
              )}
            </div>
          )}
        </AdminGlassCard>
      </AdminShell>
    </DashboardShell>
  );
}
