import { todayIsoDate } from '@/utils/format-date';

export type PendingStaffDocument = {
  documentType: string;

  fileName: string;
};

export type DraftSubjectAssignment = {
  courseId: string;

  courseLabel: string;

  offeringSectionId?: string;

  programVersionId?: string;

  semesterNo: number;

  category?: string | null;

  shiftId?: string;

  isPrimaryFaculty?: boolean;
};

export type AddStaffDraft = {
  employeeCode: string;

  employeeCodePreview: string;

  employeeCodeAutoGenerated: boolean;

  employeeCodeFinalized: boolean;

  employeeCodeSourceStaffType: string;

  photoPreviewUrl: string;

  fullName: string;

  email: string;

  mobile: string;

  gender: string;

  dateOfBirth: string;

  qualification: string;

  specialization: string;

  experienceYears?: number;

  rfidNo: string;

  biometricId: string;

  staffType: string;

  employmentType: string;

  departmentId: string;

  designationId: string;

  primaryShiftId: string;

  additionalShiftIds: string[];

  additionalRoleCodes: string[];

  shortCode: string;

  campusId: string;

  joiningDate: string;

  probationEndDate: string;

  confirmationDate: string;

  status: string;

  createPortalAccount: boolean;

  portalEmail: string;

  portalRoleSlugs: string[];

  portalPassword: string;

  bankName: string;

  accountNumber: string;

  ifsc: string;

  pfNumber: string;

  basicPay: string;

  addressLine1: string;

  addressLine2: string;

  addressCity: string;

  addressState: string;

  addressPin: string;

  emergencyName: string;

  emergencyPhone: string;

  subjectAssignments: DraftSubjectAssignment[];

  pendingDocuments: PendingStaffDocument[];

  draftSavedAt: string;

  draftVersion: number;
};

export function createEmptyDraft(): AddStaffDraft {
  return {
    employeeCode: '',

    employeeCodePreview: '',

    employeeCodeAutoGenerated: true,

    employeeCodeFinalized: false,

    employeeCodeSourceStaffType: '',

    photoPreviewUrl: '',

    fullName: '',

    email: '',

    mobile: '',

    gender: '',

    dateOfBirth: '',

    qualification: '',

    specialization: '',

    experienceYears: undefined,

    rfidNo: '',

    biometricId: '',

    staffType: 'TEACHING',

    employmentType: 'PERMANENT',

    departmentId: '',

    designationId: '',

    primaryShiftId: '',

    additionalShiftIds: [],

    additionalRoleCodes: [],

    shortCode: '',

    campusId: '',

    joiningDate: todayIsoDate(),

    probationEndDate: '',

    confirmationDate: '',

    status: 'ACTIVE',

    createPortalAccount: false,

    portalEmail: '',

    portalRoleSlugs: ['faculty'],

    portalPassword: '',

    bankName: '',

    accountNumber: '',

    ifsc: '',

    pfNumber: '',

    basicPay: '',

    addressLine1: '',

    addressLine2: '',

    addressCity: '',

    addressState: '',

    addressPin: '',

    emergencyName: '',

    emergencyPhone: '',

    subjectAssignments: [],

    pendingDocuments: [],

    draftSavedAt: '',

    draftVersion: 1,
  };
}
