export type ProposalTemplateContext = {
  institutionName: string;
  proposalDate: string;
  proposalVersion: string;
  addressLine: string;
  studentStrength: number;
  perStudentSubscriptionRate: number;
  contactPerson: string;
  contactEmail: string;
  contactPhone: string;
  companyName: string;
  companyTagline: string;
  companyEmail: string;
  companyPhone: string;
  companyWebsite: string;
  companyWebsiteLabel: string;
  primaryColor: string;
  secondaryColor: string;
  proposalTheme: string;
  backgroundImageUrl: string | null;
  dashboardScreenshotUrl: string | null;
  mobileScreenshotUrl: string | null;
  principalDashboardScreenshotUrl: string | null;
  signatureUrl: string | null;
  qrCodeUrl: string | null;
  logoDataUri: string | null;
  bclLogoDataUri: string | null;
  pricingLines: Array<{ label: string; amount: number }>;
  sectionToggles: Record<string, boolean>;
  copy: Record<string, string>;
};
