export const ACCT_VOUCHER_TYPES = [
  'RECEIPT',
  'PAYMENT',
  'CONTRA',
  'JOURNAL',
  'DEBIT_NOTE',
  'CREDIT_NOTE',
  'SALES_INVOICE',
  'PURCHASE_INVOICE',
  'REVERSAL',
] as const;

export type AcctVoucherType = (typeof ACCT_VOUCHER_TYPES)[number];

export const ACCT_VOUCHER_PREFIX: Record<AcctVoucherType, string> = {
  RECEIPT: 'RCT',
  PAYMENT: 'PMT',
  CONTRA: 'CTR',
  JOURNAL: 'JV',
  DEBIT_NOTE: 'DN',
  CREDIT_NOTE: 'CN',
  SALES_INVOICE: 'SI',
  PURCHASE_INVOICE: 'PUR',
  REVERSAL: 'REV',
};

export const ACCT_PAYMENT_MODES = [
  'CASH',
  'UPI',
  'BANK_TRANSFER',
  'NEFT',
  'RTGS',
  'IMPS',
  'CHEQUE',
  'CARD',
  'PAYMENT_GATEWAY',
  'OTHER',
] as const;

export const MODE_TO_ASSET: Record<string, string> = {
  CASH: 'CASH',
  UPI: 'UPI',
  BANK: 'BANK',
  BANK_TRANSFER: 'BANK',
  NEFT: 'BANK',
  RTGS: 'BANK',
  IMPS: 'BANK',
  CHEQUE: 'BANK',
  CARD: 'GATEWAY_RECEIVABLE',
  ONLINE: 'GATEWAY_RECEIVABLE',
  PAYMENT_GATEWAY: 'GATEWAY_RECEIVABLE',
  OTHER: 'CASH',
};

export const COST_CENTRE_SEED = [
  ['SCH', 'School'],
  ['PRI', 'Primary Section'],
  ['SEC', 'Secondary Section'],
  ['HSS', 'Higher Secondary'],
  ['TRN', 'Transport'],
  ['LIB', 'Library'],
  ['LAB', 'Laboratory'],
  ['HOS', 'Hostel'],
  ['CAN', 'Canteen'],
  ['ADM', 'Administration'],
  ['SPT', 'Sports'],
] as const;

export type CoaSeed = {
  code: string;
  name: string;
  type: 'ASSET' | 'LIABILITY' | 'EQUITY' | 'INCOME' | 'EXPENSE';
  parentCode?: string;
  systemKey?: string;
  moduleKey?: string;
  isGroup?: boolean;
};

export const DEFAULT_COA: CoaSeed[] = [
  { code: '1000', name: 'Assets', type: 'ASSET', isGroup: true },
  {
    code: '1100',
    name: 'Current Assets',
    type: 'ASSET',
    parentCode: '1000',
    isGroup: true,
  },
  {
    code: '1101',
    name: 'Cash',
    type: 'ASSET',
    parentCode: '1100',
    systemKey: 'CASH',
    moduleKey: 'accounts',
  },
  {
    code: '1102',
    name: 'Bank',
    type: 'ASSET',
    parentCode: '1100',
    systemKey: 'BANK',
    moduleKey: 'accounts',
  },
  {
    code: '1103',
    name: 'UPI Receivable',
    type: 'ASSET',
    parentCode: '1100',
    systemKey: 'UPI',
    moduleKey: 'fees',
  },
  {
    code: '1104',
    name: 'Fee Receivable',
    type: 'ASSET',
    parentCode: '1100',
    systemKey: 'FEE_RECEIVABLE',
    moduleKey: 'fees',
  },
  {
    code: '1105',
    name: 'Payment Gateway Receivable',
    type: 'ASSET',
    parentCode: '1100',
    systemKey: 'GATEWAY_RECEIVABLE',
    moduleKey: 'fees',
  },
  {
    code: '1106',
    name: 'Advances',
    type: 'ASSET',
    parentCode: '1100',
    systemKey: 'ADVANCES',
  },
  {
    code: '1500',
    name: 'Fixed Assets',
    type: 'ASSET',
    parentCode: '1000',
    isGroup: true,
  },
  {
    code: '1501',
    name: 'Buildings',
    type: 'ASSET',
    parentCode: '1500',
    systemKey: 'BUILDING',
  },
  {
    code: '1502',
    name: 'Furniture',
    type: 'ASSET',
    parentCode: '1500',
    systemKey: 'FURNITURE',
  },
  {
    code: '1503',
    name: 'Computers',
    type: 'ASSET',
    parentCode: '1500',
    systemKey: 'COMPUTERS',
  },
  {
    code: '1504',
    name: 'Vehicles',
    type: 'ASSET',
    parentCode: '1500',
    systemKey: 'VEHICLES',
  },
  {
    code: '1505',
    name: 'Equipment',
    type: 'ASSET',
    parentCode: '1500',
    systemKey: 'EQUIPMENT',
  },
  {
    code: '1590',
    name: 'Accumulated Depreciation',
    type: 'ASSET',
    parentCode: '1500',
    systemKey: 'ACCUM_DEPN',
  },
  { code: '2000', name: 'Liabilities', type: 'LIABILITY', isGroup: true },
  {
    code: '2100',
    name: 'Current Liabilities',
    type: 'LIABILITY',
    parentCode: '2000',
    isGroup: true,
  },
  {
    code: '2101',
    name: 'Vendor Payables',
    type: 'LIABILITY',
    parentCode: '2100',
    systemKey: 'VENDOR_PAYABLE',
    moduleKey: 'procurement',
  },
  {
    code: '2102',
    name: 'Salary Payable',
    type: 'LIABILITY',
    parentCode: '2100',
    systemKey: 'SALARY_PAYABLE',
    moduleKey: 'hr_payroll',
  },
  {
    code: '2103',
    name: 'TDS Payable',
    type: 'LIABILITY',
    parentCode: '2100',
    systemKey: 'TDS_PAYABLE',
    moduleKey: 'accounts',
  },
  {
    code: '2104',
    name: 'GST Payable',
    type: 'LIABILITY',
    parentCode: '2100',
    systemKey: 'GST_PAYABLE',
  },
  {
    code: '2105',
    name: 'Other Payables',
    type: 'LIABILITY',
    parentCode: '2100',
    systemKey: 'OTHER_PAYABLE',
  },
  {
    code: '3000',
    name: 'Funds / Corpus',
    type: 'EQUITY',
    isGroup: true,
  },
  {
    code: '3100',
    name: 'Corpus / Accumulated Surplus',
    type: 'EQUITY',
    parentCode: '3000',
    systemKey: 'CORPUS',
  },
  { code: '4000', name: 'Income', type: 'INCOME', isGroup: true },
  {
    code: '4101',
    name: 'Tuition Fees',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'TUITION_FEES',
    moduleKey: 'fees',
  },
  {
    code: '4102',
    name: 'Admission Fees',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'ADMISSION_FEES',
    moduleKey: 'fees',
  },
  {
    code: '4103',
    name: 'Examination Fees',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'EXAM_FEES',
    moduleKey: 'fees',
  },
  {
    code: '4104',
    name: 'Transport Fees',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'TRANSPORT_FEES',
    moduleKey: 'transport',
  },
  {
    code: '4105',
    name: 'Library Fees',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'LIBRARY_FEES',
    moduleKey: 'library',
  },
  {
    code: '4106',
    name: 'Computer Fees',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'COMPUTER_FEES',
    moduleKey: 'fees',
  },
  {
    code: '4107',
    name: 'Hostel Fees',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'HOSTEL_FEES',
    moduleKey: 'fees',
  },
  {
    code: '4108',
    name: 'Late Fee Income',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'LATE_FEE',
    moduleKey: 'fees',
  },
  {
    code: '4201',
    name: 'Donations',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'DONATIONS',
  },
  {
    code: '4202',
    name: 'Grants',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'GRANTS',
  },
  {
    code: '4203',
    name: 'Interest Income',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'INTEREST_INCOME',
  },
  {
    code: '4204',
    name: 'Stationery Sales',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'STATIONERY_SALES',
    moduleKey: 'stationery',
  },
  {
    code: '4205',
    name: 'Library Fine Income',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'LIBRARY_FINE',
    moduleKey: 'library',
  },
  {
    code: '4299',
    name: 'Other Income',
    type: 'INCOME',
    parentCode: '4000',
    systemKey: 'OTHER_INCOME',
  },
  { code: '5000', name: 'Expenses', type: 'EXPENSE', isGroup: true },
  {
    code: '5101',
    name: 'Salaries',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'SALARIES',
    moduleKey: 'hr_payroll',
  },
  {
    code: '5102',
    name: 'Electricity',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'ELECTRICITY',
  },
  {
    code: '5103',
    name: 'Water',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'WATER',
  },
  {
    code: '5104',
    name: 'Internet',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'INTERNET',
  },
  {
    code: '5105',
    name: 'Repairs',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'REPAIRS',
  },
  {
    code: '5106',
    name: 'Stationery',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'STATIONERY_EXP',
  },
  {
    code: '5107',
    name: 'Transport',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'TRANSPORT_EXP',
    moduleKey: 'transport',
  },
  {
    code: '5108',
    name: 'Examination',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'EXAM_EXP',
  },
  {
    code: '5109',
    name: 'Library',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'LIBRARY_EXP',
  },
  {
    code: '5110',
    name: 'Sports',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'SPORTS',
  },
  {
    code: '5111',
    name: 'Maintenance',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'MAINTENANCE',
  },
  {
    code: '5112',
    name: 'Insurance',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'INSURANCE',
  },
  {
    code: '5113',
    name: 'Professional Fees',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'PROF_FEES',
  },
  {
    code: '5114',
    name: 'Depreciation',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'DEPRECIATION',
  },
  {
    code: '5115',
    name: 'Gateway Charges',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'GATEWAY_CHARGES',
    moduleKey: 'fees',
  },
  {
    code: '5116',
    name: 'Fee Concession',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'CONCESSION',
    moduleKey: 'fees',
  },
  {
    code: '5199',
    name: 'Miscellaneous',
    type: 'EXPENSE',
    parentCode: '5000',
    systemKey: 'MISC_EXP',
  },
];

export const DEFAULT_APPROVAL_RULES = [
  { min: '0', max: '5000', role: 'accountant', sort: 1 },
  { min: '5000.01', max: '25000', role: 'accounts-manager', sort: 2 },
  { min: '25000.01', max: '100000', role: 'principal', sort: 3 },
  { min: '100000.01', max: null, role: 'management', sort: 4 },
] as const;
