export const LIB_COPY_STATUSES = [
  'AVAILABLE',
  'ISSUED',
  'RESERVED',
  'OVERDUE',
  'LOST',
  'DAMAGED',
  'UNDER_REPAIR',
  'WITHDRAWN',
  'MISSING',
] as const;

export const LIB_BOOK_TYPES = [
  'Textbook',
  'Reference Book',
  'Story Book',
  'Novel',
  'Biography',
  'Dictionary',
  'Encyclopedia',
  'Magazine',
  'Journal',
  'Competition Book',
  'Religious Book',
  'General Knowledge',
  'Other',
];

export const LIB_CATEGORIES = [
  'English',
  'Mathematics',
  'Science',
  'Physics',
  'Chemistry',
  'Biology',
  'History',
  'Geography',
  'Computer Science',
  'General Knowledge',
  'Literature',
  'Religion',
  'Children',
  'Reference',
  'Competitive Exams',
];

export const DEFAULT_CIRC_RULES = [
  {
    memberKind: 'STUDENT',
    gradePattern: null,
    maxBooks: 2,
    loanDays: 14,
    maxRenewals: 1,
    finePerDay: '2.00',
    graceDays: 0,
  },
  {
    memberKind: 'STUDENT',
    gradePattern: 'NURSERY,LKG,UKG',
    maxBooks: 1,
    loanDays: 7,
    maxRenewals: 0,
    finePerDay: '1.00',
    graceDays: 0,
  },
  {
    memberKind: 'STUDENT',
    gradePattern: 'I,II,III,IV',
    maxBooks: 2,
    loanDays: 14,
    maxRenewals: 1,
    finePerDay: '2.00',
    graceDays: 0,
  },
  {
    memberKind: 'STUDENT',
    gradePattern: 'V,VI,VII,VIII',
    maxBooks: 3,
    loanDays: 14,
    maxRenewals: 1,
    finePerDay: '2.00',
    graceDays: 0,
  },
  {
    memberKind: 'STUDENT',
    gradePattern: 'IX,X',
    maxBooks: 3,
    loanDays: 21,
    maxRenewals: 1,
    finePerDay: '2.00',
    graceDays: 0,
  },
  {
    memberKind: 'STUDENT',
    gradePattern: 'XI,XII',
    maxBooks: 4,
    loanDays: 21,
    maxRenewals: 1,
    finePerDay: '2.00',
    graceDays: 0,
  },
  {
    memberKind: 'TEACHING',
    gradePattern: null,
    maxBooks: 5,
    loanDays: 30,
    maxRenewals: 2,
    finePerDay: '5.00',
    graceDays: 0,
  },
  {
    memberKind: 'NON_TEACHING',
    gradePattern: null,
    maxBooks: 2,
    loanDays: 14,
    maxRenewals: 1,
    finePerDay: '2.00',
    graceDays: 0,
  },
] as const;
