export type StationeryCategorySeed = {
  code: string;
  name: string;
  children: Array<{ code: string; name: string }>;
};

export const STATIONERY_CATEGORY_SEED: StationeryCategorySeed[] = [
  {
    code: 'BOOKS',
    name: 'Books',
    children: [
      { code: 'TEXT_BOOKS', name: 'Text Books' },
      { code: 'WORK_BOOKS', name: 'Work Books' },
      { code: 'REFERENCE_BOOKS', name: 'Reference Books' },
      { code: 'ACTIVITY_BOOKS', name: 'Activity Books' },
      { code: 'PRACTICAL_BOOKS', name: 'Practical Books' },
      { code: 'SCHOOL_PUBLICATIONS', name: 'School Publications' },
      { code: 'QUESTION_BANKS', name: 'Question Banks' },
      { code: 'OTHER_BOOKS', name: 'Other Books' },
    ],
  },
  {
    code: 'NOTEBOOKS',
    name: 'Notebooks & Writing Material',
    children: [
      { code: 'CLASS_NOTEBOOK', name: 'Class Notebook' },
      { code: 'LONG_NOTEBOOK', name: 'Long Notebook' },
      { code: 'SMALL_NOTEBOOK', name: 'Small Notebook' },
      { code: 'DRAWING_NOTEBOOK', name: 'Drawing Notebook' },
      { code: 'PRACTICAL_NOTEBOOK', name: 'Practical Notebook' },
      { code: 'RECORD_NOTEBOOK', name: 'Record Notebook' },
      { code: 'ASSIGNMENT_NOTEBOOK', name: 'Assignment Notebook' },
      { code: 'ROUGH_NOTEBOOK', name: 'Rough Notebook' },
      { code: 'GRAPH_NOTEBOOK', name: 'Graph Notebook' },
    ],
  },
  {
    code: 'WRITING',
    name: 'Writing Instruments',
    children: [
      { code: 'BALL_PEN', name: 'Ball Pen' },
      { code: 'GEL_PEN', name: 'Gel Pen' },
      { code: 'FOUNTAIN_PEN', name: 'Fountain Pen' },
      { code: 'PENCIL', name: 'Pencil' },
      { code: 'MECHANICAL_PENCIL', name: 'Mechanical Pencil' },
      { code: 'MARKER', name: 'Marker' },
      { code: 'HIGHLIGHTER', name: 'Highlighter' },
      { code: 'SKETCH_PEN', name: 'Sketch Pen' },
      { code: 'WHITEBOARD_MARKER', name: 'Whiteboard Marker' },
    ],
  },
  {
    code: 'PAPER_FILES',
    name: 'Paper & Files',
    children: [
      { code: 'A4_PAPER', name: 'A4 Paper' },
      { code: 'LEGAL_PAPER', name: 'Legal Paper' },
      { code: 'COLOUR_PAPER', name: 'Colour Paper' },
      { code: 'CHART_PAPER', name: 'Chart Paper' },
      { code: 'DRAWING_SHEET', name: 'Drawing Sheet' },
      { code: 'EXAM_SHEETS', name: 'Exam Sheets' },
      { code: 'ANSWER_SHEETS', name: 'Answer Sheets' },
      { code: 'FILE', name: 'File' },
      { code: 'FOLDER', name: 'Folder' },
      { code: 'ENVELOPE', name: 'Envelope' },
    ],
  },
  {
    code: 'GEOMETRY',
    name: 'Geometry & Mathematical Items',
    children: [
      { code: 'SCALE_RULER', name: 'Scale/Ruler' },
      { code: 'ERASER', name: 'Eraser' },
      { code: 'SHARPENER', name: 'Sharpener' },
      { code: 'COMPASS', name: 'Compass' },
      { code: 'DIVIDER', name: 'Divider' },
      { code: 'PROTRACTOR', name: 'Protractor' },
      { code: 'SET_SQUARE', name: 'Set Square' },
      { code: 'GEOMETRY_BOX', name: 'Geometry Box' },
      { code: 'CALCULATOR', name: 'Calculator' },
    ],
  },
  {
    code: 'ART_CRAFT',
    name: 'Art & Craft',
    children: [
      { code: 'CRAYONS', name: 'Crayons' },
      { code: 'COLOUR_PENCIL', name: 'Colour Pencil' },
      { code: 'WATER_COLOUR', name: 'Water Colour' },
      { code: 'POSTER_COLOUR', name: 'Poster Colour' },
      { code: 'PAINT_BRUSH', name: 'Paint Brush' },
      { code: 'CRAFT_PAPER', name: 'Craft Paper' },
      { code: 'GLUE_ART', name: 'Glue' },
      { code: 'FEVICOL', name: 'Fevicol' },
      { code: 'SCISSORS_ART', name: 'Scissors' },
      { code: 'CLAY', name: 'Clay' },
      { code: 'ART_KIT', name: 'Art Kit' },
    ],
  },
  {
    code: 'UNIFORM',
    name: 'School Uniform',
    children: [
      { code: 'SHIRT', name: 'Shirt' },
      { code: 'TROUSERS', name: 'Trousers' },
      { code: 'SHORTS', name: 'Shorts' },
      { code: 'SKIRT', name: 'Skirt' },
      { code: 'TIE', name: 'Tie' },
      { code: 'BELT', name: 'Belt' },
      { code: 'SOCKS', name: 'Socks' },
      { code: 'SWEATER', name: 'Sweater' },
      { code: 'BLAZER', name: 'Blazer' },
      { code: 'SPORTS_TSHIRT', name: 'Sports T-Shirt' },
      { code: 'SPORTS_SHORTS', name: 'Sports Shorts' },
      { code: 'HOUSE_TSHIRT', name: 'House T-Shirt' },
      { code: 'HOUSE_ITEMS', name: 'House-specific items' },
    ],
  },
  {
    code: 'FOOTWEAR',
    name: 'Footwear',
    children: [
      { code: 'SCHOOL_SHOES', name: 'School Shoes' },
      { code: 'SPORTS_SHOES', name: 'Sports Shoes' },
      { code: 'SANDALS', name: 'Sandals' },
      { code: 'OTHER_FOOTWEAR', name: 'Other approved footwear' },
    ],
  },
  {
    code: 'ACCESSORIES',
    name: 'School Accessories',
    children: [
      { code: 'SCHOOL_BAG', name: 'School Bag' },
      { code: 'ID_CARD', name: 'ID Card' },
      { code: 'ID_CARD_HOLDER', name: 'ID Card Holder' },
      { code: 'LANYARD', name: 'Lanyard' },
      { code: 'WATER_BOTTLE', name: 'Water Bottle' },
      { code: 'LUNCH_BOX', name: 'Lunch Box' },
      { code: 'UMBRELLA', name: 'Umbrella' },
      { code: 'CAP', name: 'Cap' },
      { code: 'BADGE', name: 'Badge' },
      { code: 'HOUSE_BADGE', name: 'House Badge' },
      { code: 'SCHOOL_TIE', name: 'School Tie' },
    ],
  },
  {
    code: 'OFFICE',
    name: 'Office / General Stationery',
    children: [
      { code: 'STAPLER', name: 'Stapler' },
      { code: 'STAPLER_PINS', name: 'Stapler Pins' },
      { code: 'PAPER_CLIPS', name: 'Paper Clips' },
      { code: 'BINDER_CLIPS', name: 'Binder Clips' },
      { code: 'RUBBER_BANDS', name: 'Rubber Bands' },
      { code: 'GLUE_OFFICE', name: 'Glue' },
      { code: 'TAPE', name: 'Tape' },
      { code: 'CORRECTION_PEN', name: 'Correction Pen' },
      { code: 'CORRECTION_TAPE', name: 'Correction Tape' },
      { code: 'SCISSORS_OFFICE', name: 'Scissors' },
      { code: 'CUTTER', name: 'Cutter' },
      { code: 'FILES_OFFICE', name: 'Files' },
      { code: 'REGISTERS', name: 'Registers' },
      { code: 'RECEIPT_BOOKS', name: 'Receipt Books' },
    ],
  },
  {
    code: 'EXAM',
    name: 'Examination Material',
    children: [
      { code: 'ANSWER_BOOK', name: 'Answer Book' },
      { code: 'SUPPLEMENTARY_SHEET', name: 'Supplementary Sheet' },
      { code: 'GRAPH_SHEET', name: 'Graph Sheet' },
      { code: 'PRACTICAL_RECORD', name: 'Practical Record' },
      { code: 'EXAM_PAD', name: 'Exam Pad' },
      { code: 'EXAM_ENVELOPE', name: 'Exam Envelope' },
      { code: 'OTHER_EXAM', name: 'Other examination stationery' },
    ],
  },
];
